// src/components/config/PluginRuntimeSwitchRow.vue
<script setup lang="ts">
import { computed } from "vue";
import ConsoleSwitch from "@/components/ConsoleSwitch.vue";
import { boolSwitchLabel } from "@/utils/configFieldDisplay";

const props = withDefaults(
  defineProps<{
    modelValue: boolean;
    title: string;
    disabled?: boolean;
  }>(),
  {
    disabled: false,
  },
);

const emit = defineEmits<{
  "update:modelValue": [value: boolean];
}>();

const switchLabel = computed(() => boolSwitchLabel(props.modelValue));
</script>

<template>
  <div
    class="plugin-runtime-switch"
    :class="{ 'plugin-runtime-switch--disabled': disabled }"
  >
    <div class="plugin-runtime-switch__row">
      <span class="plugin-runtime-switch__title">{{ title }}</span>
      <ConsoleSwitch
        :model-value="modelValue"
        :label="switchLabel"
        :disabled="disabled"
        @update:model-value="emit('update:modelValue', $event)"
      />
    </div>
    <div class="plugin-runtime-switch__desc">
      <slot />
    </div>
  </div>
</template>

// react/src/components/config/PluginRuntimeSwitchRow.tsx
import type { ReactNode } from "react";
import ConsoleSwitch from "@/components/ConsoleSwitch";
import { cn } from "@/lib/utils";

export default function PluginRuntimeSwitchRow({
  title,
  checked,
  disabled = false,
  variant = "card",
  onCheckedChange,
  children,
}: {
  title: string;
  checked: boolean;
  disabled?: boolean;
  variant?: "card" | "plain";
  onCheckedChange: (next: boolean) => void;
  children?: ReactNode;
}) {
  const switchLabel = checked ? "开启" : "关闭";
  return (
    <div
      className={cn(
        "plugin-runtime-switch",
        disabled && "plugin-runtime-switch--disabled",
        variant === "plain" && "plugin-runtime-switch--plain",
      )}
    >
      <div className="plugin-runtime-switch__row">
        <span className="plugin-runtime-switch__title">{title}</span>
        <ConsoleSwitch
          checked={checked}
          label={switchLabel}
          disabled={disabled}
          onCheckedChange={onCheckedChange}
        />
      </div>
      {children ? <div className="plugin-runtime-switch__desc">{children}</div> : null}
    </div>
  );
}
