// src/components/config/ConfigFieldRenderer.tsx
import type { PluginConfigField } from "@/api/console";
import ConsoleSwitch from "@/components/ConsoleSwitch";
import TagsInput from "@/components/config/TagsInput";
import UiInput from "@/components/ui/UiInput";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { cn } from "@/lib/utils";
import {
  binaryEnumIsOn,
  binaryEnumOffChoice,
  binaryEnumOnChoice,
  binaryEnumSwitchLabel,
  boolChoiceLabel,
  enumChoiceLabel,
  fieldDisplayTitle,
  isBinaryBoolEnum,
} from "@/utils/configFieldDisplay";
import {
  idTagsFromJsonText,
  idTagsToJsonText,
  isChipListField,
  isIdListField,
  tagsFromJsonText,
  tagsToJsonText,
} from "@/utils/pluginConfigFieldModel";

function fieldChoices(field: PluginConfigField): string[] {
  if (field.choices?.length) return field.choices;
  return (field.options || []).map((o) => (typeof o === "string" ? o : o.value));
}

export default function ConfigFieldRenderer({
  field,
  modelValue,
  onValueChange,
  showLabel = true,
  showMeta = true,
  showDescription = true,
  inputMaxWidth = "520px",
}: {
  field: PluginConfigField;
  modelValue: string;
  onValueChange: (value: string) => void;
  showLabel?: boolean;
  showMeta?: boolean;
  showDescription?: boolean;
  inputMaxWidth?: string;
}) {
  const choices = fieldChoices(field);
  const fieldWithChoices = { ...field, choices };
  const usesBoolSwitch = field.kind === "bool" || isBinaryBoolEnum(fieldWithChoices);
  const usesEnumSelect = field.kind === "enum" && choices.length > 0 && !isBinaryBoolEnum(fieldWithChoices);
  const usesNumberInput = field.kind === "int" || field.kind === "float" || field.kind === "number";
  const usesSecretInput = field.kind === "string" && Boolean(field.secret);
  const usesMultiline = field.kind === "string" && Boolean(field.multiline);
  const usesTags = isChipListField(field);
  const usesIdTags = isIdListField(field);

  const boolOn =
    field.kind === "bool" ? modelValue === "true" : binaryEnumIsOn(fieldWithChoices, modelValue);
  const boolLabel =
    field.kind === "bool"
      ? boolChoiceLabel(modelValue)
      : binaryEnumSwitchLabel(fieldWithChoices, modelValue);

  function onBoolChange(checked: boolean) {
    if (field.kind === "bool") {
      onValueChange(checked ? "true" : "false");
      return;
    }
    onValueChange(
      checked ? binaryEnumOnChoice(fieldWithChoices) : binaryEnumOffChoice(fieldWithChoices),
    );
  }

  const tags = usesTags
    ? usesIdTags
      ? idTagsFromJsonText(modelValue)
      : tagsFromJsonText(modelValue)
    : [];

  const enumKnown = choices.includes(modelValue);
  const enumSelectValue = modelValue || undefined;

  return (
    <div className={cn("config-field-renderer form-field", usesBoolSwitch && "config-field-renderer--bool")}>
      {usesBoolSwitch && showLabel ? (
        <div className="config-field-renderer__bool-head">
          <div className="config-field-renderer__title form-field__label form-field__label--title">
            {fieldDisplayTitle(field)}
          </div>
          <ConsoleSwitch
            checked={boolOn}
            label={boolLabel}
            ariaLabel={boolLabel}
            onCheckedChange={onBoolChange}
          />
        </div>
      ) : null}
      {usesBoolSwitch && !showLabel ? (
        <div className="config-field-renderer__bool-only">
          <ConsoleSwitch
            checked={boolOn}
            label={boolLabel}
            ariaLabel={boolLabel}
            onCheckedChange={onBoolChange}
          />
        </div>
      ) : null}
      {!usesBoolSwitch && showLabel ? (
        <div className="form-field__label form-field__label--title config-field-renderer__title">
          {fieldDisplayTitle(field)}
        </div>
      ) : null}

      {showDescription && field.description ? (
        <div className="muted common-config-field-desc config-field-renderer__desc">{field.description}</div>
      ) : null}
      {showMeta ? (
        <div className="muted config-field-renderer__meta">
          配置键: <code>{field.env_key || field.name}</code>
          {" · "}默认：{JSON.stringify(field.default)}
        </div>
      ) : null}

      {usesEnumSelect ? (
        <Select value={enumSelectValue} onValueChange={onValueChange}>
          <SelectTrigger
            className="form-field__control w-full"
            style={{ maxWidth: inputMaxWidth }}
            aria-label={fieldDisplayTitle(field)}
          >
            <SelectValue placeholder="请选择" />
          </SelectTrigger>
          <SelectContent>
            {!enumKnown && modelValue ? (
              <SelectItem value={modelValue}>{enumChoiceLabel(modelValue, fieldWithChoices)}</SelectItem>
            ) : null}
            {choices.map((opt) => (
              <SelectItem key={opt} value={opt}>
                {enumChoiceLabel(opt, fieldWithChoices)}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      ) : null}

      {usesTags ? (
        <TagsInput
          variant="embedded"
          value={tags}
          onChange={(next) =>
            onValueChange(usesIdTags ? idTagsToJsonText(next) : tagsToJsonText(next))
          }
          placeholder={usesIdTags ? "输入号码后回车添加…" : "添加标签后回车"}
          inputMode={usesIdTags ? "numeric" : undefined}
          acceptPattern={usesIdTags ? /^\d+$/ : undefined}
        />
      ) : null}

      {!usesBoolSwitch && !usesEnumSelect && !usesTags && field.kind === "json" ? (
        <textarea
          className="textarea inp form-field__control config-field-renderer__textarea"
          rows={6}
          value={modelValue}
          spellCheck={false}
          onChange={(e) => onValueChange(e.target.value)}
          style={{ maxWidth: inputMaxWidth }}
        />
      ) : null}

      {usesSecretInput ? (
        <UiInput
          className="form-field__control"
          type="password"
          revealable
          autoComplete="off"
          value={modelValue}
          onValueChange={onValueChange}
        />
      ) : null}

      {usesNumberInput ? (
        <input
          className="inp form-field__control"
          type="number"
          value={modelValue}
          min={field.min_value}
          max={field.max_value}
          step={field.kind === "float" ? "any" : 1}
          onChange={(e) => onValueChange(e.target.value)}
          style={{ maxWidth: inputMaxWidth }}
        />
      ) : null}

      {usesMultiline ? (
        <textarea
          className="textarea form-field__control config-field-renderer__textarea"
          rows={4}
          value={modelValue}
          onChange={(e) => onValueChange(e.target.value)}
          style={{ maxWidth: inputMaxWidth }}
        />
      ) : null}

      {!usesBoolSwitch &&
      !usesEnumSelect &&
      !usesTags &&
      field.kind !== "json" &&
      !usesSecretInput &&
      !usesNumberInput &&
      !usesMultiline ? (
        <UiInput className="form-field__control" type="text" value={modelValue} onValueChange={onValueChange} />
      ) : null}
    </div>
  );
}

// src/components/config/ConfigFieldRenderer.vue
<script setup lang="ts">
import { computed } from "vue";
import type { PluginConfigField } from "@/api/pallasTypes";
import JsonTextareaField from "@/components/JsonTextareaField.vue";
import NumberStepperInput from "@/components/config/NumberStepperInput.vue";
import TagsInput from "@/components/config/TagsInput.vue";
import UiInput from "@/components/ui/UiInput.vue";
import UiSelect from "@/components/ui/UiSelect.vue";
import UiSwitch from "@/components/ui/UiSwitch.vue";
import { isStringListField, tagsFromJsonText, tagsToJsonText } from "@/utils/pluginConfigFieldModel";
import {
  binaryEnumIsOn,
  binaryEnumOffChoice,
  binaryEnumOnChoice,
  binaryEnumSwitchLabel,
  boolChoiceLabel,
  enumChoiceLabel,
  fieldDisplayTitle,
  isBinaryBoolEnum,
} from "@/utils/configFieldDisplay";

const props = withDefaults(
  defineProps<{
    field: PluginConfigField;
    modelValue: string;
    showLabel?: boolean;
    showMeta?: boolean;
    showDescription?: boolean;
    jsonTitle?: string;
    showJsonExpandButton?: boolean;
    inputMaxWidth?: string;
  }>(),
  {
    showLabel: true,
    showMeta: true,
    showDescription: true,
    showJsonExpandButton: true,
    inputMaxWidth: "520px",
  },
);

const emit = defineEmits<{
  "update:modelValue": [value: string];
}>();

const usesBoolSwitch = computed(
  () => props.field.kind === "bool" || isBinaryBoolEnum(props.field),
);

const usesEnumSelect = computed(
  () =>
    props.field.kind === "enum" &&
    Boolean(props.field.choices?.length) &&
    !isBinaryBoolEnum(props.field),
);

const usesNumberStepper = computed(
  () => props.field.kind === "int" || props.field.kind === "float",
);

const usesSecretInput = computed(
  () => props.field.kind === "string" && Boolean(props.field.secret),
);

const usesMultiline = computed(
  () => props.field.kind === "string" && Boolean(props.field.multiline),
);

const usesTagsInput = computed(() => isStringListField(props.field));

const boolSwitchValue = computed(() => {
  if (props.field.kind === "bool") return props.modelValue === "true";
  return binaryEnumIsOn(props.field, props.modelValue);
});

const boolSwitchLabelText = computed(() => {
  if (props.field.kind === "bool") return boolChoiceLabel(props.modelValue);
  return binaryEnumSwitchLabel(props.field, props.modelValue);
});

const tagsValue = computed(() => tagsFromJsonText(props.modelValue));

const numberKind = computed<"int" | "float">(() => (props.field.kind === "float" ? "float" : "int"));

function setValue(next: string) {
  emit("update:modelValue", next);
}

function onBoolChange(checked: boolean) {
  if (props.field.kind === "bool") {
    setValue(checked ? "true" : "false");
    return;
  }
  setValue(checked ? binaryEnumOnChoice(props.field) : binaryEnumOffChoice(props.field));
}

function onTagsChange(tags: string[]) {
  setValue(tagsToJsonText(tags));
}
</script>

<template>
  <div
    class="config-field-renderer form-field"
    :class="{ 'config-field-renderer--bool': usesBoolSwitch }"
  >
    <div
      v-if="usesBoolSwitch && showLabel"
      class="config-field-renderer__bool-head"
    >
      <div class="config-field-renderer__title form-field__label form-field__label--title">
        {{ fieldDisplayTitle(field) }}
        <span
          v-if="!field.label"
          class="muted config-field-renderer__kind"
        >（{{ field.kind }}）</span>
      </div>
      <UiSwitch
        :model-value="boolSwitchValue"
        :label="boolSwitchLabelText"
        :aria-label="boolSwitchLabelText"
        @update:model-value="onBoolChange"
      />
    </div>
    <div
      v-else-if="usesBoolSwitch"
      class="config-field-renderer__bool-only"
    >
      <UiSwitch
        :model-value="boolSwitchValue"
        :label="boolSwitchLabelText"
        :aria-label="boolSwitchLabelText"
        @update:model-value="onBoolChange"
      />
    </div>
    <template v-else>
      <div
        v-if="showLabel"
        class="form-field__label form-field__label--title config-field-renderer__title"
      >
        {{ fieldDisplayTitle(field) }}
        <span
          v-if="!field.label"
          class="muted config-field-renderer__kind"
        >（{{ field.kind }}）</span>
      </div>
    </template>
    <div
      v-if="showDescription && field.description"
      class="muted common-config-field-desc config-field-renderer__desc"
    >
      {{ field.description }}
    </div>
    <div
      v-if="showMeta"
      class="muted config-field-renderer__meta"
    >
      配置键: <code>{{ field.env_key }}</code>
      · 默认：{{ JSON.stringify(field.default) }}
    </div>
    <UiSelect
      v-if="usesEnumSelect"
      class="form-field__control"
      :model-value="modelValue"
      @update:model-value="setValue"
    >
      <option
        v-for="opt in field.choices"
        :key="opt"
        :value="opt"
      >
        {{ enumChoiceLabel(opt, field) }}
      </option>
    </UiSelect>
    <TagsInput
      v-else-if="usesTagsInput"
      variant="embedded"
      :model-value="tagsValue"
      @update:model-value="onTagsChange"
    />
    <JsonTextareaField
      v-else-if="field.kind === 'json'"
      :model-value="modelValue"
      :title="jsonTitle || `${field.name}（JSON）`"
      :rows="6"
      :show-expand-button="showJsonExpandButton"
      @update:model-value="setValue"
    />
    <UiInput
      v-else-if="usesSecretInput"
      class="form-field__control"
      type="password"
      revealable
      autocomplete="off"
      :model-value="modelValue"
      @update:model-value="setValue"
    />
    <NumberStepperInput
      v-else-if="usesNumberStepper"
      :model-value="modelValue"
      :kind="numberKind"
      :min="field.min_value"
      :max="field.max_value"
      :max-width="inputMaxWidth"
      @update:model-value="setValue"
    />
    <textarea
      v-else-if="usesMultiline"
      :value="modelValue"
      class="textarea form-field__control config-field-renderer__textarea"
      rows="4"
      @input="setValue(($event.target as HTMLTextAreaElement).value)"
    />
    <UiInput
      v-else-if="!usesBoolSwitch"
      class="form-field__control"
      type="text"
      :model-value="modelValue"
      @update:model-value="setValue"
    />
  </div>
</template>

<style scoped>
.config-field-renderer__title {
  margin-bottom: 0;
}
.config-field-renderer__kind {
  font-weight: 500;
}
.config-field-renderer__desc {
  font-size: 13px;
  margin-bottom: 0;
}
.config-field-renderer__bool-only {
  display: flex;
  justify-content: flex-start;
}

.config-field-renderer :deep(.form-field__control),
.config-field-renderer :deep(.json-textarea-field),
.config-field-renderer :deep(.sel),
.config-field-renderer :deep(.inp),
.config-field-renderer :deep(.ui-input-wrap),
.config-field-renderer :deep(.ui-select) {
  width: 100%;
}

.config-field-renderer :deep(.form-field__control),
.config-field-renderer :deep(.json-textarea-field),
.config-field-renderer :deep(.ui-input-wrap) {
  max-width: v-bind(inputMaxWidth);
}

.config-field-renderer__textarea {
  width: 100%;
  max-width: v-bind(inputMaxWidth);
  resize: vertical;
  font-family: inherit;
}
</style>
