// src/pages/CommunityPage.vue
<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { RouterLink } from "vue-router";
import { fetchCommunityStats, fetchCorpusStatus, fetchFederationOnboarding } from "@/api/consoleApi";
import type {
  CommunityStatsData,
  CommunityVersionCountData,
  CorpusSourceStatusData,
  CorpusStatusData,
  FederationOnboardingData,
} from "@/api/pallasTypes";
import { pushConsoleToast } from "@/utils/consoleToast";
import { copyTextToClipboard } from "@/utils/clipboard";
import ConsolePageSkeleton from "@/components/ConsolePageSkeleton.vue";
import PanelSidebarAdd from "@/components/PanelSidebarAdd.vue";
import RefreshIconButton from "@/components/RefreshIconButton.vue";
import StatCard from "@/components/StatCard.vue";
import { usePanelNavIcon } from "@/composables/usePanelNavIcon";

const panelNavIcon = usePanelNavIcon();
const pageReady = ref(false);
const refreshBusy = ref(false);
const err = ref("");
const communityStats = ref<CommunityStatsData | null>(null);
const corpusStatus = ref<CorpusStatusData | null>(null);
const federationOnboarding = ref<FederationOnboardingData | null>(null);
const federationOnboardingUnavailable = ref(false);

function formatCommunityStatNum(n: number | undefined | null): string {
  if (n == null || !Number.isFinite(n)) return "—";
  return Math.floor(n).toLocaleString();
}

const onlineHint = computed(() => {
  const sec = communityStats.value?.online_ttl_sec;
  if (sec == null || !Number.isFinite(sec) || sec < 60) return "统计窗口内";
  const m = Math.max(1, Math.round(sec / 60));
  return `近 ${m} 分钟内有心跳`;
});

const deploymentsOnlineHint = computed(
  () => `${onlineHint.value}的自托管安装`,
);

const botsOnlineHint = computed(() => {
  const sum = communityStats.value?.bots_online_sum;
  const onlineDep = communityStats.value?.deployments_online;
  if (
    sum != null &&
    Number.isFinite(sum) &&
    onlineDep != null &&
    onlineDep > 0 &&
    Number.isFinite(onlineDep)
  ) {
    const avg = sum / onlineDep;
    const avgText = avg >= 10 ? Math.round(avg).toString() : avg.toFixed(1);
    return `全网在线牛牛合计，平均每处约 ${avgText} 只`;
  }
  return "各安装向中心上报的在线牛牛合计";
});

const activeRecentHint = computed(() => {
  const total = communityStats.value?.deployments_total;
  const catalog = communityStats.value?.catalog_bots_online_sum;
  const parts: string[] = [];
  if (total != null) {
    parts.push(`历史累计 ${formatCommunityStatNum(total)} 套安装`);
  }
  if (catalog != null && Number.isFinite(catalog)) {
    parts.push(`在线名册牛牛 ${formatCommunityStatNum(catalog)} 只`);
  }
  return parts.length ? parts.join(" · ") : "近 24 小时内有心跳上报";
});

const corpusPoolValue = computed(() => {
  const ctx = formatCommunityStatNum(communityStats.value?.corpus?.contexts_total);
  const ans = formatCommunityStatNum(communityStats.value?.corpus?.answers_total);
  if (ctx === "—" && ans === "—") return "—";
  return `${ctx} 词条 · ${ans} 回复`;
});

const corpusPoolHint = computed(() => {
  const hits = communityStats.value?.corpus?.answer_hits_sum;
  if (hits != null && Number.isFinite(hits)) {
    return `回复累计被引用 ${formatCommunityStatNum(hits)} 次`;
  }
  return "共享池中的触发词与回复条目";
});

const corpusOnlineEnrollHint = computed(() => {
  const total = communityStats.value?.corpus?.enrollments_total;
  const parts: string[] = [`${onlineHint.value}且已接入共享语料`];
  if (total != null) {
    parts.push(`累计 ${formatCommunityStatNum(total)} 处自托管`);
  }
  return parts.join(" · ");
});

const corpusTotalEnrollHint = computed(() => {
  const recent = communityStats.value?.corpus?.enrollments_recent_24h;
  const contrib = communityStats.value?.corpus?.contribute_enabled_total;
  const parts: string[] = ["历史上接入过共享语料的安装数"];
  if (recent != null && recent > 0) {
    parts.push(`近 24 小时新增 ${formatCommunityStatNum(recent)} 处`);
  }
  if (contrib != null) {
    parts.push(`其中 ${formatCommunityStatNum(contrib)} 处可上传学习结果`);
  }
  return parts.join(" · ");
});

const communityAvailable = computed(() => communityStats.value != null);

const corpusPanelVisible = computed(() => {
  const corpus = communityStats.value?.corpus;
  return corpus != null && Object.keys(corpus).length > 0;
});

const onlineVersions = computed((): CommunityVersionCountData[] => {
  const rows = communityStats.value?.online_versions;
  if (!Array.isArray(rows)) return [];
  return [...rows].sort((a, b) => b.count - a.count);
});

const statsAsOfText = computed(() => {
  const asOf = (communityStats.value?.as_of || "").trim();
  return asOf ? `快照 ${asOf}` : "";
});

const statsUrl = computed(() => (communityStats.value?.stats_url || "").trim());

const allSourceKeys = ["local", "fed", "community"] as const;

type SourceKey = (typeof allSourceKeys)[number];

function fedSourceVisible(fed: CorpusSourceStatusData | undefined): boolean {
  if (!fed) return false;
  return !!(fed.configured || fed.enabled);
}

const visibleSourceKeys = computed((): SourceKey[] => {
  const keys: SourceKey[] = ["local"];
  if (fedSourceVisible(corpusStatus.value?.sources?.fed)) keys.push("fed");
  keys.push("community");
  return keys;
});

const mergeOrderSteps = computed((): Array<"local" | "fed" | "community"> => {
  const order = corpusStatus.value?.merge_order;
  if (!Array.isArray(order) || !order.length) return [];
  const allowed = new Set(["local", "fed", "community"]);
  const visible = new Set(visibleSourceKeys.value);
  return order.filter(
    (s): s is "local" | "fed" | "community" => allowed.has(s) && visible.has(s as SourceKey),
  );
});

const sourceMatrixRows = [
  { key: "enabled", label: "启用" },
  { key: "enrolled", label: "已接入" },
  { key: "readable", label: "可读" },
  { key: "writable", label: "可写" },
  { key: "contribute", label: "可贡献" },
] as const;

type MatrixRowKey = (typeof sourceMatrixRows)[number]["key"];

const localMatrixNaRows = new Set<MatrixRowKey>(["enrolled", "contribute"]);

function matrixCellState(
  sourceKey: SourceKey,
  source: CorpusSourceStatusData | undefined,
  rowKey: MatrixRowKey,
): "on" | "off" | "na" {
  if (sourceKey === "local" && localMatrixNaRows.has(rowKey)) return "na";
  if (!source) return "na";
  if (rowKey === "enabled") return source.enabled ? "on" : "off";
  if (!source.enabled) return "na";
  return source[rowKey] ? "on" : "off";
}

function matrixCellText(state: "on" | "off" | "na"): string {
  if (state === "on") return "是";
  if (state === "off") return "否";
  return "—";
}

const corpusSummaryFlow = computed(() => {
  if (!mergeOrderSteps.value.length) return "";
  return mergeOrderSteps.value.map((k) => sourceLabel(k)).join(" → ");
});

const corpusSnapshotText = computed(() => formatUnixSec(corpusStatus.value?.as_of));

const deploymentIdShort = computed(() => {
  const id = (corpusStatus.value?.deployment?.deployment_id || "").trim();
  if (!id) return "—";
  if (id.length <= 16) return id;
  return `${id.slice(0, 8)}…${id.slice(-4)}`;
});

const controlPlane = computed(() => corpusStatus.value?.control_plane);

const federationPanelVisible = computed(
  () => federationOnboarding.value != null || federationOnboardingUnavailable.value,
);

const federationSecret = computed(() => (federationOnboarding.value?.instance_secret || "").trim());

const federationCoordDisplay = computed(() => {
  const c = federationOnboarding.value?.coord;
  if (!c) return "";
  const display = (c.redis_url_display || "").trim();
  if (display) return display;
  const host = (c.host || "").trim();
  if (!host) return "";
  const port = c.port != null ? `:${c.port}` : "";
  const db = c.db != null ? `/${c.db}` : "";
  return `redis://${host}${port}${db}`;
});

const controlPlaneConfigLink = computed(() => ({
  name: "common-config" as const,
  query: {
    section: (federationOnboarding.value?.config_section_id || "control_plane").trim() || "control_plane",
  },
}));

function ingressEnabledLabel(raw: string | undefined): string {
  const s = (raw || "auto").trim() || "auto";
  if (s === "true") return "开启";
  if (s === "false") return "关闭";
  return "自动";
}

async function copyFederationSecret() {
  const text = federationSecret.value;
  if (!text) {
    pushConsoleToast("中心未提供入池密钥", "err");
    return;
  }
  if (!(await copyTextToClipboard(text))) {
    pushConsoleToast("复制失败", "err");
    return;
  }
  pushConsoleToast("已复制入池密钥", "ok");
}

function sourceApiBase(key: SourceKey): string {
  return (corpusStatus.value?.sources?.[key]?.api_base || "").trim();
}

const sourceApiEntries = computed(() =>
  visibleSourceKeys.value
    .map((key) => ({ key, url: sourceApiBase(key) }))
    .filter((row) => row.url),
);

function mergeStrategyLabel(raw: string | undefined): string {
  const s = (raw || "").trim();
  if (!s) return "—";
  const map: Record<string, string> = {
    local_first: "本地优先",
    merge_counts: "合并计数",
  };
  return map[s] || s;
}

function remoteFailureLabel(raw: string | undefined): string {
  const s = (raw || "").trim();
  if (!s) return "—";
  const map: Record<string, string> = {
    local_only: "仅用本地",
  };
  return map[s] || s;
}

function formatUnixSec(ts: number | null | undefined): string {
  if (ts == null || !Number.isFinite(ts) || ts <= 0) return "—";
  try {
    return new Date(ts * 1000).toLocaleString();
  } catch {
    return "—";
  }
}

function sourceLabel(key: SourceKey): string {
  if (key === "local") return "本地";
  if (key === "fed") return "联邦";
  return "共享池";
}

async function load(options?: { bypassCache?: boolean }) {
  err.value = "";
  try {
    const [comm, corpus, fed] = await Promise.all([
      fetchCommunityStats({ bypassCache: options?.bypassCache }).catch(() => null),
      fetchCorpusStatus().catch(() => null),
      fetchFederationOnboarding().catch(() => null),
    ]);
    communityStats.value = comm;
    corpusStatus.value = corpus;
    federationOnboarding.value = fed;
    federationOnboardingUnavailable.value = fed == null;
  } catch (e) {
    err.value = e instanceof Error ? e.message : String(e);
  } finally {
    pageReady.value = true;
  }
}

async function refresh() {
  refreshBusy.value = true;
  try {
    await load({ bypassCache: true });
  } finally {
    refreshBusy.value = false;
  }
}

onMounted(() => {
  void load();
});
</script>

<template>
  <div class="community-page">
    <ConsolePageSkeleton
      v-if="!pageReady"
      :panels="3"
    />
    <template v-else>
      <p
        v-if="err"
        class="alert alert--err community-page__alert"
      >
        {{ err }}
      </p>

      <div
        v-if="!communityAvailable"
        class="panel community-page__panel"
      >
        <div class="panel__bd muted community-page__empty">
          统计中心未返回数据。请确认本部署已启用统计上报，且中心服务可访问。
          <RouterLink
            class="community-page__inline-link"
            to="/corpus-config"
          >语料与联邦设置</RouterLink>
        </div>
      </div>

      <section
        v-if="communityAvailable"
        id="community-deploy"
        class="community-page__section"
      >
        <div class="panel community-page__panel">
          <div class="panel__hd panel__hd--split community-page__panel-hd">
            <h2 class="panel__title">
              <span
                class="panel__title-ico"
                aria-hidden="true"
              >{{ panelNavIcon }}</span>全网部署
            </h2>
            <div class="row-actions community-page__hd-actions">
              <PanelSidebarAdd main-path="/community" />
              <RefreshIconButton
                :busy="refreshBusy"
                label="刷新统计与语料数据"
                @click="refresh"
              />
            </div>
          </div>
          <div class="panel__bd">
            <div class="grid-stats community-page__deploy-grid">
              <StatCard
                dense
                label="活跃安装"
                :value="formatCommunityStatNum(communityStats?.deployments_online)"
                :hint="deploymentsOnlineHint"
              />
              <StatCard
                dense
                label="在线牛牛"
                :value="formatCommunityStatNum(communityStats?.bots_online_sum)"
                :hint="botsOnlineHint"
              />
              <StatCard
                dense
                label="分片 · 进程"
                :value="`${formatCommunityStatNum(communityStats?.deployments_online_sharded)} / ${formatCommunityStatNum(communityStats?.shard_workers_online_sum)}`"
                hint="分片架构的安装数与工作进程数"
              />
              <StatCard
                dense
                label="近 24 小时"
                :value="formatCommunityStatNum(communityStats?.active_recent_24h)"
                :hint="activeRecentHint"
              />
            </div>
            <dl class="home-dl community-page__detail-dl community-page__meta-dl">
              <dt>历史安装</dt>
              <dd>{{ formatCommunityStatNum(communityStats?.deployments_total) }} 套</dd>
              <dt>在线名册</dt>
              <dd>{{ formatCommunityStatNum(communityStats?.catalog_bots_online_sum) }} 只牛牛</dd>
              <dt>共享语料</dt>
              <dd>
                <span
                  class="badge"
                  :class="communityStats?.corpus_enabled ? 'badge--ok' : ''"
                >{{ communityStats?.corpus_enabled ? "已启用" : "未启用" }}</span>
              </dd>
              <template v-if="statsAsOfText || statsUrl">
                <dt>数据来源</dt>
                <dd class="community-page__meta-stack">
                  <span
                    v-if="statsAsOfText"
                    class="community-page__meta-line"
                  >{{ statsAsOfText }}</span>
                  <a
                    v-if="statsUrl"
                    class="community-page__ext-link community-page__meta-line community-page__mono"
                    :href="statsUrl"
                    target="_blank"
                    rel="noopener noreferrer"
                  >{{ statsUrl }}</a>
                </dd>
              </template>
            </dl>
            <div
              v-if="onlineVersions.length"
              class="community-page__versions"
            >
              <h3 class="community-page__subhd">在线版本分布</h3>
              <ul class="community-page__version-list">
                <li
                  v-for="row in onlineVersions"
                  :key="row.version"
                  class="community-page__version-row"
                >
                  <span class="community-page__version-name community-page__mono">{{ row.version || "—" }}</span>
                  <span class="community-page__version-count">{{ formatCommunityStatNum(row.count) }} 套</span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      <section
        v-if="federationPanelVisible"
        id="community-federation"
        class="community-page__section"
      >
        <div class="panel community-page__panel community-page__federation-panel">
          <div class="panel__hd panel__hd--split community-page__panel-hd">
            <h2 class="panel__title">
              <span
                class="panel__title-ico"
                aria-hidden="true"
              >◇</span>{{ federationOnboarding?.title || "联邦 Phase 2" }}
            </h2>
            <div class="row-actions community-page__hd-actions">
              <RouterLink
                class="btn btn--ghost btn--sm"
                :to="controlPlaneConfigLink"
              >联邦控制面</RouterLink>
            </div>
          </div>
          <div class="panel__bd community-page__federation-bd">
            <p
              v-if="federationOnboarding?.summary"
              class="community-page__federation-summary"
            >
              {{ federationOnboarding.summary }}
            </p>
            <p
              v-else-if="federationOnboardingUnavailable"
              class="muted community-page__federation-summary"
            >
              中心暂未开放入池说明接口；你仍可在「联邦控制面」手动填写密钥与 bootstrap 地址。
            </p>
            <p
              v-if="federationOnboarding?.ingress_note"
              class="community-page__federation-ingress-note muted"
            >
              {{ federationOnboarding.ingress_note }}
            </p>

            <div
              v-if="federationSecret"
              class="community-page__federation-secret"
            >
              <div class="community-page__federation-secret-hd">
                <span class="community-page__federation-secret-label">{{
                  federationOnboarding?.instance_secret_label || "入池密钥"
                }}</span>
                <button
                  type="button"
                  class="btn btn--ghost btn--sm"
                  @click="copyFederationSecret"
                >
                  复制密钥
                </button>
              </div>
              <code class="community-page__federation-secret-value community-page__mono">{{ federationSecret }}</code>
              <p
                v-if="federationOnboarding?.instance_secret_hint"
                class="community-page__federation-secret-hint muted"
              >
                {{ federationOnboarding.instance_secret_hint }}
              </p>
            </div>

            <dl
              v-if="federationOnboarding"
              class="home-dl community-page__detail-dl community-page__federation-meta"
            >
              <dt>联邦池</dt>
              <dd class="community-page__mono">{{ federationOnboarding.federate_id || "—" }}</dd>
              <dt>bootstrap</dt>
              <dd>
                <span
                  class="badge"
                  :class="federationOnboarding.bootstrap_enabled ? 'badge--ok' : ''"
                >{{ federationOnboarding.bootstrap_enabled ? "已启用" : "未启用" }}</span>
              </dd>
              <dt>协调 Redis</dt>
              <dd class="community-page__mono community-page__meta-line">{{ federationCoordDisplay || "—" }}</dd>
            </dl>

            <div
              v-if="controlPlane"
              class="community-page__federation-local"
            >
              <h3 class="community-page__subhd">本部署</h3>
              <div class="community-page__corpus-meta-bar">
                <span class="community-page__corpus-meta-item">
                  <span class="community-page__corpus-meta-k">控制面</span>
                  <span
                    class="community-page__corpus-meta-v"
                    :class="controlPlane.enabled ? 'is-ok' : 'is-off'"
                  >{{ controlPlane.enabled ? "已开启" : "已关闭" }}</span>
                </span>
                <span class="community-page__corpus-meta-item">
                  <span class="community-page__corpus-meta-k">密钥</span>
                  <span
                    class="community-page__corpus-meta-v"
                    :class="controlPlane.instance_secret_configured ? 'is-ok' : 'is-off'"
                  >{{ controlPlane.instance_secret_configured ? "已填写" : "未填写" }}</span>
                </span>
                <span class="community-page__corpus-meta-item">
                  <span class="community-page__corpus-meta-k">bootstrap</span>
                  <span
                    class="community-page__corpus-meta-v"
                    :class="controlPlane.bootstrap_valid ? 'is-ok' : 'is-off'"
                  >{{ controlPlane.bootstrap_valid ? "有效" : "待拉取/过期" }}</span>
                </span>
                <span class="community-page__corpus-meta-item">
                  <span class="community-page__corpus-meta-k">ingress</span>
                  <span class="community-page__corpus-meta-v">{{ ingressEnabledLabel(controlPlane.federate_ingress_enabled) }}</span>
                </span>
                <span
                  v-if="controlPlane.federate_id"
                  class="community-page__corpus-meta-item community-page__corpus-meta-item--grow"
                >
                  <span class="community-page__corpus-meta-k">池 ID</span>
                  <span class="community-page__corpus-meta-v community-page__mono">{{ controlPlane.federate_id }}</span>
                </span>
              </div>
            </div>

            <ol
              v-if="federationOnboarding?.steps?.length"
              class="community-page__federation-steps"
            >
              <li
                v-for="step in federationOnboarding.steps"
                :key="step.order"
                class="community-page__federation-step"
              >
                <span class="community-page__federation-step-title">{{ step.order }}. {{ step.title }}</span>
                <span class="community-page__federation-step-detail">{{ step.detail }}</span>
              </li>
            </ol>
          </div>
        </div>
      </section>

      <section
        v-if="corpusPanelVisible"
        id="community-corpus"
        class="community-page__section"
      >
        <div class="panel community-page__panel">
          <div class="panel__hd panel__hd--split community-page__panel-hd">
            <h2 class="panel__title">
              <span
                class="panel__title-ico"
                aria-hidden="true"
              >▦</span>共享语料
            </h2>
            <div class="row-actions community-page__hd-actions">
              <RouterLink
                class="btn btn--ghost btn--sm"
                to="/corpus-config"
              >语料设置</RouterLink>
            </div>
          </div>
          <div class="panel__bd">
            <div class="grid-stats community-page__corpus-grid">
              <StatCard
                dense
                label="词条规模"
                :value="corpusPoolValue"
                :hint="corpusPoolHint"
              />
              <StatCard
                dense
                label="在线接入"
                :value="formatCommunityStatNum(communityStats?.corpus?.enrollments_online)"
                :hint="corpusOnlineEnrollHint"
              />
              <StatCard
                dense
                label="累计接入"
                :value="formatCommunityStatNum(communityStats?.corpus?.enrollments_total)"
                :hint="corpusTotalEnrollHint"
              />
              <StatCard
                dense
                label="可上传学习"
                :value="formatCommunityStatNum(communityStats?.corpus?.contribute_enabled_total)"
                hint="已接入且允许把本机学习结果同步到共享语料池"
              />
              <StatCard
                dense
                label="回复热度"
                :value="formatCommunityStatNum(communityStats?.corpus?.answer_hits_sum)"
                hint="各回复条目在共享池中的累计引用次数"
              />
              <StatCard
                dense
                label="可读安装"
                :value="formatCommunityStatNum(communityStats?.corpus?.read_enabled_total)"
                hint="已接入且允许从共享池读取语料的安装数"
              />
            </div>
          </div>
        </div>
      </section>

      <section
        id="community-local"
        class="community-page__section"
      >
        <div class="panel community-page__panel">
          <div class="panel__hd panel__hd--split community-page__panel-hd">
            <h2 class="panel__title">
              <span
                class="panel__title-ico"
                aria-hidden="true"
              >◎</span>本部署语料
            </h2>
            <div class="row-actions community-page__hd-actions">
              <RouterLink
                class="btn btn--ghost btn--sm"
                to="/corpus-config"
              >语料设置</RouterLink>
            </div>
          </div>
          <div
            v-if="corpusStatus"
            class="panel__bd community-page__local-bd"
          >
            <div class="community-page__corpus-board">
              <div class="community-page__corpus-summary">
                <div class="community-page__corpus-summary-main">
                  <span
                    class="badge community-page__status-badge"
                    :class="corpusStatus.composite_active ? 'badge--ok' : ''"
                  >{{ corpusStatus.composite_active ? "复合已激活" : "复合未激活" }}</span>
                  <span
                    v-if="corpusSummaryFlow"
                    class="community-page__corpus-summary-flow"
                  >{{ corpusSummaryFlow }}</span>
                </div>
                <div class="community-page__corpus-summary-meta">
                  <span>{{ mergeStrategyLabel(corpusStatus.merge_strategy) }}</span>
                  <span class="community-page__corpus-summary-sep">·</span>
                  <span>远端失败 {{ remoteFailureLabel(corpusStatus.on_remote_failure) }}</span>
                  <span class="community-page__corpus-summary-sep">·</span>
                  <span>快照 {{ corpusSnapshotText }}</span>
                </div>
              </div>

              <div class="table-wrap community-page__matrix-wrap">
                <table class="tbl community-page__source-matrix">
                  <thead>
                    <tr>
                      <th scope="col">能力</th>
                      <th
                        v-for="key in visibleSourceKeys"
                        :key="key"
                        scope="col"
                        class="community-page__matrix-src-th"
                      >
                        <span
                          class="community-page__matrix-src"
                          :class="corpusStatus.sources?.[key]?.enabled ? 'is-on' : 'is-off'"
                        >{{ sourceLabel(key) }}</span>
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr
                      v-for="row in sourceMatrixRows"
                      :key="row.key"
                    >
                      <th scope="row">{{ row.label }}</th>
                      <td
                        v-for="key in visibleSourceKeys"
                        :key="`${row.key}-${key}`"
                      >
                        <span
                          class="community-page__matrix-cell"
                          :class="`community-page__matrix-cell--${matrixCellState(key, corpusStatus.sources?.[key], row.key)}`"
                        >{{ matrixCellText(matrixCellState(key, corpusStatus.sources?.[key], row.key)) }}</span>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>

              <ul
                v-if="sourceApiEntries.length"
                class="community-page__api-list"
              >
                <li
                  v-for="entry in sourceApiEntries"
                  :key="entry.key"
                  class="community-page__api-list-item"
                >
                  <span class="community-page__api-list-k">{{ sourceLabel(entry.key) }}</span>
                  <code class="community-page__api-list-v">{{ entry.url }}</code>
                </li>
              </ul>

              <div class="community-page__corpus-meta-bar">
                <span
                  class="community-page__corpus-meta-item"
                  :title="corpusStatus.deployment?.deployment_id || ''"
                >
                  <span class="community-page__corpus-meta-k">部署</span>
                  <span class="community-page__corpus-meta-v community-page__mono">{{ deploymentIdShort }}</span>
                </span>
                <span class="community-page__corpus-meta-item">
                  <span class="community-page__corpus-meta-k">统计上报</span>
                  <span
                    class="community-page__corpus-meta-v"
                    :class="corpusStatus.deployment?.community_stats_enabled ? 'is-ok' : 'is-off'"
                  >{{ corpusStatus.deployment?.community_stats_enabled ? "已启用" : "未启用" }}</span>
                </span>
                <span
                  v-if="corpusStatus.deployment?.heartbeat_endpoint"
                  class="community-page__corpus-meta-item community-page__corpus-meta-item--grow"
                >
                  <span class="community-page__corpus-meta-k">心跳</span>
                  <span class="community-page__corpus-meta-v community-page__mono">{{ corpusStatus.deployment.heartbeat_endpoint }}</span>
                </span>
              </div>
            </div>          </div>
          <div
            v-else
            class="panel__bd muted community-page__empty"
          >
            无法读取本部署语料状态。
          </div>
        </div>
      </section>
    </template>
  </div>
</template>

// react/src/pages/CommunityPage.tsx
import { useCallback, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import {
  fetchCommunityStats,
  fetchCorpusStatus,
  fetchFederationOnboarding,
  probeCommunityConnectivity,
} from "@/api/fullConsole";
import type {
  CommunityConnectivityCheckData,
  CommunityVersionCountData,
  CorpusSourceStatusData,
} from "@pallas-vue/api/pallasTypes";
import { PALLAS_COMMUNITY_HUB } from "@pallas-vue/utils/pallasExternalLinks";
import CorpusWordCloud from "@/components/CorpusWordCloud";
import PageHeader from "@/components/PageHeader";
import RefreshIconButton from "@/components/RefreshIconButton";

const allSourceKeys = ["local", "fed", "community"] as const;
type SourceKey = (typeof allSourceKeys)[number];

function formatUnixRelative(unix: number | null | undefined): string {
  if (unix == null || !Number.isFinite(unix) || unix <= 0) return "尚无成功上报记录";
  const sec = Math.max(0, Math.floor(Date.now() / 1000) - Math.floor(unix));
  if (sec < 60) return `${sec} 秒前`;
  if (sec < 3600) return `${Math.floor(sec / 60)} 分钟前`;
  if (sec < 86400) return `${Math.floor(sec / 3600)} 小时前`;
  return `${Math.floor(sec / 86400)} 天前`;
}

function shortProbeHost(url: string): string {
  try {
    const u = new URL(url);
    return `${u.host}${u.pathname}`;
  } catch {
    return url;
  }
}

function formatCommunityStatNum(n: number | undefined | null): string {
  if (n == null || !Number.isFinite(n)) return "—";
  return Math.floor(n).toLocaleString();
}

function formatUnixSec(ts: number | null | undefined): string {
  if (ts == null || !Number.isFinite(ts) || ts <= 0) return "—";
  try {
    return new Date(ts * 1000).toLocaleString();
  } catch {
    return "—";
  }
}

function sourceLabel(key: SourceKey): string {
  if (key === "local") return "本机";
  if (key === "fed") return "协同接话库";
  return "共享池";
}

function mergeStrategyLabel(raw: string | undefined): string {
  const s = (raw || "").trim();
  if (!s) return "—";
  const map: Record<string, string> = {
    local_first: "本地优先",
    merge_counts: "合并使用次数",
  };
  return map[s] || s;
}

function remoteFailureLabel(raw: string | undefined): string {
  const s = (raw || "").trim();
  if (!s) return "—";
  const map: Record<string, string> = { local_only: "仅用本机语料" };
  return map[s] || s;
}

const sourceMatrixRows = [
  { key: "enabled", label: "启用" },
  { key: "enrolled", label: "已接入" },
  { key: "readable", label: "可读" },
  { key: "writable", label: "可写" },
  { key: "contribute", label: "可贡献" },
] as const;

type MatrixRowKey = (typeof sourceMatrixRows)[number]["key"];
const localMatrixNaRows = new Set<MatrixRowKey>(["enrolled", "contribute"]);

function matrixCellState(
  sourceKey: SourceKey,
  source: CorpusSourceStatusData | undefined,
  rowKey: MatrixRowKey,
): "on" | "off" | "na" {
  if (sourceKey === "local" && localMatrixNaRows.has(rowKey)) return "na";
  if (!source) return "na";
  if (rowKey === "enabled") return source.enabled ? "on" : "off";
  if (!source.enabled) return "na";
  return source[rowKey] ? "on" : "off";
}

function matrixCellText(state: "on" | "off" | "na"): string {
  if (state === "on") return "是";
  if (state === "off") return "否";
  return "—";
}

export default function CommunityPage() {
  const [refreshBusy, setRefreshBusy] = useState(false);
  const [hotReloadToken, setHotReloadToken] = useState(0);
  const [err, setErr] = useState("");
  const [connectivityBusy, setConnectivityBusy] = useState(false);
  const [connectivityResult, setConnectivityResult] = useState<CommunityConnectivityCheckData | null>(null);

  const statsQ = useQuery({ queryKey: ["community-stats"], queryFn: () => fetchCommunityStats({}) });
  const corpusStatusQ = useQuery({ queryKey: ["corpus-status"], queryFn: fetchCorpusStatus });
  const federationQ = useQuery({ queryKey: ["federation-onboarding"], queryFn: fetchFederationOnboarding });

  const communityStats = statsQ.data ?? null;
  const corpusStatus = corpusStatusQ.data ?? null;
  const federationOnboarding = federationQ.data ?? null;
  const pageReady = statsQ.isFetched || corpusStatusQ.isFetched;

  const onlineHint = useMemo(() => {
    const sec = communityStats?.online_ttl_sec;
    if (sec == null || !Number.isFinite(sec) || sec < 60) return "近期有上报";
    return `近 ${Math.max(1, Math.round(sec / 60))} 分钟内有上报`;
  }, [communityStats]);

  const deploymentsOnlineHint = `${onlineHint}的自托管安装套数`;
  const botsOnlineHint = useMemo(() => {
    const sum = communityStats?.bots_online_sum;
    const onlineDep = communityStats?.deployments_online;
    if (sum != null && onlineDep != null && onlineDep > 0) {
      const avg = sum / onlineDep;
      return `各安装上报的在线牛牛合计，平均每套约 ${avg >= 10 ? Math.round(avg) : avg.toFixed(1)} 只`;
    }
    return "各安装向社区中心上报的在线牛牛总数";
  }, [communityStats]);

  const activeRecentHint = useMemo(() => {
    const parts: string[] = [];
    if (communityStats?.deployments_total != null) parts.push(`历史累计 ${formatCommunityStatNum(communityStats.deployments_total)} 套`);
    if (communityStats?.catalog_bots_online_sum != null) parts.push(`当前在线名册 ${formatCommunityStatNum(communityStats.catalog_bots_online_sum)} 只牛牛`);
    return parts.length ? parts.join(" · ") : "近 24 小时内有统计上报的安装数";
  }, [communityStats]);

  const corpusPoolValue = useMemo(() => {
    const ctx = formatCommunityStatNum(communityStats?.corpus?.contexts_total);
    const ans = formatCommunityStatNum(communityStats?.corpus?.answers_total);
    if (ctx === "—" && ans === "—") return "—";
    return `${ctx} 词条 · ${ans} 回复`;
  }, [communityStats]);

  const corpusPoolHint = useMemo(() => {
    const hits = communityStats?.corpus?.answer_hits_sum;
    if (hits != null && Number.isFinite(hits)) return `回复累计被引用 ${formatCommunityStatNum(hits)} 次`;
    return "共享池中的触发词与回复条目";
  }, [communityStats]);

  const onlineVersions = useMemo((): CommunityVersionCountData[] => {
    const rows = communityStats?.online_versions;
    if (!Array.isArray(rows)) return [];
    return [...rows].sort((a, b) => b.count - a.count);
  }, [communityStats]);

  const statsAsOfText = (communityStats?.as_of || "").trim() ? `快照 ${communityStats?.as_of}` : "";
  const statsUrl = (communityStats?.stats_url || "").trim();
  const communityHubUrl = (federationOnboarding?.stats_primary_url || PALLAS_COMMUNITY_HUB).trim() || PALLAS_COMMUNITY_HUB;

  const fedSourceVisible = (fed: CorpusSourceStatusData | undefined) => !!(fed?.configured || fed?.enabled);
  const visibleSourceKeys = useMemo((): SourceKey[] => {
    const keys: SourceKey[] = ["local"];
    if (fedSourceVisible(corpusStatus?.sources?.fed)) keys.push("fed");
    keys.push("community");
    return keys;
  }, [corpusStatus]);

  const mergeOrderSteps = useMemo(() => {
    const order = corpusStatus?.merge_order;
    if (!Array.isArray(order) || !order.length) return [] as Array<"local" | "fed" | "community">;
    const allowed = new Set(["local", "fed", "community"]);
    const visible = new Set(visibleSourceKeys);
    return order.filter((s): s is "local" | "fed" | "community" => allowed.has(s) && visible.has(s as SourceKey));
  }, [corpusStatus, visibleSourceKeys]);

  const corpusSummaryFlow = mergeOrderSteps.map((k) => sourceLabel(k)).join(" → ");

  const corpusMultiSourceBadge = useMemo(() => {
    if (!corpusStatus) return { label: "多源接话未启用", ok: false };
    const community = corpusStatus.sources?.community;
    if (corpusStatus.composite_active) {
      if (community?.wanted && !community?.readable) return { label: "多源接话已启用（待接入）", ok: true };
      return { label: "多源接话已启用", ok: true };
    }
    if (community?.wanted) return { label: "多源接话已开启（待就绪）", ok: false };
    const mode = String(corpusStatus.remote_find_mode || "").trim();
    if (mode === "prefetch" || mode === "sync") return { label: "本机未命中时查社区已开", ok: true };
    return { label: "多源接话未启用", ok: false };
  }, [corpusStatus]);

  const controlPlane = corpusStatus?.control_plane;
  const federationPoolStats = federationOnboarding?.pool_stats ?? communityStats?.federation ?? null;

  const refresh = useCallback(async () => {
    setRefreshBusy(true);
    try {
      await Promise.all([statsQ.refetch(), corpusStatusQ.refetch(), federationQ.refetch()]);
      setHotReloadToken((t) => t + 1);
    } finally {
      setRefreshBusy(false);
    }
  }, [corpusStatusQ, federationQ, statsQ]);

  async function runConnectivityCheck() {
    if (connectivityBusy) return;
    setConnectivityBusy(true);
    try {
      setConnectivityResult(await probeCommunityConnectivity());
    } catch (e) {
      setConnectivityResult(null);
      setErr(e instanceof Error ? e.message : String(e));
    } finally {
      setConnectivityBusy(false);
    }
  }

  if (!pageReady) {
    return (
      <div className="community-page console-hub-page">
        <p className="muted">加载社区统计…</p>
      </div>
    );
  }

  return (
    <div className="community-page console-hub-page">
      <PageHeader
        title="统计与语料"
        description="社区中心公开统计与本部署语料、多机协同状态；数据只读。"
        actions={<RefreshIconButton embedded className="hub-refresh-wide-only" busy={refreshBusy} label="刷新" onClick={() => void refresh()} />}
      />
      <p className="community-page__masthead-links muted">
        <a className="community-page__inline-link" href={communityHubUrl} target="_blank" rel="noopener noreferrer">
          社区主站
        </a>
        {" · "}
        <Link to="/plugins/pb_stats">在线统计</Link>
        {" · "}
        <Link to="/plugins/pb_core">共享接话库</Link>
      </p>

      {err ? <p className="alert alert--err community-page__alert">{err}</p> : null}

      {!communityStats ? (
        <p className="alert alert--warn community-page__alert">
          暂时无法从社区中心获取数据，下列数字以 — 占位。请确认本机已开启「上报在线统计」，且网络能访问社区中心。
          <button type="button" className="btn community-page__alert-probe-btn" disabled={connectivityBusy} onClick={() => void runConnectivityCheck()}>
            {connectivityBusy ? "检测中…" : "检测连通"}
          </button>
        </p>
      ) : null}

      <section id="community-deploy" className="community-page__section">
        <div className="panel community-page__panel">
          <div className="panel__hd panel__hd--split community-page__panel-hd community-page__deploy-panel-hd">
            <h2 className="panel__title community-page__section-title">
              全网部署
              <RefreshIconButton embedded className="hub-refresh-narrow-only" showLabel={false} busy={refreshBusy} label="刷新" onClick={() => void refresh()} />
            </h2>
            <div className="row-actions community-page__hd-actions community-page__deploy-hd-actions">
              <button type="button" className="btn community-page__deploy-probe-btn" disabled={connectivityBusy} onClick={() => void runConnectivityCheck()}>
                {connectivityBusy ? "检测中…" : "检测连通"}
              </button>
              <Link to="/plugins/pb_stats" className="btn community-page__deploy-settings-btn">
                在线统计设置
              </Link>
            </div>
          </div>
          <div className="panel__bd">
            {connectivityResult ? (
              <div className={`community-page__probe-card ${connectivityResult.summary.any_ok ? "is-ok" : "is-bad"}`}>
                <p className="community-page__probe-hint">{connectivityResult.summary.hint}</p>
                <ul className="community-page__probe-list">
                  {connectivityResult.probes.map((row) => (
                    <li key={row.url} className="community-page__probe-row">
                      <span className={`badge ${row.ok ? "badge--ok" : "badge--warn"}`}>{row.ok ? "可达" : "失败"}</span>
                      <code className="community-page__mono community-page__probe-url">{shortProbeHost(row.url)}</code>
                      <span className="muted community-page__probe-meta">
                        {row.ok ? (row.latency_ms != null ? `${row.latency_ms} ms` : "—") : row.error || (row.http_status != null ? `HTTP ${row.http_status}` : "失败")}
                      </span>
                    </li>
                  ))}
                </ul>
                <dl className="home-dl community-page__detail-dl community-page__probe-reporting">
                  <dt>上报开关</dt>
                  <dd>{connectivityResult.reporting.enabled ? "已开启" : "已关闭"}</dd>
                  <dt>配置 endpoint</dt>
                  <dd className="community-page__mono">{connectivityResult.reporting.endpoint || "—"}</dd>
                  <dt>最近成功入口</dt>
                  <dd className="community-page__mono">{connectivityResult.reporting.active_heartbeat_endpoint || "—"}</dd>
                  <dt>上次成功上报</dt>
                  <dd>{formatUnixRelative(connectivityResult.reporting.last_heartbeat_ok_unix)}</dd>
                </dl>
              </div>
            ) : null}

            <div className="community-page__kpi-bar home-kpi-bar community-page__deploy-grid">
              <MetricTile label="活跃安装" value={formatCommunityStatNum(communityStats?.deployments_online)} hint={deploymentsOnlineHint} />
              <MetricTile label="在线牛牛" value={formatCommunityStatNum(communityStats?.bots_online_sum)} hint={botsOnlineHint} />
              <MetricTile
                label="分片安装"
                value={`${formatCommunityStatNum(communityStats?.deployments_online_sharded)} / ${formatCommunityStatNum(communityStats?.shard_workers_online_sum)}`}
                hint="采用分片架构的安装数 / 在线工作进程数"
              />
              <MetricTile label="近 24 小时" value={formatCommunityStatNum(communityStats?.active_recent_24h)} hint={activeRecentHint} />
            </div>

            <dl className="home-dl community-page__detail-dl community-page__meta-dl">
              <dt>历史安装</dt>
              <dd>{formatCommunityStatNum(communityStats?.deployments_total)} 套</dd>
              <dt>在线名册</dt>
              <dd>{formatCommunityStatNum(communityStats?.catalog_bots_online_sum)} 只牛牛</dd>
              <dt>共享语料</dt>
              <dd>
                {communityStats != null ? (
                  <span className={`badge ${communityStats.corpus_enabled ? "badge--ok" : ""}`}>
                    {communityStats.corpus_enabled ? "已接入" : "未接入"}
                  </span>
                ) : (
                  "—"
                )}
              </dd>
              {statsAsOfText || statsUrl ? (
                <>
                  <dt>数据来源</dt>
                  <dd className="community-page__meta-stack">
                    {statsAsOfText ? <span className="community-page__meta-line">{statsAsOfText}</span> : null}
                    {statsUrl ? (
                      <a className="community-page__ext-link community-page__meta-line community-page__mono" href={statsUrl} target="_blank" rel="noopener noreferrer">
                        {statsUrl}
                      </a>
                    ) : null}
                  </dd>
                </>
              ) : null}
            </dl>

            {onlineVersions.length ? (
              <div className="community-page__versions">
                <h3 className="community-page__subhd">在线版本分布</h3>
                <ul className="community-page__version-list">
                  {onlineVersions.map((row) => (
                    <li key={row.version} className="community-page__version-row">
                      <span className="community-page__version-name community-page__mono">{row.version || "—"}</span>
                      <span className="community-page__version-count">{formatCommunityStatNum(row.count)} 套</span>
                    </li>
                  ))}
                </ul>
              </div>
            ) : null}
          </div>
        </div>
      </section>

      <section id="community-federation" className="community-page__section">
        <div className="panel community-page__panel community-page__federation-panel">
          <div className="panel__hd panel__hd--split community-page__panel-hd">
            <h2 className="panel__title community-page__section-title">{federationOnboarding?.title || "多机协同"}</h2>
            <div className="row-actions community-page__hd-actions">
              <Link to="/plugins/pb_core" className="btn">
                多机协同
              </Link>
            </div>
          </div>
          <div className="panel__bd community-page__federation-bd">
            {federationOnboarding?.summary ? <p className="community-page__federation-summary">{federationOnboarding.summary}</p> : null}
            <div className="community-page__kpi-bar home-kpi-bar community-page__federation-pool-grid">
              <MetricTile label="累计入池" value={formatCommunityStatNum(federationPoolStats?.members_total)} hint="曾成功从社区中心领取协同配置的安装套数" />
              <MetricTile label="在线入池" value={formatCommunityStatNum(federationPoolStats?.members_online)} hint="已入池且近期有在线统计上报的安装套数" />
              <MetricTile label="去重活跃" value={formatCommunityStatNum(federationPoolStats?.coord_active_deployments)} hint="去重服务上仍有活跃标记的安装数" />
            </div>
          </div>
        </div>
      </section>

      <section id="community-corpus" className="community-page__section">
        <div className="panel community-page__panel">
          <div className="panel__hd panel__hd--split community-page__panel-hd">
            <h2 className="panel__title community-page__section-title">共享语料</h2>
          </div>
          <div className="panel__bd">
            <div className="community-page__kpi-bar home-kpi-bar community-page__corpus-grid">
              <MetricTile label="词条规模" value={corpusPoolValue} hint={corpusPoolHint} />
              <MetricTile label="在线接入" value={formatCommunityStatNum(communityStats?.corpus?.enrollments_online)} hint={`${onlineHint}且已接入共享语料`} />
              <MetricTile label="累计接入" value={formatCommunityStatNum(communityStats?.corpus?.enrollments_total)} hint="曾经接入过社区共享语料的安装总数" />
              <MetricTile label="允许上传" value={formatCommunityStatNum(communityStats?.corpus?.contribute_enabled_total)} hint="已接入且允许把本机新回复同步到共享池的安装数" />
            </div>
          </div>
        </div>
      </section>

      <section id="community-hot" className="community-page__section">
        <div className="panel community-page__panel">
          <div className="panel__hd panel__hd--split community-page__panel-hd">
            <h2 className="panel__title community-page__section-title">共享语料热词</h2>
          </div>
          <div className="panel__bd">
            <p className="muted community-page__hot-lead">默认展示近24h各部署热词叠加（机群榜）；「高频池」为共享语料累计。</p>
            <CorpusWordCloud source="community" reloadToken={hotReloadToken} />
          </div>
        </div>
      </section>

      <section id="community-local-hot" className="community-page__section">
        <div className="panel community-page__panel">
          <div className="panel__hd panel__hd--split community-page__panel-hd">
            <h2 className="panel__title community-page__section-title">本机语料热词</h2>
          </div>
          <div className="panel__bd">
            <p className="muted community-page__hot-lead">本部署全部群的学习语料累计热度，与共享池独立统计。</p>
            <CorpusWordCloud source="local" reloadToken={hotReloadToken} />
          </div>
        </div>
      </section>

      <section id="community-local" className="community-page__section">
        <div className="panel community-page__panel">
          <div className="panel__hd panel__hd--split community-page__panel-hd">
            <h2 className="panel__title community-page__section-title">本部署语料</h2>
            <div className="row-actions community-page__hd-actions">
              <Link to="/plugins/pb_core" className="btn">
                语料设置
              </Link>
            </div>
          </div>
          {corpusStatus ? (
            <div className="panel__bd community-page__local-bd">
              <div className="community-page__corpus-board">
                <div className="community-page__corpus-summary">
                  <div className="community-page__corpus-summary-main">
                    <span className={`badge community-page__status-badge ${corpusMultiSourceBadge.ok ? "badge--ok" : ""}`}>
                      {corpusMultiSourceBadge.label}
                    </span>
                    {corpusSummaryFlow ? <span className="community-page__corpus-summary-flow">查找顺序：{corpusSummaryFlow}</span> : null}
                  </div>
                  <div className="community-page__corpus-summary-meta">
                    <span>{mergeStrategyLabel(corpusStatus.merge_strategy)}</span>
                    <span className="community-page__corpus-summary-sep">·</span>
                    <span>远端失败时 {remoteFailureLabel(corpusStatus.on_remote_failure)}</span>
                    <span className="community-page__corpus-summary-sep">·</span>
                    <span>快照 {formatUnixSec(corpusStatus.as_of)}</span>
                  </div>
                </div>

                <div className="table-wrap community-page__matrix-wrap">
                  <table className="tbl community-page__source-matrix">
                    <thead>
                      <tr>
                        <th scope="col">能力</th>
                        {visibleSourceKeys.map((key) => (
                          <th key={key} scope="col" className="community-page__matrix-src-th">
                            <span className={`community-page__matrix-src ${corpusStatus.sources?.[key]?.enabled ? "is-on" : "is-off"}`}>
                              {sourceLabel(key)}
                            </span>
                          </th>
                        ))}
                      </tr>
                    </thead>
                    <tbody>
                      {sourceMatrixRows.map((row) => (
                        <tr key={row.key}>
                          <th scope="row">{row.label}</th>
                          {visibleSourceKeys.map((key) => {
                            const state = matrixCellState(key, corpusStatus.sources?.[key], row.key);
                            return (
                              <td key={`${row.key}-${key}`}>
                                <span className={`community-page__matrix-cell community-page__matrix-cell--${state}`}>
                                  {matrixCellText(state)}
                                </span>
                              </td>
                            );
                          })}
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>

                {controlPlane ? (
                  <div className="community-page__corpus-meta-bar">
                    <span className="community-page__corpus-meta-item">
                      <span className="community-page__corpus-meta-k">多机协同</span>
                      <span className={`community-page__corpus-meta-v ${controlPlane.enabled ? "is-ok" : "is-off"}`}>
                        {controlPlane.enabled ? "已开启" : "已关闭"}
                      </span>
                    </span>
                    <span className="community-page__corpus-meta-item">
                      <span className="community-page__corpus-meta-k">在线统计</span>
                      <span className={`community-page__corpus-meta-v ${corpusStatus.deployment?.community_stats_enabled ? "is-ok" : "is-off"}`}>
                        {corpusStatus.deployment?.community_stats_enabled ? "已开启" : "已关闭"}
                      </span>
                    </span>
                  </div>
                ) : null}
              </div>
            </div>
          ) : (
            <div className="panel__bd muted community-page__empty">无法读取本部署语料状态。</div>
          )}
        </div>
      </section>
    </div>
  );
}

function MetricTile({ label, value, hint }: { label: string; value: string; hint: string }) {
  return (
    <div className="metric-tile">
      <div className="metric-tile__head">
        <span className="metric-tile__label">{label}</span>
      </div>
      <div className="metric-tile__value-slot">
        <span className="metric-tile__value metric-tile__value--inline">{value}</span>
        <span className="community-page__kpi-hint muted" title={hint}>
          {hint}
        </span>
      </div>
    </div>
  );
}
