// src/pages/UpdatePage.vue
<script setup lang="ts">
import { computed, nextTick, onMounted, ref, watch } from "vue";
import { RouterLink, useRoute } from "vue-router";
import {
  fetchBotConfigMigrationCheck,
  fetchBotUpdateCheck,
  fetchCommonConfig,
  fetchUpdateCheck,
  postBotConfigMigrationApply,
  postBotUpdateApply,
  postUpdateApply,
  putCommonConfig,
} from "@/api/consoleApi";
import type { BotConfigMigrationCheckData, BotUpdateCheckData, UpdateCheckData } from "@/api/pallasTypes";
import ConsolePageSkeleton from "@/components/ConsolePageSkeleton.vue";
import PanelSidebarAdd from "@/components/PanelSidebarAdd.vue";
import RefreshIconButton from "@/components/RefreshIconButton.vue";
import { usePanelNavIcon } from "@/composables/usePanelNavIcon";
import { useSaveHotkey } from "@/composables/useSaveHotkey";
import { axiosErrorDetail } from "@/api/http";
import { releaseNotesToSafeHtml } from "@/utils/releaseNotesHtml";
import { toastApiError, toastSaveSuccess } from "@/utils/consoleToastFeedback";

const WEBUI_RELEASES_PAGE = "https://github.com/PallasBot/Pallas-Bot-WebUI/releases";
const BOT_RELEASES_PAGE = "https://github.com/PallasBot/Pallas-Bot/releases";
const BOT_REPO_MAIN = "https://github.com/PallasBot/Pallas-Bot/blob/main";
const BOT_DOC = {
  siteCustomization: `${BOT_REPO_MAIN}/docs/architecture/site-customization-and-updates.md`,
  localReadme: `${BOT_REPO_MAIN}/local/README.md`,
  deployment: `${BOT_REPO_MAIN}/docs/Deployment.md`,
  dockerDeployment: `${BOT_REPO_MAIN}/docs/DockerDeployment.md`,
  faqUpdates: `${BOT_REPO_MAIN}/docs/FAQ.md#更新与版本`,
  settingsStorage: `${BOT_REPO_MAIN}/docs/architecture/settings-storage.md`,
} as const;

/** 与通用配置 `?section=pallas_protocol` 一致，经通用配置落盘 */
const PALLAS_PROTOCOL_SECTION_ID = "pallas_protocol";
const GITHUB_TOKEN_FIELD = "pallas_protocol_github_token";

const panelNavIcon = usePanelNavIcon();
const route = useRoute();
const err = ref("");
const pageReady = ref(false);
const web = ref<UpdateCheckData | null>(null);
const bot = ref<BotUpdateCheckData | null>(null);
const configMigration = ref<BotConfigMigrationCheckData | null>(null);

const webReleaseNotesHtml = computed(() => releaseNotesToSafeHtml(web.value?.release_notes));
const botReleaseNotesHtml = computed(() => releaseNotesToSafeHtml(bot.value?.release_notes));

const webApplyDisabled = computed(
  () => busy.value || !web.value?.has_update || !web.value?.latest_tag,
);

const webCallout = computed((): { kind: "info"; text: string } | null => {
  if (web.value?.has_update) {
    return { kind: "info", text: "更新完成后页面会自动刷新。" };
  }
  return null;
});

const botDeployLabel = computed(() => {
  const mode = bot.value?.deployment_mode;
  if (mode === "docker") return "Docker";
  if (mode === "release_tag") return "正式版";
  if (mode === "release_tag_dirty") return "正式版 · 有本地改动";
  if (mode === "dev_clone") return "开发克隆";
  return "—";
});

const botCallout = computed((): { kind: "warn" | "info"; text: string } | null => {
  const b = bot.value;
  if (!b) return null;
  if (b.deployment_mode === "docker") {
    return {
      kind: "warn",
      text: "控制台不能 git 拉代码；请按下方步骤拉新镜像并重启容器。",
    };
  }
  if (b.deployment_mode === "release_tag_dirty") {
    return {
      kind: "warn",
      text: `更新前会自动 stash ${b.dirty_file_count ?? 0} 项本地改动；冲突时需 git stash pop。建议插件放 local/plugins/。`,
    };
  }
  if (b.deployment_mode === "dev_clone") {
    return { kind: "info", text: "更新时执行 git pull --ff-only --autostash。" };
  }
  return null;
});

const botMetaParts = computed(() => {
  const b = bot.value;
  if (!b) return [];
  const parts: string[] = [botDeployLabel.value];
  if (b.git_available && b.current_branch) parts.push(`分支 ${b.current_branch}`);
  if (b.dirty && (b.dirty_file_count ?? 0) > 0) parts.push(`改动 ${b.dirty_file_count} 项`);
  return parts;
});

const botDocLinks = computed(() => {
  const isDocker = bot.value?.deployment_mode === "docker";
  const links: { href: string; label: string }[] = [
    { href: BOT_DOC.siteCustomization, label: "站点定制与更新" },
    { href: BOT_DOC.localReadme, label: "local 目录说明" },
  ];
  if (isDocker) {
    links.unshift({ href: BOT_DOC.dockerDeployment, label: "Docker 部署" });
  } else {
    links.push({ href: BOT_DOC.deployment, label: "标准部署" });
  }
  links.push({ href: BOT_DOC.faqUpdates, label: "FAQ · 更新与版本" });
  if (configMigration.value?.show) {
    links.push({ href: BOT_DOC.settingsStorage, label: "配置存储" });
  }
  return links;
});

const botApplyDisabled = computed(
  () =>
    busy.value
    || !bot.value?.has_update
    || !bot.value?.latest_tag
    || bot.value?.deployment_mode === "docker",
);

const busy = ref(false);
const msg = ref("");
const refreshWebBusy = ref(false);
const refreshBotBusy = ref(false);
const configMigrationBusy = ref(false);
const configMigrationMsg = ref("");
const configMigrationErr = ref("");
const configMigrationLegacyFiles = computed(() => {
  const files = configMigration.value?.legacy_env_files ?? [];
  return files.length ? files.join("、") : ".env";
});

async function loadConfigMigration() {
  configMigrationErr.value = "";
  try {
    configMigration.value = await fetchBotConfigMigrationCheck();
  } catch (e) {
    configMigrationErr.value = e instanceof Error ? e.message : String(e);
    configMigration.value = null;
  }
}

const ghTokenInput = ref("");
const ghTokenHadValue = ref(false);
const ghTokenBusy = ref(false);
const ghTokenErr = ref("");
const ghTokenOk = ref("");

async function loadGithubTokenHint() {
  ghTokenErr.value = "";
  ghTokenOk.value = "";
  try {
    const data = await fetchCommonConfig(PALLAS_PROTOCOL_SECTION_ID);
    const f = data.fields.find((x) => x.name === GITHUB_TOKEN_FIELD);
    const cur = f?.current;
    const s = cur === null || cur === undefined ? "" : String(cur).trim();
    ghTokenHadValue.value = s.length > 0;
    ghTokenInput.value = "";
  } catch (e) {
    ghTokenErr.value = e instanceof Error ? e.message : String(e);
    ghTokenHadValue.value = false;
  }
}

async function saveGithubToken() {
  const next = ghTokenInput.value.trim();
  if (!next) {
    ghTokenErr.value = "请输入新令牌，或使用下方「清除」移除已保存的令牌。";
    return;
  }
  ghTokenBusy.value = true;
  ghTokenErr.value = "";
  ghTokenOk.value = "";
  try {
    await putCommonConfig(PALLAS_PROTOCOL_SECTION_ID, { [GITHUB_TOKEN_FIELD]: next });
    ghTokenHadValue.value = true;
    ghTokenInput.value = "";
    ghTokenOk.value = "配置已保存；若未立即生效可重启 Bot。";
    toastSaveSuccess("GitHub 令牌已保存");
  } catch (e) {
    ghTokenErr.value = e instanceof Error ? e.message : String(e);
    toastApiError(e, "保存失败");
  } finally {
    ghTokenBusy.value = false;
  }
}

useSaveHotkey(() => !ghTokenBusy.value && ghTokenInput.value.trim().length > 0, () => saveGithubToken());

async function clearGithubToken() {
  if (!confirm("确定清除已保存的 GitHub 令牌？")) return;
  ghTokenBusy.value = true;
  ghTokenErr.value = "";
  ghTokenOk.value = "";
  try {
    await putCommonConfig(PALLAS_PROTOCOL_SECTION_ID, { [GITHUB_TOKEN_FIELD]: "" });
    ghTokenHadValue.value = false;
    ghTokenInput.value = "";
    ghTokenOk.value = "已清除；重启 Bot 后生效。";
    toastSaveSuccess("GitHub 令牌已清除");
  } catch (e) {
    ghTokenErr.value = e instanceof Error ? e.message : String(e);
    toastApiError(e, "清除失败");
  } finally {
    ghTokenBusy.value = false;
  }
}

function scrollUpdateHashIntoView() {
  const raw = (route.hash || "").replace(/^#/, "").trim();
  if (!raw) return;
  nextTick(() => {
    requestAnimationFrame(() => {
      document.getElementById(raw)?.scrollIntoView({ behavior: "smooth", block: "start" });
    });
  });
}

async function load() {
  err.value = "";
  msg.value = "";
  try {
    await Promise.all([fetchUpdateCheck().then((r) => (web.value = r)), fetchBotUpdateCheck().then((r) => (bot.value = r))]);
  } catch (e) {
    err.value = e instanceof Error ? e.message : String(e);
  } finally {
    pageReady.value = true;
  }
  scrollUpdateHashIntoView();
  void loadGithubTokenHint();
  void loadConfigMigration();
}

/** 与原先「重新检查」一致：仅重新拉取 WebUI 远端比对结果 */
async function refreshWeb() {
  err.value = "";
  refreshWebBusy.value = true;
  try {
    web.value = await fetchUpdateCheck();
  } catch (e) {
    err.value = e instanceof Error ? e.message : String(e);
  } finally {
    refreshWebBusy.value = false;
  }
}

/** 与原先「重新检查」一致：仅重新拉取 Bot 远端比对结果 */
async function refreshBot() {
  err.value = "";
  refreshBotBusy.value = true;
  try {
    bot.value = await fetchBotUpdateCheck();
    await loadConfigMigration();
  } catch (e) {
    err.value = e instanceof Error ? e.message : String(e);
  } finally {
    refreshBotBusy.value = false;
  }
}

async function applyWeb() {
  if (!web.value?.latest_tag) return;
  if (!confirm(`将 WebUI 更新到 ${web.value.latest_tag}？`)) return;
  busy.value = true;
  try {
    const r = await postUpdateApply();
    msg.value = r.message ? `${r.message} · 正在刷新页面以载入新版本…` : "WebUI 已更新，正在刷新页面…";
    await nextTick();
    window.location.reload();
  } catch (e) {
    err.value = axiosErrorDetail(e);
  } finally {
    busy.value = false;
  }
}

async function applyBot() {
  if (!bot.value?.latest_tag) return;
  if (!confirm(`将 Bot 更新到 ${bot.value.latest_tag}？`)) return;
  busy.value = true;
  try {
    const r = await postBotUpdateApply();
    msg.value = r.message || "已触发。";
    await load();
  } catch (e) {
    err.value = axiosErrorDetail(e);
  } finally {
    busy.value = false;
  }
}

async function applyConfigMigration(force: boolean) {
  const cm = configMigration.value;
  if (!cm?.show) return;
  const prompt = force
    ? "将覆盖已有的 config/pallas.toml 与 webui.json，是否继续？建议先备份。"
    : "把根目录 .env 迁移到 config/pallas.toml 与 data/pallas_config/webui.json？";
  if (!confirm(prompt)) return;
  configMigrationBusy.value = true;
  configMigrationErr.value = "";
  configMigrationMsg.value = "";
  try {
    const r = await postBotConfigMigrationApply(force);
    configMigrationMsg.value = r.message;
    configMigration.value = r.migration ?? (await fetchBotConfigMigrationCheck());
    toastSaveSuccess("配置已迁移");
  } catch (e) {
    configMigrationErr.value = axiosErrorDetail(e);
    toastApiError(e, "迁移失败");
  } finally {
    configMigrationBusy.value = false;
  }
}

watch(
  () => route.hash,
  () => {
    if (pageReady.value) scrollUpdateHashIntoView();
  },
);

onMounted(() => {
  void load();
});
</script>

<template>
  <div class="update-page">
    <div
      v-if="err"
      class="alert alert--err"
    >
      {{ err }}
    </div>
    <div
      v-if="msg"
      class="alert alert--ok"
    >
      {{ msg }}
    </div>

    <ConsolePageSkeleton
      v-if="!pageReady"
      :panels="2"
    />
    <template v-else>
      <div
        id="console-update-github"
        class="panel update-page__panel"
      >
        <div class="panel__hd panel__hd--split update-page__panel-hd-nowrap">
          <h2 class="panel__title">
            <span class="panel__title-ico" aria-hidden="true">{{ panelNavIcon }}</span><span class="update-page__title-keep">GitHub 令牌</span>
          </h2>
          <div class="row-actions">
            <PanelSidebarAdd main-path="/update" />
          </div>
        </div>
        <div class="panel__bd muted update-page__bd">
          <p>
            可选。用于 Release 检查与下载、协议端在线拉包等。也可在侧边栏
            <RouterLink :to="{ path: '/common-config', query: { section: PALLAS_PROTOCOL_SECTION_ID } }">通用配置 → 协议端</RouterLink>
            中填写，键名 <code>PALLAS_PROTOCOL_GITHUB_TOKEN</code>；下方保存与此处等效。
          </p>
          <p>
            当前：<strong class="update-page__strong">{{ ghTokenHadValue ? "已配置" : "未配置" }}</strong>
            <span v-if="ghTokenHadValue">（不显示内容；输入新值覆盖）</span>
          </p>
          <div class="update-page__gh-row">
            <input
              v-model="ghTokenInput"
              class="inp update-page__gh-inp"
              type="password"
              autocomplete="off"
              placeholder="粘贴 fine-grained 或 classic PAT"
              :disabled="ghTokenBusy"
            >
            <button
              type="button"
              class="btn btn--primary"
              :disabled="ghTokenBusy"
              @click="saveGithubToken"
            >
              {{ ghTokenBusy ? "保存中…" : "保存" }}
            </button>
            <button
              v-if="ghTokenHadValue"
              type="button"
              class="btn"
              :disabled="ghTokenBusy"
              @click="clearGithubToken"
            >
              清除
            </button>
          </div>
          <div
            v-if="ghTokenErr"
            class="alert alert--err update-page__gh-alert"
          >
            {{ ghTokenErr }}
          </div>
          <div
            v-if="ghTokenOk"
            class="alert alert--ok update-page__gh-alert"
          >
            {{ ghTokenOk }}
          </div>
          <p class="update-page__gh-more">
            更多协议相关项见
            <RouterLink
              class="update-page__link"
              to="/common-config"
            >通用配置</RouterLink>
            → 选择「协议端 / Pallas Protocol」。
          </p>
        </div>
      </div>

      <div
        id="console-update-webui"
        class="panel update-page__panel"
      >
        <div class="panel__hd panel__hd--split update-page__panel-hd-nowrap">
          <h2 class="panel__title">
            <span class="panel__title-ico" aria-hidden="true">{{ panelNavIcon }}</span>WebUI
            <RefreshIconButton
              :busy="refreshWebBusy"
              :disabled="busy"
              label="刷新 WebUI 更新检查"
              @click="refreshWeb"
            />
            <span
              v-if="web?.has_update"
              class="badge badge--warn update-page__status-pill"
            >有更新</span>
            <span
              v-else
              class="badge badge--ok update-page__status-pill"
            >已是最新</span>
          </h2>
          <div class="row-actions">
            <PanelSidebarAdd main-path="/update" />
          </div>
        </div>
        <div class="panel__bd update-page__bd update-page__bd--release">
          <div class="update-page__release-summary">
            <div class="update-page__release-stat">
              <span class="update-page__release-stat-label">当前</span>
              <span class="update-page__release-stat-value">{{ web?.current_tag || "—" }}</span>
            </div>
            <span
              class="update-page__release-stat-arrow muted"
              aria-hidden="true"
            >→</span>
            <div class="update-page__release-stat">
              <span class="update-page__release-stat-label">远端</span>
              <span class="update-page__release-stat-value">{{ web?.latest_tag ?? "—" }}</span>
            </div>
          </div>

          <div class="update-page__release-primary">
            <button
              type="button"
              class="btn btn--primary"
              :disabled="webApplyDisabled"
              @click="applyWeb"
            >
              应用 WebUI 更新
            </button>
            <a
              class="update-page__link update-page__release-ext-link"
              :href="(web?.release_url || '').trim() || WEBUI_RELEASES_PAGE"
              target="_blank"
              rel="noopener noreferrer"
            >GitHub Release</a>
          </div>

          <p
            v-if="web?.error"
            class="alert alert--err update-page__release-inline-alert"
          >
            {{ web.error }}
          </p>
          <div
            v-else-if="webCallout"
            class="update-page__release-callout update-page__release-callout--info"
          >
            {{ webCallout.text }}
          </div>

          <details
            v-if="(web?.release_notes || '').trim()"
            class="update-page__release-fold update-page__release-notes"
          >
            <summary class="update-page__release-fold-summary">
              {{ web?.latest_tag ? `「${web.latest_tag}」发行说明` : "发行说明" }}
            </summary>
            <div
              class="update-page__release-notes-body update-page__release-notes-body--md"
              v-html="webReleaseNotesHtml"
            />
          </details>

          <p class="update-page__release-foot muted">
            由 Bot 从 GitHub 下载 <code>dist.zip</code> 并解压到控制台静态目录。
          </p>
        </div>
      </div>

      <div
        id="console-update-bot"
        class="panel update-page__panel"
      >
        <div class="panel__hd panel__hd--split update-page__panel-hd-nowrap">
          <h2 class="panel__title">
            <span class="panel__title-ico" aria-hidden="true">{{ panelNavIcon }}</span>Bot 本体
            <RefreshIconButton
              :busy="refreshBotBusy"
              :disabled="busy"
              label="刷新 Bot 更新检查"
              @click="refreshBot"
            />
            <span
              v-if="bot?.has_update"
              class="badge badge--warn update-page__status-pill"
            >有更新</span>
            <span
              v-else-if="bot?.development_build"
              class="badge badge--dev update-page__status-pill"
              title="当前 commit 超前于 GitHub 最新发行版，无需执行「应用 Bot 更新」"
            >开发构建</span>
            <span
              v-else
              class="badge badge--ok update-page__status-pill"
            >已是最新</span>
          </h2>
          <div class="row-actions">
            <PanelSidebarAdd main-path="/update" />
          </div>
        </div>
        <div class="panel__bd update-page__bd update-page__bd--release">
          <div class="update-page__release-summary">
            <div class="update-page__release-stat">
              <span class="update-page__release-stat-label">当前</span>
              <span class="update-page__release-stat-value">{{ bot?.current_tag || "—" }}</span>
              <span
                v-if="bot?.current_commit"
                class="update-page__release-stat-sub muted"
              >{{ bot.current_commit.slice(0, 7) }}</span>
            </div>
            <span
              class="update-page__release-stat-arrow muted"
              aria-hidden="true"
            >→</span>
            <div class="update-page__release-stat">
              <span class="update-page__release-stat-label">远端</span>
              <span class="update-page__release-stat-value">{{ bot?.latest_tag ?? "—" }}</span>
            </div>
          </div>

          <p
            v-if="botMetaParts.length"
            class="update-page__release-meta muted"
          >
            {{ botMetaParts.join(" · ") }}
          </p>

          <div class="update-page__release-primary">
            <button
              v-if="bot?.deployment_mode !== 'docker'"
              type="button"
              class="btn btn--primary"
              :disabled="botApplyDisabled"
              @click="applyBot"
            >
              应用 Bot 更新
            </button>
            <a
              class="update-page__link update-page__release-ext-link"
              :href="(bot?.release_url || '').trim() || BOT_RELEASES_PAGE"
              target="_blank"
              rel="noopener noreferrer"
            >GitHub Release</a>
          </div>

          <p
            v-if="bot?.error"
            class="alert alert--err update-page__release-inline-alert"
          >
            {{ bot.error }}
          </p>
          <div
            v-else-if="botCallout"
            class="update-page__release-callout"
            :class="botCallout.kind === 'warn' ? 'alert alert--warn' : 'update-page__release-callout--info'"
          >
            {{ botCallout.text }}
          </div>

          <section
            v-if="configMigration?.show"
            class="update-page__release-section"
          >
            <h3 class="update-page__release-section-title">配置迁移</h3>
            <p class="muted">
              新版本用 <code>pallas.toml</code> + <code>webui.json</code>；检测到
              <strong>{{ configMigration.legacy_env_key_count }}</strong> 项遗留
              <code>{{ configMigrationLegacyFiles }}</code>。
              <span v-if="configMigration.can_migrate">可一键迁移。</span>
              <span v-else-if="configMigration.suggest_cleanup_legacy_env">覆盖迁移请先备份。</span>
            </p>
            <p class="muted update-page__config-migrate-note">
              迁移会把 Pallas 插件/通用配置写入 <code>webui.json</code>；根目录
              <code>.env</code> 仍可保留，专放 nb/pip 插件环境变量（见仓库
              <code>.env.example</code>）。同名键以 <code>webui.json</code> 为准，请勿重复。
              pip 插件须在 <code>pyproject.toml</code> 的 <code>[tool.nonebot.plugins]</code> 注册后才会加载。
            </p>
            <div
              v-if="configMigration.can_migrate || configMigration.needs_force"
              class="update-page__config-migrate-actions"
            >
              <button
                v-if="configMigration.can_migrate"
                type="button"
                class="btn btn--primary"
                :disabled="configMigrationBusy || busy"
                @click="applyConfigMigration(false)"
              >
                一键迁移
              </button>
              <button
                v-if="configMigration.needs_force"
                type="button"
                class="btn"
                :disabled="configMigrationBusy || busy"
                @click="applyConfigMigration(true)"
              >
                覆盖并迁移
              </button>
            </div>
            <p
              v-if="configMigrationMsg"
              class="alert alert--ok update-page__config-migrate-feedback"
            >
              {{ configMigrationMsg }}
            </p>
            <p
              v-if="configMigrationErr"
              class="alert alert--err update-page__config-migrate-feedback"
            >
              {{ configMigrationErr }}
            </p>
          </section>

          <section
            v-if="bot?.deployment_mode === 'docker'"
            class="update-page__release-section update-page__docker-hint"
          >
            <h3 class="update-page__release-section-title">Docker 更新步骤</h3>
            <ol class="update-page__docker-steps">
              <li><code>docker compose pull pallasbot</code></li>
              <li><code>docker compose up -d pallasbot</code>（未换镜像时加 <code>--force-recreate</code>）</li>
              <li>未用 <code>:latest</code> 时，先把 compose 里 image tag 改为目标版本</li>
            </ol>
            <p class="muted update-page__docker-foot">
              数据与配置通常在卷中（<code>data/</code>、<code>config/pallas.toml</code>、<code>local/plugins/</code>）。
            </p>
          </section>

          <details
            v-if="(bot?.release_notes || '').trim()"
            class="update-page__release-fold update-page__release-notes"
          >
            <summary class="update-page__release-fold-summary">
              {{ bot?.latest_tag ? `「${bot.latest_tag}」发行说明` : "发行说明" }}
            </summary>
            <div
              class="update-page__release-notes-body update-page__release-notes-body--md"
              v-html="botReleaseNotesHtml"
            />
          </details>

          <details class="update-page__release-fold update-page__doc-links">
            <summary class="update-page__release-fold-summary">相关文档</summary>
            <ul class="update-page__doc-links-list">
              <li
                v-for="link in botDocLinks"
                :key="link.href"
              >
                <a
                  class="update-page__link"
                  :href="link.href"
                  target="_blank"
                  rel="noopener noreferrer"
                >{{ link.label }}</a>
              </li>
            </ul>
          </details>

          <p
            v-if="bot?.deployment_mode !== 'docker'"
            class="update-page__release-foot muted"
          >
            配置与数据请放在 <code>config/pallas.toml</code>、<code>data/</code>，避免改主仓 <code>src/</code>。
          </p>
        </div>
      </div>
    </template>
  </div>
</template>

<style scoped>
.update-page__panel + .update-page__panel {
  margin-top: 14px;
}

.update-page__status-pill {
  font-size: 10px;
  font-weight: 650;
  padding: 2px 7px;
  line-height: 1.3;
  letter-spacing: 0.02em;
  max-width: min(11.5rem, 46vw);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  vertical-align: middle;
}

.update-page__bd p {
  margin: 0 0 6px;
}

.update-page__bd--release {
  color: var(--text-muted);
  font-size: 13px;
  line-height: 1.5;
}

.update-page__release-summary {
  display: flex;
  align-items: stretch;
  gap: 10px;
  margin-bottom: 10px;
  padding: 12px 14px;
  border-radius: var(--radius-md);
  border: 1px solid color-mix(in srgb, var(--border) 88%, transparent);
  background: color-mix(in srgb, var(--bg-muted) 45%, transparent);
}

.update-page__release-stat {
  flex: 1 1 0;
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.update-page__release-stat-label {
  font-size: 11px;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  opacity: 0.72;
}

.update-page__release-stat-value {
  font-size: 16px;
  font-weight: 700;
  color: var(--text);
  line-height: 1.25;
  word-break: break-word;
}

.update-page__release-stat-sub {
  font-size: 11px;
  font-family: var(--font-mono, ui-monospace, monospace);
}

.update-page__release-stat-arrow {
  flex: 0 0 auto;
  align-self: center;
  font-size: 18px;
  opacity: 0.5;
}

.update-page__release-meta {
  margin: 0 0 12px !important;
  font-size: 12px;
}

.update-page__release-primary {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 10px 14px;
  margin-bottom: 12px;
}

.update-page__release-ext-link {
  font-size: 13px;
}

.update-page__release-inline-alert,
.update-page__release-callout {
  margin: 0 0 12px !important;
  font-size: 13px;
  line-height: 1.45;
}

.update-page__release-callout--info {
  padding: 8px 10px;
  border-radius: var(--radius-md);
  border: 1px solid color-mix(in srgb, var(--border) 90%, transparent);
  background: color-mix(in srgb, var(--bg-muted) 35%, transparent);
  color: var(--text-muted);
}

.update-page__release-section {
  margin: 0 0 12px;
  padding: 10px 12px;
  border-radius: var(--radius-md);
  border: 1px solid color-mix(in srgb, var(--border) 90%, transparent);
  background: color-mix(in srgb, var(--bg-muted) 30%, transparent);
}

.update-page__release-section-title {
  margin: 0 0 8px;
  font-size: 13px;
  font-weight: 700;
  color: var(--text);
}

.update-page__release-section p {
  margin: 0;
}

.update-page__config-migrate-note {
  margin-top: 8px !important;
  font-size: 12px;
  line-height: 1.45;
}

.update-page__config-migrate-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-top: 10px;
}

.update-page__config-migrate-feedback {
  margin-top: 8px !important;
  margin-bottom: 0 !important;
}

.update-page__release-fold,
.update-page__release-notes {
  margin: 0 0 8px;
  padding: 8px 10px;
  border-radius: var(--radius-sm);
  border: 1px solid color-mix(in srgb, var(--border) 90%, transparent);
  background: color-mix(in srgb, var(--bg-muted) 25%, transparent);
}

.update-page__release-fold-summary {
  cursor: pointer;
  font-size: 13px;
  font-weight: 650;
  color: var(--text);
  user-select: none;
}

.update-page__release-foot {
  margin: 4px 0 0 !important;
  font-size: 12px;
}

.update-page__doc-links {
  margin: 0;
  padding: 8px 10px;
  border: none;
  background: transparent;
}

.update-page__doc-links-list {
  margin: 8px 0 0;
  padding-left: 1.2rem;
  font-size: 13px;
  line-height: 1.5;
}

.update-page__doc-links-list li + li {
  margin-top: 4px;
}

.update-page__bd p:last-of-type {
  margin-bottom: 0;
}

.update-page__strong {
  color: var(--text);
  font-weight: 650;
}

.update-page__changelog-row {
  margin: 2px 0 8px;
  font-size: 13px;
}

.update-page__link {
  color: var(--accent);
  font-weight: 600;
  text-decoration: none;
}

.update-page__link:hover {
  text-decoration: underline;
  text-underline-offset: 2px;
}

.update-page__release-notes-body {
  margin: 8px 0 0;
  padding: 0;
  max-height: min(42vh, 320px);
  overflow: auto;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
  font-size: 12px;
  line-height: 1.45;
  white-space: pre-wrap;
  word-break: break-word;
  color: var(--text-muted);
}

.update-page__release-notes-body--md {
  white-space: normal;
}

.update-page__release-notes-body--md :deep(a.update-page__commit-link) {
  color: var(--accent);
  font-weight: 600;
  text-decoration: none;
  white-space: nowrap;
}

.update-page__release-notes-body--md :deep(a.update-page__commit-link:hover) {
  text-decoration: underline;
  text-underline-offset: 2px;
}

.update-page__docker-hint {
  margin: 0;
  padding: 0;
  border: none;
  background: transparent;
}

.update-page__docker-steps {
  margin: 0 0 8px;
  padding-left: 1.25rem;
}

.update-page__docker-steps li {
  margin-bottom: 4px;
}

.update-page__docker-foot {
  margin: 0 !important;
  font-size: 12px;
}

.update-page__apply {
  margin-top: 14px;
}

.update-page__gh-row {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 10px;
  margin-top: 12px;
}

.update-page__gh-inp {
  flex: 1 1 220px;
  min-width: 0;
  max-width: 520px;
}

.update-page__gh-alert {
  margin-top: 12px;
}

.update-page__gh-more {
  margin: 14px 0 0;
  font-size: 13px;
  line-height: 1.5;
}

.update-page__title-keep {
  white-space: nowrap;
}

@media (max-width: 560px) {
  .update-page__gh-row {
    flex-direction: column;
    align-items: stretch;
    gap: 8px;
  }

  .update-page__gh-inp {
    flex: 1 1 auto;
    max-width: none;
  }

  .update-page__gh-row .btn {
    padding: 7px 12px;
    font-size: 13px;
    line-height: 1.25;
    min-height: 0;
  }
}
</style>

// react/src/pages/UpdatePage.tsx
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Link, useLocation } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { axiosErrorDetail } from "@/api/http";
import { fetchPluginConfig, putPluginConfig } from "@/api/console";
import {
  fetchUpdateCheckAll,
  postBotUpdateApply,
  postUpdateApply,
} from "@/api/fullConsole";
import { releaseNotesToSafeHtml } from "@/utils/releaseNotesHtml";
import { pallasBotVersionLabel, updateCheckCurrentTagLabel } from "@/utils/versionDisplay";
import {
  PALLAS_BOT_DOC,
  PALLAS_BOT_RELEASES,
  PALLAS_BOT_REPO,
  PALLAS_WEBUI_RELEASES,
  PALLAS_WEBUI_REPO,
} from "@/utils/pallasExternalLinks";
import GitMirrorDialog from "@/components/GitMirrorDialog";
import PageMasthead from "@/components/PageMasthead";
import RefreshIconButton from "@/components/RefreshIconButton";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import UiInput from "@/components/ui/UiInput";
import { useBotSystemRestart } from "@/hooks/useBotSystemRestart";
import { cn } from "@/lib/utils";
import { pushConsoleToast } from "@/utils/consoleToast";
import { ChevronRight, RefreshCw } from "lucide-react";

const PB_PROTOCOL_PLUGIN = "pb_protocol";
const GITHUB_TOKEN_FIELD = "pallas_protocol_github_token";
const WEBUI_RELEASES_PAGE = PALLAS_WEBUI_RELEASES;
const BOT_RELEASES_PAGE = PALLAS_BOT_RELEASES;

const UPDATE_PANEL = "update-page__panel flex flex-col overflow-hidden shadow-none";
const UPDATE_PANEL_HD =
  "panel__hd panel__hd--split update-page__panel-hd-nowrap flex-row items-center justify-between space-y-0 border-b px-4 py-3";
const UPDATE_PANEL_BD = "panel__bd update-page__bd update-page__bd--release space-y-0 px-4 pb-4 pt-3";
const UPDATE_OPS_BD = "panel__bd update-page__bd px-4 pb-4 pt-3";
const UPDATE_STATUS_PILL = "update-page__status-pill";

function UpdateFoldSummary({ children }: { children: ReactNode }) {
  return (
    <summary className="update-page__release-fold-summary">
      <ChevronRight className="update-page__release-fold-chevron" aria-hidden strokeWidth={2} />
      <span className="min-w-0">{children}</span>
    </summary>
  );
}

function formatCheckedAt(ts?: number | null): string {
  if (ts == null || !Number.isFinite(ts) || ts <= 0) return "—";
  try {
    return new Date(ts * 1000).toLocaleString(undefined, {
      month: "2-digit",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
    });
  } catch {
    return "—";
  }
}

function botDeployLabel(mode?: string | null): string {
  if (mode === "docker") return "Docker";
  if (mode === "release_tag") return "正式版";
  if (mode === "release_tag_dirty") return "正式版 · 有本地改动";
  if (mode === "dev_clone") return "开发克隆";
  return "—";
}

function releaseNotesFoldSummary(
  currentTag: string | null | undefined,
  latestTag: string | null | undefined,
  hasUpdate: boolean | null | undefined,
): string {
  const latest = (latestTag || "").trim();
  const current = (currentTag || "").trim();
  if (hasUpdate && current && latest) return `${current} → ${latest} 更新说明`;
  if (latest) return `「${latest}」发行说明`;
  return "发行说明";
}

export default function UpdatePage() {
  const qc = useQueryClient();
  const location = useLocation();
  const [busy, setBusy] = useState(false);
  const [msg, setMsg] = useState("");
  const [err, setErr] = useState("");
  const [gitMirrorOpen, setGitMirrorOpen] = useState(false);
  const [ghTokenInput, setGhTokenInput] = useState("");
  const [ghTokenHadValue, setGhTokenHadValue] = useState(false);
  const [ghTokenBusy, setGhTokenBusy] = useState(false);
  const [ghTokenErr, setGhTokenErr] = useState("");
  const [ghTokenOk, setGhTokenOk] = useState("");

  const q = useQuery({ queryKey: ["update-check-all"], queryFn: fetchUpdateCheckAll });
  const web = q.data?.webui;
  const bot = q.data?.bot;

  const {
    restartBusy,
    restartErr,
    restartMsg,
    restartProgressLabel,
    restartInProgress,
    restartAvailable,
    shardedRuntime,
    ensureRestartContext,
    restartBot,
  } = useBotSystemRestart({ botUpdateCheck: bot ?? null });

  const webCurrentDisplay = updateCheckCurrentTagLabel(web?.current_tag);
  const botCurrentDisplay = pallasBotVersionLabel(undefined, bot);
  const webReleaseNotesHtml = useMemo(() => releaseNotesToSafeHtml(web?.release_notes), [web?.release_notes]);
  const botReleaseNotesHtml = useMemo(() => releaseNotesToSafeHtml(bot?.release_notes), [bot?.release_notes]);
  const webReleaseNotesSummary = releaseNotesFoldSummary(web?.current_tag, web?.latest_tag, web?.has_update);
  const botReleaseNotesSummary = releaseNotesFoldSummary(bot?.current_tag, bot?.latest_tag, bot?.has_update);

  const webCallout = web?.has_update ? "更新完成后页面会自动刷新。" : null;
  const botCallout = useMemo((): { kind: "warn" | "info"; text: string } | null => {
    if (!bot) return null;
    if (bot.deployment_mode === "docker") {
      return { kind: "warn", text: "控制台不能 git 拉代码；请按下方步骤拉新镜像并重启容器。" };
    }
    if (bot.deployment_mode === "release_tag_dirty") {
      return {
        kind: "warn",
        text: `更新前会自动 stash ${bot.dirty_file_count ?? 0} 项本地改动；冲突时需 git stash pop。建议插件放 local/plugins/。`,
      };
    }
    if (bot.deployment_mode === "dev_clone") {
      return { kind: "info", text: "更新时执行 git pull --ff-only --autostash。" };
    }
    return null;
  }, [bot]);

  const botMetaParts = useMemo(() => {
    if (!bot) return [] as string[];
    const parts: string[] = [botDeployLabel(bot.deployment_mode)];
    if (bot.git_available && bot.current_branch) parts.push(`分支 ${bot.current_branch}`);
    if (bot.dirty && (bot.dirty_file_count ?? 0) > 0) parts.push(`改动 ${bot.dirty_file_count} 项`);
    return parts;
  }, [bot]);

  const updateMastheadLead = useMemo(() => {
    const parts: string[] = [];
    if (web) parts.push(`WebUI ${webCurrentDisplay}${web.has_update ? " · 有更新" : ""}`);
    if (bot) parts.push(`Bot ${botCurrentDisplay}${bot.has_update ? " · 有更新" : ""}`);
    return parts.length ? parts.join(" · ") : "WebUI 与 Bot 版本更新。";
  }, [bot, botCurrentDisplay, web, webCurrentDisplay]);

  const checkedAtDisplay = formatCheckedAt(q.data?.checked_at);
  const webApplyDisabled = busy || !web?.has_update || !web?.latest_tag;
  const botApplyDisabled =
    busy || !bot?.has_update || !bot?.latest_tag || bot?.deployment_mode === "docker";

  const botDocLinks = useMemo(() => {
    const isDocker = bot?.deployment_mode === "docker";
    const links: { href: string; label: string }[] = [
      { href: PALLAS_BOT_DOC.home, label: "在线文档" },
      { href: PALLAS_BOT_REPO, label: "Pallas-Bot 仓库" },
      { href: PALLAS_BOT_DOC.siteCustomization, label: "站点定制与更新" },
      { href: PALLAS_BOT_DOC.localReadme, label: "local 目录说明" },
    ];
    if (isDocker) links.unshift({ href: PALLAS_BOT_DOC.dockerDeployment, label: "Docker 部署" });
    else links.push({ href: PALLAS_BOT_DOC.deployment, label: "标准部署" });
    links.push({ href: PALLAS_BOT_DOC.faqUpdates, label: "FAQ · 更新与版本" });
    return links;
  }, [bot?.deployment_mode]);

  const webDocLinks = useMemo(
    () => [
      { href: (web?.release_url || "").trim() || WEBUI_RELEASES_PAGE, label: "GitHub Release" },
      { href: PALLAS_WEBUI_REPO, label: "Pallas-Bot-WebUI 仓库" },
      { href: PALLAS_BOT_DOC.siteCustomization, label: "站点定制与更新" },
      { href: PALLAS_BOT_DOC.faqUpdates, label: "FAQ · 更新与版本" },
    ],
    [web?.release_url],
  );

  useEffect(() => {
    void loadGithubTokenHint();
  }, []);

  useEffect(() => {
    if (q.isSuccess) void ensureRestartContext();
  }, [q.isSuccess, ensureRestartContext]);

  useEffect(() => {
    const raw = (location.hash || "").replace(/^#/, "").trim();
    if (!raw || q.isLoading) return;
    requestAnimationFrame(() => {
      document.getElementById(raw)?.scrollIntoView({ behavior: "smooth", block: "start" });
    });
  }, [location.hash, q.isLoading, q.dataUpdatedAt]);

  async function loadGithubTokenHint() {
    setGhTokenErr("");
    setGhTokenOk("");
    try {
      const data = await fetchPluginConfig(PB_PROTOCOL_PLUGIN);
      const f = data.fields.find((x) => x.name === GITHUB_TOKEN_FIELD);
      const cur = f?.current;
      const s = cur === null || cur === undefined ? "" : String(cur).trim();
      setGhTokenHadValue(s.length > 0);
      setGhTokenInput("");
    } catch (e) {
      setGhTokenErr(e instanceof Error ? e.message : String(e));
      setGhTokenHadValue(false);
    }
  }

  async function saveGithubToken() {
    const next = ghTokenInput.trim();
    if (!next) {
      setGhTokenErr("请输入新令牌，或使用下方「清除」移除已保存的令牌。");
      return;
    }
    setGhTokenBusy(true);
    setGhTokenErr("");
    setGhTokenOk("");
    try {
      await putPluginConfig(PB_PROTOCOL_PLUGIN, { [GITHUB_TOKEN_FIELD]: next });
      setGhTokenHadValue(true);
      setGhTokenInput("");
      setGhTokenOk("配置已保存；若未立即生效可重启 Bot。");
      pushConsoleToast("GitHub 令牌已保存", "ok");
    } catch (e) {
      const detail = e instanceof Error ? e.message : String(e);
      setGhTokenErr(detail);
      pushConsoleToast(detail, "err");
    } finally {
      setGhTokenBusy(false);
    }
  }

  async function clearGithubToken() {
    if (!window.confirm("确定清除已保存的 GitHub 令牌？")) return;
    setGhTokenBusy(true);
    setGhTokenErr("");
    setGhTokenOk("");
    try {
      await putPluginConfig(PB_PROTOCOL_PLUGIN, { [GITHUB_TOKEN_FIELD]: "" });
      setGhTokenHadValue(false);
      setGhTokenInput("");
      setGhTokenOk("已清除；重启 Bot 后生效。");
      pushConsoleToast("GitHub 令牌已清除", "ok");
    } catch (e) {
      const detail = e instanceof Error ? e.message : String(e);
      setGhTokenErr(detail);
      pushConsoleToast(detail, "err");
    } finally {
      setGhTokenBusy(false);
    }
  }

  async function applyWeb() {
    if (!web?.latest_tag) return;
    if (!window.confirm(`将 WebUI 更新到 ${web.latest_tag}？`)) return;
    setBusy(true);
    setErr("");
    setMsg("");
    try {
      const r = await postUpdateApply();
      setMsg(r.message ? `${r.message} · 正在刷新页面以载入新版本…` : "WebUI 已更新，正在刷新页面…");
      window.setTimeout(() => window.location.reload(), 800);
    } catch (e) {
      setErr(axiosErrorDetail(e));
    } finally {
      setBusy(false);
    }
  }

  async function applyBot(restart = false) {
    if (!bot?.latest_tag) return;
    const prompt = restart
      ? `将 Bot 更新到 ${bot.latest_tag} 并重启进程？`
      : `将 Bot 更新到 ${bot.latest_tag}？`;
    if (!window.confirm(prompt)) return;
    setBusy(true);
    setErr("");
    setMsg("");
    try {
      const r = await postBotUpdateApply({ restart });
      setMsg(r.message || (restart ? "已触发更新与重启。" : "已触发。"));
      if (!restart) await qc.invalidateQueries({ queryKey: ["update-check-all"] });
    } catch (e) {
      setErr(axiosErrorDetail(e));
    } finally {
      setBusy(false);
    }
  }

  async function triggerBotRestart(workersOnly = false) {
    setErr("");
    setMsg("");
    const ok = await restartBot(workersOnly);
    if (ok) setMsg(restartProgressLabel || restartMsg || "Bot 已恢复在线。");
    else if (restartErr) setErr(restartErr);
  }

  return (
    <div className="update-page console-hub-page">
      {err ? <div className="alert alert--err">{err}</div> : null}
      {msg ? <div className="alert alert--ok">{msg}</div> : null}

      <PageMasthead
        title="更新"
        description={
          <>
            {updateMastheadLead}
            {checkedAtDisplay !== "—" ? (
              <span className="update-page__checked-at muted"> · 检查于 {checkedAtDisplay}</span>
            ) : null}
          </>
        }
        actions={
          <div className="flex flex-wrap items-center gap-1.5">
            <Button type="button" variant="secondary" size="sm" onClick={() => setGitMirrorOpen(true)}>
              镜像源
            </Button>
            <Button
              type="button"
              variant="secondary"
              size="sm"
              disabled={q.isFetching || busy}
              onClick={() => void q.refetch()}
            >
              <RefreshCw className={cn("size-3.5", (q.isFetching || busy) && "animate-spin")} />
              {q.isFetching || busy ? "检查中…" : "重新检查"}
            </Button>
          </div>
        }
      />

      <div className="update-page__overview">
        <a
          href="#console-update-webui"
          className={cn("update-page__overview-card", web?.has_update && "update-page__overview-card--warn")}
        >
          <span className="update-page__overview-k">WebUI</span>
          <span className="update-page__overview-v">{webCurrentDisplay}</span>
          <span className="update-page__overview-meta muted">
            {web?.has_update ? `→ ${web?.latest_tag ?? "?"}` : "已是最新"}
          </span>
        </a>
        <a
          href="#console-update-bot"
          className={cn("update-page__overview-card", bot?.has_update && "update-page__overview-card--warn")}
        >
          <span className="update-page__overview-k">Bot</span>
          <span className="update-page__overview-v">{botCurrentDisplay}</span>
          <span className="update-page__overview-meta muted">
            {bot?.has_update ? `→ ${bot?.latest_tag ?? "?"}` : botDeployLabel(bot?.deployment_mode)}
          </span>
        </a>
      </div>

      <Card id="console-update-webui" className={UPDATE_PANEL}>
        <CardHeader className={UPDATE_PANEL_HD}>
          <CardTitle className="panel__title flex flex-wrap items-center gap-1.5">
            WebUI
            <RefreshIconButton
              embedded
              showLabel={false}
              busy={q.isFetching}
              disabled={busy}
              label="刷新 WebUI 更新检查"
              onClick={() => void q.refetch()}
            />
            {web?.has_update ? (
              <Badge className={UPDATE_STATUS_PILL} variant="warn">
                有更新
              </Badge>
            ) : (
              <Badge className={UPDATE_STATUS_PILL} variant="success">
                已是最新
              </Badge>
            )}
          </CardTitle>
        </CardHeader>
        <CardContent className={UPDATE_PANEL_BD}>
          <div className="update-page__release-summary">
            <div className="update-page__release-stat">
              <span className="update-page__release-stat-label">当前</span>
              <span className="update-page__release-stat-value">{webCurrentDisplay}</span>
            </div>
            <span className="update-page__release-stat-arrow muted" aria-hidden="true">
              →
            </span>
            <div className="update-page__release-stat">
              <span className="update-page__release-stat-label">远端</span>
              <span className="update-page__release-stat-value">{web?.latest_tag ?? "—"}</span>
            </div>
          </div>

          <div className="update-page__release-primary">
            <Button type="button" disabled={webApplyDisabled} onClick={() => void applyWeb()}>
              {busy ? "处理中…" : "应用 WebUI 更新"}
            </Button>
            <a
              className="update-page__link update-page__release-ext-link"
              href={(web?.release_url || "").trim() || WEBUI_RELEASES_PAGE}
              target="_blank"
              rel="noopener noreferrer"
            >
              GitHub Release
            </a>
          </div>

          {web?.error ? (
            <p className="alert alert--err update-page__release-inline-alert">{web.error}</p>
          ) : webCallout ? (
            <div className="update-page__release-callout update-page__release-callout--info">{webCallout}</div>
          ) : null}

          <details className="update-page__release-fold update-page__release-notes">
            <UpdateFoldSummary>{webReleaseNotesSummary}</UpdateFoldSummary>
            {(web?.release_notes || "").trim() ? (
              <div
                className="update-page__release-notes-body update-page__release-notes-body--md"
                dangerouslySetInnerHTML={{ __html: webReleaseNotesHtml }}
              />
            ) : (
              <p className="update-page__release-notes-empty muted">
                GitHub 未提供发行说明正文，请查看{" "}
                <a
                  className="update-page__link"
                  href={(web?.release_url || "").trim() || WEBUI_RELEASES_PAGE}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Release 页面
                </a>
                。
              </p>
            )}
          </details>

          <details className="update-page__release-fold update-page__doc-links">
            <UpdateFoldSummary>相关文档</UpdateFoldSummary>
            <ul className="update-page__doc-links-list">
              {webDocLinks.map((link) => (
                <li key={link.href}>
                  <a className="update-page__link" href={link.href} target="_blank" rel="noopener noreferrer">
                    {link.label}
                  </a>
                </li>
              ))}
            </ul>
          </details>

          <p className="update-page__release-foot muted">
            由 Bot 从 GitHub 下载 <code>dist.zip</code> 并解压到控制台静态目录。
          </p>
        </CardContent>
      </Card>

      <Card id="console-update-bot" className={UPDATE_PANEL}>
        <CardHeader className={UPDATE_PANEL_HD}>
          <CardTitle className="panel__title flex flex-wrap items-center gap-1.5">
            Bot 本体
            <RefreshIconButton
              embedded
              showLabel={false}
              busy={q.isFetching}
              disabled={busy}
              label="刷新 Bot 更新检查"
              onClick={() => void q.refetch()}
            />
            {bot?.has_update ? (
              <Badge className={UPDATE_STATUS_PILL} variant="warn">
                有更新
              </Badge>
            ) : bot?.development_build ? (
              <Badge
                className={UPDATE_STATUS_PILL}
                variant="secondary"
                title="当前 commit 超前于 GitHub 最新发行版，无需执行「应用 Bot 更新」"
              >
                开发构建
              </Badge>
            ) : (
              <Badge className={UPDATE_STATUS_PILL} variant="success">
                已是最新
              </Badge>
            )}
          </CardTitle>
        </CardHeader>
        <CardContent className={UPDATE_PANEL_BD}>
          <div className="update-page__release-summary">
            <div className="update-page__release-stat">
              <span className="update-page__release-stat-label">当前</span>
              <span className="update-page__release-stat-value">{botCurrentDisplay}</span>
              {bot?.current_commit ? (
                <span className="update-page__release-stat-sub muted">{bot.current_commit.slice(0, 7)}</span>
              ) : null}
            </div>
            <span className="update-page__release-stat-arrow muted" aria-hidden="true">
              →
            </span>
            <div className="update-page__release-stat">
              <span className="update-page__release-stat-label">远端</span>
              <span className="update-page__release-stat-value">{bot?.latest_tag ?? "—"}</span>
            </div>
          </div>

          {botMetaParts.length ? (
            <p className="update-page__release-meta muted">{botMetaParts.join(" · ")}</p>
          ) : null}

          <div className="update-page__release-primary">
            {bot?.deployment_mode !== "docker" ? (
              <Button type="button" disabled={botApplyDisabled} onClick={() => void applyBot(false)}>
                应用 Bot 更新
              </Button>
            ) : null}
            {bot?.deployment_mode !== "docker" && bot?.restart_available ? (
              <Button type="button" variant="outline" disabled={botApplyDisabled} onClick={() => void applyBot(true)}>
                更新并重启
              </Button>
            ) : null}
            <a
              className="update-page__link update-page__release-ext-link"
              href={(bot?.release_url || "").trim() || BOT_RELEASES_PAGE}
              target="_blank"
              rel="noopener noreferrer"
            >
              GitHub Release
            </a>
          </div>

          {bot?.error ? (
            <p className="alert alert--err update-page__release-inline-alert">{bot.error}</p>
          ) : botCallout ? (
            <div
              className={cn(
                "update-page__release-callout",
                botCallout.kind === "warn" ? "alert alert--warn" : "update-page__release-callout--info",
              )}
            >
              {botCallout.text}
            </div>
          ) : null}

          {bot?.deployment_mode === "docker" ? (
            <section className="update-page__release-section update-page__docker-hint">
              <h3 className="update-page__release-section-title">Docker 更新步骤</h3>
              <ol className="update-page__docker-steps">
                <li>
                  <code>docker compose pull pallasbot</code>
                </li>
                <li>
                  <code>docker compose up -d pallasbot</code>（未换镜像时加 <code>--force-recreate</code>）
                </li>
                <li>
                  未用 <code>:latest</code> 时，先把 compose 里 image tag 改为目标版本
                </li>
              </ol>
              <p className="muted update-page__docker-foot">
                数据与配置通常在卷中（<code>data/</code>、<code>config/pallas.toml</code>、<code>local/plugins/</code>）。
              </p>
            </section>
          ) : null}

          <details className="update-page__release-fold update-page__release-notes">
            <UpdateFoldSummary>{botReleaseNotesSummary}</UpdateFoldSummary>
            {(bot?.release_notes || "").trim() ? (
              <div
                className="update-page__release-notes-body update-page__release-notes-body--md"
                dangerouslySetInnerHTML={{ __html: botReleaseNotesHtml }}
              />
            ) : (
              <p className="update-page__release-notes-empty muted">
                GitHub 未提供发行说明正文，请查看{" "}
                <a
                  className="update-page__link"
                  href={(bot?.release_url || "").trim() || BOT_RELEASES_PAGE}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Release 页面
                </a>
                。
              </p>
            )}
          </details>

          <details className="update-page__release-fold update-page__doc-links">
            <UpdateFoldSummary>相关文档</UpdateFoldSummary>
            <ul className="update-page__doc-links-list">
              {botDocLinks.map((link) => (
                <li key={link.href}>
                  <a className="update-page__link" href={link.href} target="_blank" rel="noopener noreferrer">
                    {link.label}
                  </a>
                </li>
              ))}
            </ul>
          </details>

          {bot?.deployment_mode !== "docker" ? (
            <p className="update-page__release-foot muted">
              配置与数据请放在 <code>config/pallas.toml</code>、<code>data/</code>，避免改主仓 <code>src/</code>。
            </p>
          ) : null}
        </CardContent>
      </Card>

      {restartAvailable ? (
        <Card id="console-update-restart" className={cn(UPDATE_PANEL, "update-page__panel--ops")}>
          <CardHeader className={cn(UPDATE_PANEL_HD, "update-page__ops-hd")}>
            <CardTitle className="panel__title">运维</CardTitle>
          </CardHeader>
          <CardContent className={UPDATE_OPS_BD}>
            <p className="muted update-page__ops-lead">
              安装/更新插件或修改需重启生效的配置后，可在此触发 Bot 进程重启。与「更新并重启」不同，此处不会拉取新代码。
              {shardedRuntime ? "分片部署下可选择仅重启分片节点或重启全部进程。" : null}
            </p>
            {restartInProgress || restartMsg ? (
              <p className="muted update-page__ops-lead" role="status">
                {restartProgressLabel || restartMsg}
              </p>
            ) : null}
            {restartErr ? (
              <p className="alert alert--err update-page__ops-lead" role="alert">
                {restartErr}
              </p>
            ) : null}
            <div className="flex flex-wrap items-center gap-1.5 update-page__ops-actions">
              {shardedRuntime ? (
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  disabled={restartBusy || restartInProgress}
                  onClick={() => void triggerBotRestart(true)}
                >
                  重启 Worker
                </Button>
              ) : null}
              <Button
                type="button"
                variant="destructive"
                size="sm"
                disabled={restartBusy || restartInProgress}
                onClick={() => void triggerBotRestart(false)}
              >
                {restartInProgress ? "重启中…" : shardedRuntime ? "重启全部进程" : "重启 Bot"}
              </Button>
            </div>
          </CardContent>
        </Card>
      ) : null}

      <details id="console-update-github" className="update-page__gh-fold">
        <summary className="update-page__gh-fold-summary">
          GitHub 令牌
          <span className="muted"> · {ghTokenHadValue ? "已配置" : "未配置"}</span>
        </summary>
        <div className="update-page__gh-fold-body muted update-page__bd">
          <p>
            可选。用于 Release 检查与下载、协议端在线拉包等。也可在{" "}
            <Link to={`/plugins/${PB_PROTOCOL_PLUGIN}`}>插件配置 → 协议端</Link> 填写{" "}
            <code>PALLAS_PROTOCOL_GITHUB_TOKEN</code>。
          </p>
          <div className="update-page__gh-row">
            <UiInput
              className="update-page__gh-inp"
              type="password"
              revealable
              autoComplete="off"
              placeholder="粘贴 fine-grained 或 classic PAT"
              disabled={ghTokenBusy}
              value={ghTokenInput}
              onValueChange={setGhTokenInput}
            />
            <Button type="button" size="sm" disabled={ghTokenBusy} onClick={() => void saveGithubToken()}>
              {ghTokenBusy ? "保存中…" : "保存"}
            </Button>
            {ghTokenHadValue ? (
              <Button type="button" variant="outline" size="sm" disabled={ghTokenBusy} onClick={() => void clearGithubToken()}>
                清除
              </Button>
            ) : null}
          </div>
          {ghTokenErr ? <div className="alert alert--err update-page__gh-alert">{ghTokenErr}</div> : null}
          {ghTokenOk ? <div className="alert alert--ok update-page__gh-alert">{ghTokenOk}</div> : null}
        </div>
      </details>

      <GitMirrorDialog open={gitMirrorOpen} onClose={() => setGitMirrorOpen(false)} />
    </div>
  );
}
