// src/layout/AppShell.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from "vue";
import { useRoute } from "vue-router";
import brandMarkUrl from "@/assets/pallas-priest.png?url";
import { fetchHealth } from "@/api/health";
import type { HealthResponse } from "@/api/health";
import { mainNavIconForPath, mainNavItemByPath, type MainNavItem } from "@/config/mainNav";
import { consolePrefs, setConsolePrefs } from "@/utils/consolePrefs";
import { initialShellLoading, routeNavLoading } from "@/utils/routeLoading";
import type { ThemeMode } from "@/utils/consolePrefs";

const dragPath = ref<string | null>(null);
const dragOverPath = ref<string | null>(null);

const orderedNav = computed((): MainNavItem[] =>
  consolePrefs.sidebarNavOrder
    .map((to) => mainNavItemByPath(to))
    .filter((item): item is MainNavItem => item != null),
);

const route = useRoute();
const mobileNavOpen = ref(false);
const isNarrow = ref(false);

const webuiVersion = __WEBUI_VERSION__;

/** 与首屏「控制台资源」一致：优先展示服务端上报的静态资源版本，缺失时回退构建号 */
const brandVersionDisplay = computed(() => {
  const c = health.value?.console;
  const ver = (c?.version || "").trim();
  const commit = (c?.commit || "").trim();
  const short = commit.length >= 7 ? commit.slice(0, 7) : commit;
  if (ver) {
    return short && !ver.includes(short) ? `${ver} · ${short}` : ver;
  }
  return `v${webuiVersion}`;
});

const mainInnerClass = computed(() => ({
  "shell__main-inner": true,
  "shell__main-inner--logs": route.name === "logs",
}));

const pageLoadingVisible = computed(() => routeNavLoading.value || initialShellLoading.value);

const pageLoadingTitle = computed(() => {
  const t = route.meta?.title;
  return typeof t === "string" && t.trim() ? t.trim() : "页面";
});

const topBarTitle = computed(() => {
  if (route.name === "plugin-config") {
    const n = route.params.name;
    if (typeof n === "string" && n.trim()) return n.trim();
  }
  const t = route.meta?.title;
  return typeof t === "string" && t.trim() ? t.trim() : "控制台";
});

const topBarIcon = computed(() => mainNavIconForPath(route.path));

const topBarDesc = computed(() => {
  const d = route.meta?.description;
  return typeof d === "string" && d.trim() ? d.trim() : "";
});

const health = ref<HealthResponse | null>(null);
const healthErr = ref("");
const healthLoading = ref(true);

const connectionBadge = computed(() => {
  if (healthLoading.value) {
    return { text: "API …", cls: "shell__topbar-conn shell__topbar-conn--pending" as const };
  }
  if (healthErr.value) {
    return { text: "未连接", cls: "shell__topbar-conn shell__topbar-conn--err" as const };
  }
  if (health.value?.ok) {
    return { text: "已连接", cls: "shell__topbar-conn shell__topbar-conn--ok" as const };
  }
  return { text: "API 异常", cls: "shell__topbar-conn shell__topbar-conn--warn" as const };
});

let healthPollTimer: ReturnType<typeof setInterval> | null = null;

async function refreshHealth() {
  healthLoading.value = true;
  healthErr.value = "";
  try {
    health.value = await fetchHealth();
  } catch (e) {
    healthErr.value = e instanceof Error ? e.message : String(e);
    health.value = null;
  } finally {
    healthLoading.value = false;
  }
}

function updateNarrow() {
  isNarrow.value = window.matchMedia("(max-width: 860px)").matches;
}

function closeMobileNav() {
  mobileNavOpen.value = false;
}

function setTheme(mode: ThemeMode) {
  setConsolePrefs({ theme: mode });
}

function toggleSidebar() {
  setConsolePrefs({ sidebarCollapsed: !consolePrefs.sidebarCollapsed });
}

function exitConsole() {
  if (typeof window === "undefined") return;
  if (window.history.length > 1) {
    window.history.back();
    return;
  }
  try {
    const ref = document.referrer;
    if (ref) {
      const u = new URL(ref);
      if (u.origin === window.location.origin) {
        window.location.assign(ref);
        return;
      }
    }
  } catch {
    /* ignore */
  }
  window.close();
}

function reorderNavPaths(fromPath: string, toPath: string) {
  if (fromPath === toPath) return;
  const order = [...consolePrefs.sidebarNavOrder];
  const fi = order.indexOf(fromPath);
  const ti = order.indexOf(toPath);
  if (fi < 0 || ti < 0) return;
  const [moved] = order.splice(fi, 1);
  order.splice(ti, 0, moved);
  setConsolePrefs({ sidebarNavOrder: order });
}

function onGripDragStart(path: string, e: DragEvent) {
  dragPath.value = path;
  e.dataTransfer?.setData("text/plain", path);
  if (e.dataTransfer) e.dataTransfer.effectAllowed = "move";
}

function onNavDragOver(path: string, e: DragEvent) {
  if (!dragPath.value) return;
  e.preventDefault();
  if (e.dataTransfer) e.dataTransfer.dropEffect = "move";
  dragOverPath.value = path;
}

function onNavDragLeave(path: string) {
  if (dragOverPath.value === path) dragOverPath.value = null;
}

function onNavDrop(targetPath: string, e: DragEvent) {
  e.preventDefault();
  const fromPath = (e.dataTransfer?.getData("text/plain") || "").trim() || dragPath.value || "";
  reorderNavPaths(fromPath, targetPath);
  dragPath.value = null;
  dragOverPath.value = null;
}

function onGripDragEnd() {
  dragPath.value = null;
  dragOverPath.value = null;
}

const shellClass = computed(() => ({
  shell: true,
  "shell--sidebar-collapsed": consolePrefs.sidebarCollapsed,
}));

function navCollapsedLabel(collapsed: boolean, label: string) {
  return collapsed ? label : undefined;
}

onMounted(() => {
  updateNarrow();
  window.addEventListener("resize", updateNarrow);
  void refreshHealth();
  healthPollTimer = setInterval(() => {
    void refreshHealth();
  }, 45000);
});

watch(mobileNavOpen, (open) => {
  if (typeof document === "undefined") return;
  document.body.style.overflow = open ? "hidden" : "";
});

watch(
  () => route.fullPath,
  () => {
    closeMobileNav();
    void refreshHealth();
  },
);

onUnmounted(() => {
  window.removeEventListener("resize", updateNarrow);
  if (healthPollTimer != null) {
    clearInterval(healthPollTimer);
    healthPollTimer = null;
  }
  if (typeof document !== "undefined") {
    document.body.style.overflow = "";
  }
});
</script>

<template>
  <div :class="shellClass">
    <div class="shell__bg" aria-hidden="true" />
    <header
      class="shell__topbar"
      aria-label="当前页与连接"
    >
      <div class="shell__topbar-start">
        <div class="shell__topbar-rail">
          <button
            v-if="!isNarrow"
            type="button"
            class="shell__topbar-collapse"
            :aria-expanded="!consolePrefs.sidebarCollapsed"
            :aria-label="consolePrefs.sidebarCollapsed ? '展开菜单栏' : '收起菜单栏'"
            @click="toggleSidebar"
          >
            {{ consolePrefs.sidebarCollapsed ? "»" : "«" }}
          </button>
          <button
            v-else
            type="button"
            class="shell__topbar-menu"
            aria-label="打开导航菜单"
            aria-controls="shell-mobile-nav-panel"
            @click="mobileNavOpen = true"
          >
            ☰
          </button>
          <span class="shell__topbar-vrule" aria-hidden="true" />
        </div>
      </div>
      <div class="shell__topbar-lead">
        <h1 class="shell__topbar-title">
          <span class="shell__topbar-ico" aria-hidden="true">{{ topBarIcon }}</span>
          <span class="shell__topbar-title-text">{{ topBarTitle }}</span>
        </h1>
        <p
          v-if="topBarDesc"
          class="shell__topbar-desc muted"
          :class="{ 'shell__topbar-desc--hide-narrow': isNarrow }"
          :title="topBarDesc"
        >
          {{ topBarDesc }}
        </p>
      </div>
      <div class="shell__topbar-end">
        <span
          :class="connectionBadge.cls"
          :title="healthErr || (healthLoading ? '正在探测 API' : undefined)"
        >{{ connectionBadge.text }}</span>
        <div
          class="shell-toolbar__seg shell-toolbar__seg--compact shell__topbar-theme"
          role="group"
          aria-label="颜色模式"
        >
          <button
            type="button"
            :class="{ 'is-on': consolePrefs.theme === 'dark' }"
            title="深色"
            aria-label="深色"
            @click="setTheme('dark')"
          >
            <span class="shell__theme-ico" aria-hidden="true">
              <svg
                class="shell__ico"
                viewBox="0 0 24 24"
                fill="currentColor"
              ><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z" /></svg>
            </span>
          </button>
          <button
            type="button"
            :class="{ 'is-on': consolePrefs.theme === 'light' }"
            title="浅色"
            aria-label="浅色"
            @click="setTheme('light')"
          >
            <span class="shell__theme-ico" aria-hidden="true">
              <svg
                class="shell__ico"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
              >
                <circle
                  cx="12"
                  cy="12"
                  r="4"
                />
                <path d="M12 2v2m0 16v2M2 12h2m16 0h2M4.93 4.93l1.41 1.41m11.31 11.31l1.41 1.41M19.07 4.93l-1.41 1.41M6.34 17.66l-1.41 1.41" />
              </svg>
            </span>
          </button>
          <button
            type="button"
            :class="{ 'is-on': consolePrefs.theme === 'system' }"
            title="跟随系统"
            aria-label="跟随系统"
            @click="setTheme('system')"
          >
            <span class="shell__theme-ico" aria-hidden="true">
              <svg
                class="shell__ico"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
              >
                <rect
                  x="2"
                  y="3"
                  width="20"
                  height="14"
                  rx="2"
                />
                <path d="M8 21h8M12 17v4" />
              </svg>
            </span>
          </button>
        </div>
        <button
          type="button"
          class="shell__topbar-exit"
          title="退出控制台"
          aria-label="退出控制台"
          @click="exitConsole"
        >
          <svg
            class="shell__ico"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            aria-hidden="true"
          >
            <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
            <polyline points="16 17 21 12 16 7" />
            <line
              x1="21"
              y1="12"
              x2="9"
              y2="12"
            />
          </svg>
        </button>
      </div>
    </header>
    <aside
      class="shell__sidebar"
      :aria-hidden="isNarrow"
    >
      <div class="shell__sidebar-top">
        <div class="shell__brand">
          <img
            class="shell__brand-mark"
            :src="brandMarkUrl"
            alt=""
            width="28"
            height="28"
            decoding="async"
          >
          <div class="shell__brand-main">
            <div class="shell__title">Pallas-Bot</div>
            <div class="shell__version">{{ brandVersionDisplay }}</div>
          </div>
        </div>
      </div>
      <nav class="shell__nav" aria-label="主导航">
        <div
          v-for="item in orderedNav"
          :key="item.to"
          class="shell__nav-item"
          :class="{
            'shell__nav-item--drag-over':
              dragOverPath === item.to && dragPath != null && dragPath !== item.to,
          }"
          @dragover="onNavDragOver(item.to, $event)"
          @dragleave="onNavDragLeave(item.to)"
          @drop="onNavDrop(item.to, $event)"
        >
          <span
            v-if="!isNarrow && !consolePrefs.sidebarCollapsed"
            class="shell__nav-grip"
            draggable="true"
            aria-label="拖动调整顺序"
            title="拖动排序"
            @dragstart="onGripDragStart(item.to, $event)"
            @dragend="onGripDragEnd"
          >⋮</span>
          <RouterLink
            v-slot="{ navigate, isActive, isExactActive }"
            custom
            :to="item.to"
            :end="item.to === '/'"
          >
            <button
              type="button"
              class="shell__nav-link"
              :class="{
                'shell__nav-link--root': item.to === '/',
                'is-router-active': isActive,
                'is-router-exact': isExactActive,
              }"
              :aria-label="navCollapsedLabel(consolePrefs.sidebarCollapsed, item.label)"
              :aria-current="isExactActive ? 'page' : undefined"
              @click="navigate"
            >
              <span class="shell__nav-ico">{{ item.icon }}</span>
              <span class="shell__nav-text">
                <span class="shell__nav-label">{{ item.label }}</span>
                <span class="shell__nav-desc">{{ item.description }}</span>
              </span>
            </button>
          </RouterLink>
        </div>
      </nav>
      <div class="shell__sidebar-bottom">
        <footer class="shell__foot">
          © PallasBot
        </footer>
      </div>
    </aside>

    <Teleport to="body">
      <div
        v-if="isNarrow && mobileNavOpen"
        class="shell-mobile-nav"
      >
        <aside
          id="shell-mobile-nav-panel"
          class="shell-mobile-nav__panel"
          role="dialog"
          aria-modal="true"
          aria-label="主导航"
        >
          <div class="shell-mobile-nav__head">
            <div class="shell-mobile-nav__brand-block">
              <img
                class="shell-mobile-nav__mark"
                :src="brandMarkUrl"
                alt=""
                width="28"
                height="28"
                decoding="async"
              >
              <div class="shell-mobile-nav__brand-text">
                <span class="shell-mobile-nav__brand">Pallas-Bot</span>
                <span class="shell-mobile-nav__ver">{{ brandVersionDisplay }}</span>
              </div>
            </div>
            <button
              type="button"
              class="shell-mobile-nav__close"
              aria-label="关闭菜单"
              @click="closeMobileNav"
            >
              ×
            </button>
          </div>
          <nav class="shell-mobile-nav__links" aria-label="主导航">
            <RouterLink
              v-for="item in orderedNav"
              :key="`m-${item.to}`"
              v-slot="{ navigate, isActive, isExactActive }"
              custom
              :to="item.to"
              :end="item.to === '/'"
            >
              <button
                type="button"
                class="shell-mobile-nav__link"
                :class="{
                  'shell__nav-link--root': item.to === '/',
                  'is-router-active': isActive,
                  'is-router-exact': isExactActive,
                }"
                :aria-current="isExactActive ? 'page' : undefined"
                @click="
                  navigate();
                  closeMobileNav();
                "
              >
                <span class="shell__nav-ico">{{ item.icon }}</span>
                <span class="shell__nav-text">
                  <span class="shell__nav-label">{{ item.label }}</span>
                  <span class="shell__nav-desc">{{ item.description }}</span>
                </span>
              </button>
            </RouterLink>
          </nav>
        </aside>
        <div
          class="shell-mobile-nav__backdrop"
          aria-hidden="true"
          @click="closeMobileNav"
        />
      </div>
    </Teleport>

    <div class="shell__main">
      <div
        v-if="pageLoadingVisible"
        class="shell-page-loading"
        aria-busy="true"
        aria-live="polite"
      >
        <div class="shell-page-loading__card">
          <div
            class="shell-page-loading__spinner"
            aria-hidden="true"
          />
          <p class="shell-page-loading__title">
            加载中
          </p>
          <p class="shell-page-loading__route muted">
            {{ pageLoadingTitle }}
          </p>
        </div>
      </div>
      <div :class="mainInnerClass">
        <router-view v-slot="{ Component, route: r }">
          <transition
            name="shell-page"
            mode="out-in"
          >
            <component
              :is="Component"
              :key="r.path"
            />
          </transition>
        </router-view>
      </div>
    </div>
  </div>
</template>

// react/src/layout/AppShell.tsx
import { useEffect, useMemo, useState } from "react";
import { NavLink, Outlet, useLocation } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import brandMarkAsset from "@pallas-vue/assets/brand-avatar.png?url";
import { fetchHealth } from "@/api/health";
import { MAIN_NAV_ITEMS, sectionIcon } from "@/config/mainNav";
import ConsoleToastHost from "@/components/ConsoleToastHost";
import { cn } from "@/lib/utils";
import { readSidebarCollapsed, writeSidebarCollapsed } from "@/theme/applyShellTheme";

const brandMarkUrl = String(brandMarkAsset);
const SIDEBAR_GROUPS_KEY = "pallas.react.sidebar.groups.collapsed";

function logout() {
  const root = ((import.meta.env.BASE_URL as string) || "/pallas/").replace(/\/$/, "");
  const form = document.createElement("form");
  form.method = "POST";
  form.action = `${root}/logout`;
  form.style.display = "none";
  document.body.appendChild(form);
  form.submit();
}

/** 与 Vue shell 一致：≤860px 走移动顶栏 + 抽屉 */
function useIsShellNarrow(bp = 860) {
  const [narrow, setNarrow] = useState(
    () => typeof window !== "undefined" && window.matchMedia(`(max-width: ${bp}px)`).matches,
  );
  useEffect(() => {
    const mq = window.matchMedia(`(max-width: ${bp}px)`);
    const fn = () => setNarrow(mq.matches);
    mq.addEventListener("change", fn);
    return () => mq.removeEventListener("change", fn);
  }, [bp]);
  return narrow;
}

function navGroups() {
  const groups: { section: string; items: typeof MAIN_NAV_ITEMS }[] = [];
  for (const item of MAIN_NAV_ITEMS) {
    const last = groups[groups.length - 1];
    if (last?.section === item.section) last.items.push(item);
    else groups.push({ section: item.section, items: [item] });
  }
  return groups;
}

function readCollapsedGroups(): Record<string, boolean> {
  try {
    const raw = localStorage.getItem(SIDEBAR_GROUPS_KEY);
    if (!raw) return {};
    const parsed = JSON.parse(raw) as unknown;
    return parsed && typeof parsed === "object" ? (parsed as Record<string, boolean>) : {};
  } catch {
    return {};
  }
}

function isNavActive(pathname: string, to: string): boolean {
  if (to === "/") return pathname === "/";
  if (to === "/ai/home") {
    return (
      pathname === "/ai" ||
      pathname === "/ai/home" ||
      pathname.startsWith("/ai/home/") ||
      pathname === "/ai/statistics" ||
      pathname.startsWith("/ai/statistics/") ||
      pathname === "/ai/history" ||
      pathname.startsWith("/ai/history/")
    );
  }
  if (to === "/ai/wizard") {
    return pathname === "/ai/wizard" || pathname.startsWith("/ai/wizard/");
  }
  if (to === "/ai/config/provider" || to.startsWith("/ai/config/")) {
    return pathname.startsWith("/ai/config");
  }
  if (pathname === to || pathname.startsWith(`${to}/`)) {
    const moreSpecific = MAIN_NAV_ITEMS.some(
      (other) =>
        other.to !== to &&
        other.to.startsWith(`${to}/`) &&
        (pathname === other.to || pathname.startsWith(`${other.to}/`)),
    );
    return !moreSpecific;
  }
  return false;
}

function NavTree({
  onNavigate,
  mobile,
}: {
  onNavigate?: () => void;
  mobile?: boolean;
}) {
  const location = useLocation();
  const groups = useMemo(() => navGroups(), []);
  const [collapsedMap, setCollapsedMap] = useState<Record<string, boolean>>(() => readCollapsedGroups());
  const linkClass = mobile ? "shell-mobile-nav__link" : "shell__nav-link";

  function groupContainsActive(items: typeof MAIN_NAV_ITEMS): boolean {
    return items.some((item) => isNavActive(location.pathname, item.to));
  }

  function isGroupOpen(section: string, items: typeof MAIN_NAV_ITEMS): boolean {
    if (groupContainsActive(items)) return true;
    return !collapsedMap[section];
  }

  function toggleGroup(section: string, items: typeof MAIN_NAV_ITEMS) {
    if (groupContainsActive(items)) return;
    setCollapsedMap((prev) => {
      const next = { ...prev, [section]: !prev[section] };
      try {
        localStorage.setItem(SIDEBAR_GROUPS_KEY, JSON.stringify(next));
      } catch {
        /* ignore */
      }
      return next;
    });
  }

  return (
    <>
      {groups.map((g) => {
        const open = isGroupOpen(g.section, g.items);
        const SectionIcon = sectionIcon(g.section);
        return (
          <div key={g.section} className={cn("shell__nav-group", open && "shell__nav-group--open")}>
            <button
              type="button"
              className={cn(mobile ? "shell-mobile-nav__link shell__nav-group-toggle" : "shell__nav-group-toggle")}
              aria-expanded={open}
              aria-label={`${g.section}菜单`}
              onClick={() => toggleGroup(g.section, g.items)}
            >
              <SectionIcon className="shell__nav-ico" width={18} height={18} aria-hidden />
              <span className="shell__nav-text">
                <span className="shell__nav-label">{g.section}</span>
              </span>
              <span className="shell__nav-group-chevron" aria-hidden="true">
                ›
              </span>
            </button>
            {open ? (
              <div className="shell__nav-group-children">
                {g.items.map((item) => {
                  const Icon = item.icon;
                  const active = isNavActive(location.pathname, item.to);
                  const exact =
                    item.to === "/"
                      ? location.pathname === "/"
                      : item.to.startsWith("/ai/config")
                        ? location.pathname.startsWith("/ai/config")
                        : location.pathname === item.to;
                  return (
                    <div key={item.to} className="shell__nav-item shell__nav-item--child">
                      <NavLink
                        to={item.to}
                        end={item.to === "/"}
                        onClick={onNavigate}
                        className={cn(
                          linkClass,
                          !mobile && "shell__nav-link--child",
                          item.to === "/" && "shell__nav-link--root",
                          ["/logs", "/instances", "/plugins", "/database"].includes(item.to) &&
                            "shell__nav-link--heavy",
                          active && "is-router-active",
                          exact && "is-router-exact",
                        )}
                        aria-current={exact ? "page" : undefined}
                      >
                        <Icon className="shell__nav-ico" width={18} height={18} aria-hidden />
                        <span className="shell__nav-text">
                          <span className="shell__nav-label">{item.label}</span>
                        </span>
                      </NavLink>
                    </div>
                  );
                })}
              </div>
            ) : null}
          </div>
        );
      })}
    </>
  );
}

export default function AppShell() {
  const location = useLocation();
  const isNarrow = useIsShellNarrow();
  const [collapsed, setCollapsed] = useState(() => readSidebarCollapsed());
  const [mobileOpen, setMobileOpen] = useState(false);
  const healthQ = useQuery({ queryKey: ["health"], queryFn: fetchHealth, refetchInterval: 15_000 });

  useEffect(() => setMobileOpen(false), [location.pathname]);

  const connOk = Boolean(healthQ.data?.ok);
  const connText = connOk ? "已连接" : healthQ.isLoading ? "探测中" : "未连接";
  const connCls = connOk
    ? "shell__sidebar-conn--ok"
    : healthQ.isLoading
      ? "shell__sidebar-conn--pending"
      : "shell__sidebar-conn--err";

  function toggleCollapsed() {
    const next = !collapsed;
    setCollapsed(next);
    writeSidebarCollapsed(next);
  }

  const mainMod =
    location.pathname.startsWith("/logs")
      ? "shell__main-inner--logs"
      : location.pathname.startsWith("/plugin-store")
        ? "shell__main-inner--plugin-store"
        : location.pathname === "/"
          ? "shell__main-inner--home"
          : "shell__main-inner--hub";

  return (
    <div className={cn("shell", collapsed && !isNarrow && "shell--sidebar-collapsed")}>
      <div className="shell__bg" aria-hidden />

      {isNarrow ? (
        <div className="shell__mobile-topbar">
          <button
            type="button"
            className="shell__mobile-topbar-btn"
            aria-label="打开菜单"
            onClick={() => setMobileOpen(true)}
          >
            <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden>
              <path d="M4 7h16M4 12h16M4 17h16" />
            </svg>
          </button>
          <div className="shell__mobile-topbar-brand">
            <img className="shell__mobile-topbar-mark" src={brandMarkUrl} alt="" width={28} height={28} />
            <span className="shell__mobile-topbar-title">Pallas Bot</span>
          </div>
          <span className="shell__mobile-topbar-version">r{__WEBUI_VERSION__}</span>
        </div>
      ) : null}

      <aside className="shell__sidebar" aria-hidden={isNarrow || undefined}>
        <div className={cn("shell__sidebar-top", collapsed && !isNarrow && "shell__sidebar-top--collapsed")}>
          {collapsed && !isNarrow ? (
            <>
              <div className="shell__brand-slot shell__brand-slot--avatar">
                <div className="shell__brand-mark-wrap">
                  <img className="shell__brand-mark" src={brandMarkUrl} alt="" width={44} height={44} decoding="async" />
                </div>
                <span className={cn("shell__sidebar-conn shell__sidebar-conn--brand shell__sidebar-conn--collapsed-dot", connCls)} aria-label={connText}>
                  {connText}
                </span>
              </div>
              <div className="shell__brand-slot shell__brand-slot--expand">
                <button type="button" className="shell__brand-collapse shell__brand-expand" aria-label="展开菜单栏" onClick={toggleCollapsed}>
                  <svg className="shell__brand-collapse-ico" viewBox="0 0 24 24" width="18" height="18" aria-hidden>
                    <path fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" d="M5 5v14M10 8l4 4-4 4M19 5v14" />
                  </svg>
                </button>
              </div>
            </>
          ) : (
            <div className="shell__brand">
              <div className="shell__brand-mark-wrap">
                <img className="shell__brand-mark" src={brandMarkUrl} alt="" width={44} height={44} decoding="async" />
              </div>
              <div className="shell__brand-main">
                <div className="shell__brand-title-row">
                  <div className="shell__title">PBWebUI</div>
                  <span className="shell__brand-badge" title="控制台资源版本">
                    r{__WEBUI_VERSION__}
                  </span>
                </div>
                <div className="shell__brand-meta">
                  <span className={cn("shell__sidebar-conn shell__sidebar-conn--brand", connCls)}>{connText}</span>
                </div>
              </div>
              {!isNarrow ? (
                <button type="button" className="shell__brand-collapse shell__brand-collapse--edge" aria-label="收起菜单栏" onClick={toggleCollapsed}>
                  <svg className="shell__brand-collapse-ico" viewBox="0 0 24 24" width="18" height="18" aria-hidden>
                    <path fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" d="M5 5v14M14 8l-4 4 4 4M19 5v14" />
                  </svg>
                </button>
              ) : null}
            </div>
          )}
        </div>

        <nav className="shell__nav" aria-label="主导航">
          <NavTree />
        </nav>

        <div className="shell__sidebar-tools">
          <button type="button" className="shell__sidebar-exit" title="退出控制台" aria-label="退出控制台" onClick={logout}>
            <svg className="shell__ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden>
              <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
              <polyline points="16 17 21 12 16 7" />
              <line x1="21" y1="12" x2="9" y2="12" />
            </svg>
            <span className="shell__sidebar-exit-label">退出</span>
          </button>
        </div>

        <div className="shell__sidebar-bottom">
          <footer className="shell__foot">
            <div className="shell__foot-copy">© PallasBot</div>
          </footer>
        </div>
      </aside>

      {isNarrow && mobileOpen ? (
        <div className="shell-mobile-nav">
          <aside className="shell-mobile-nav__panel" role="dialog" aria-modal="true" aria-label="主导航">
            <div className="shell-mobile-nav__head">
              <div className="shell-mobile-nav__brand-block">
                <div className="shell__brand-mark-wrap">
                  <img className="shell__brand-mark" src={brandMarkUrl} alt="" width={44} height={44} />
                </div>
                <div className="shell-mobile-nav__brand-text">
                  <div className="shell__brand-title-row">
                    <span className="shell-mobile-nav__brand">PBWebUI</span>
                    <span className="shell__brand-badge">r{__WEBUI_VERSION__}</span>
                  </div>
                  <div className="shell__brand-meta shell__brand-meta--mobile">
                    <span className={cn("shell__sidebar-conn shell__sidebar-conn--brand", connCls)}>{connText}</span>
                  </div>
                </div>
              </div>
              <button type="button" className="shell-mobile-nav__close" aria-label="关闭菜单" onClick={() => setMobileOpen(false)}>
                ×
              </button>
            </div>
            <nav className="shell-mobile-nav__links" aria-label="主导航">
              <NavTree mobile onNavigate={() => setMobileOpen(false)} />
            </nav>
            <div className="shell-mobile-nav__foot">
              <button type="button" className="shell__sidebar-exit" onClick={logout}>
                <span className="shell__sidebar-exit-label">退出控制台</span>
              </button>
            </div>
          </aside>
          <button type="button" className="shell-mobile-nav__backdrop" aria-label="关闭菜单" onClick={() => setMobileOpen(false)} />
        </div>
      ) : null}

      <div className="shell__main">
        <div className={cn("shell__main-inner", mainMod)}>
          <Outlet />
        </div>
      </div>
      <ConsoleToastHost />
    </div>
  );
}
