// src/components/social/UserSocialConfigModal.tsx
import { useEffect, useState } from "react";
import { axiosErrorDetail } from "@/api/http";
import { fetchUserConfigById, putUserConfig } from "@/api/fullConsole";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

type Props = {
  open: boolean;
  userId: number | null;
  userNickname?: string;
  defaultBanned?: boolean;
  onOpenChange: (open: boolean) => void;
  onSaved?: () => void;
};

/** 用户颗粒配置：shadcn Dialog，标题左对齐。 */
export default function UserSocialConfigModal({
  open,
  userId,
  userNickname,
  defaultBanned,
  onOpenChange,
  onSaved,
}: Props) {
  const [banned, setBanned] = useState(false);
  const [loadBusy, setLoadBusy] = useState(false);
  const [saveBusy, setSaveBusy] = useState(false);
  const [loadErr, setLoadErr] = useState("");
  const [saveErr, setSaveErr] = useState("");
  const [loadedId, setLoadedId] = useState<number | null>(null);

  useEffect(() => {
    if (!open) {
      setLoadErr("");
      setSaveErr("");
      setLoadedId(null);
      return;
    }
    const uid = userId;
    if (uid == null || !Number.isFinite(uid) || uid < 1) {
      setLoadErr("无效用户 QQ。");
      return;
    }
    let cancelled = false;
    setLoadBusy(true);
    setLoadErr("");
    setSaveErr("");
    void fetchUserConfigById(uid)
      .then((u) => {
        if (cancelled) return;
        setLoadedId(u.user_id);
        setBanned(defaultBanned ? true : Boolean(u.banned));
      })
      .catch((e) => {
        if (!cancelled) setLoadErr(axiosErrorDetail(e));
      })
      .finally(() => {
        if (!cancelled) setLoadBusy(false);
      });
    return () => {
      cancelled = true;
    };
  }, [open, userId, defaultBanned]);

  async function save() {
    if (loadedId == null || saveBusy) return;
    setSaveBusy(true);
    setSaveErr("");
    try {
      await putUserConfig(loadedId, { banned });
      onSaved?.();
      onOpenChange(false);
    } catch (e) {
      setSaveErr(axiosErrorDetail(e));
    } finally {
      setSaveBusy(false);
    }
  }

  const busy = loadBusy || saveBusy;

  return (
    <Dialog
      open={open}
      onOpenChange={(next) => {
        if (!next && !busy) onOpenChange(false);
      }}
    >
      <DialogContent
        className="social-config-dialog social-config-dialog--sm flex max-h-[min(92vh,480px)] w-[min(420px,96vw)] max-w-[min(420px,96vw)] gap-0 overflow-hidden bg-card p-0"
        onEscapeKeyDown={(e) => {
          if (busy) e.preventDefault();
        }}
        onPointerDownOutside={(e) => {
          if (busy) e.preventDefault();
        }}
      >
        <DialogHeader className="border-b border-[color-mix(in_srgb,var(--border)_70%,transparent)] px-4 py-3 text-left">
          <DialogTitle id="user-social-config-title">
            {defaultBanned ? "添加用户封禁" : "编辑用户颗粒配置"}
          </DialogTitle>
          <DialogDescription className="muted">
            QQ {loadedId ?? userId ?? "—"}
            {userNickname?.trim() ? ` · ${userNickname.trim()}` : ""}
          </DialogDescription>
        </DialogHeader>

        <div className="min-h-0 flex-1 overflow-auto px-4 py-3">
          {loadBusy ? <p className="muted">加载中…</p> : null}
          {loadErr ? <p className="alert alert--err">{loadErr}</p> : null}
          {!loadBusy && !loadErr && loadedId != null ? (
            <div className="social-config-dialog__body">
              {saveErr ? <p className="alert alert--err">{saveErr}</p> : null}
              <div className="social-config-dialog__row">
                <span>封禁</span>
                <Select value={banned ? "1" : "0"} onValueChange={(v) => setBanned(v === "1")}>
                  <SelectTrigger className="h-9 w-auto min-w-[5rem]" aria-label="封禁">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="1">是</SelectItem>
                    <SelectItem value="0">否</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
          ) : null}
        </div>

        {!loadBusy && !loadErr && loadedId != null ? (
          <DialogFooter className="border-t border-[color-mix(in_srgb,var(--border)_70%,transparent)] px-4 py-3 sm:justify-end">
            <Button type="button" variant="outline" size="sm" disabled={saveBusy} onClick={() => onOpenChange(false)}>
              取消
            </Button>
            <Button type="button" size="sm" disabled={saveBusy} onClick={() => void save()}>
              {saveBusy ? "保存中…" : "保存"}
            </Button>
          </DialogFooter>
        ) : null}
      </DialogContent>
    </Dialog>
  );
}

// src/components/social/UserSocialConfigModal.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { fetchUserConfigById, putUserConfig } from "@/api/consoleApi";
import type { UserConfigPublic } from "@/api/pallasTypes";
import UiDialog from "@/components/ui/UiDialog.vue";
import FormBoolSwitchField from "@/components/config/FormBoolSwitchField.vue";
import { useSaveHotkey } from "@/composables/useSaveHotkey";
import { toastApiError, toastSaveSuccess } from "@/utils/consoleToastFeedback";

const open = defineModel<boolean>("open", { default: false });
const props = defineProps<{
  userId: number | null;
  /** 好友昵称（好友列表传入；数据库页无昵称时可省略） */
  userNickname?: string;
  /** 打开弹窗时封禁下拉默认选「是」（数据库页添加封禁用户） */
  defaultBanned?: boolean;
}>();

const subtitleUserNickname = computed(() => props.userNickname?.trim() ?? "");

const emit = defineEmits<{
  saved: [];
}>();

const userCfg = ref<UserConfigPublic | null>(null);
const userDraft = ref<{ banned: boolean } | null>(null);
const loadBusy = ref(false);
const saveBusy = ref(false);
const loadErr = ref("");
const saveErr = ref("");

function resetState() {
  userCfg.value = null;
  userDraft.value = null;
  loadErr.value = "";
  saveErr.value = "";
}

function close() {
  open.value = false;
}

async function loadConfig() {
  const uid = props.userId;
  if (uid == null || !Number.isFinite(uid) || uid < 1) {
    loadErr.value = "无效用户 QQ。";
    return;
  }
  loadBusy.value = true;
  loadErr.value = "";
  resetState();
  try {
    const u = await fetchUserConfigById(uid);
    userCfg.value = u;
    userDraft.value = { banned: props.defaultBanned ? true : u.banned };
    saveErr.value = "";
  } catch (e) {
    loadErr.value = e instanceof Error ? e.message : String(e);
    userCfg.value = null;
    userDraft.value = null;
  } finally {
    loadBusy.value = false;
  }
}

async function save() {
  if (!userCfg.value || !userDraft.value) return;
  saveBusy.value = true;
  saveErr.value = "";
  try {
    const u = await putUserConfig(userCfg.value.user_id, { banned: userDraft.value.banned });
    userCfg.value = u;
    userDraft.value = { banned: u.banned };
    emit("saved");
    close();
    toastSaveSuccess("用户配置已保存");
  } catch (e) {
    saveErr.value = e instanceof Error ? e.message : String(e);
    toastApiError(e, "保存失败");
  } finally {
    saveBusy.value = false;
  }
}

useSaveHotkey(
  () => open.value && Boolean(userDraft.value) && !saveBusy.value && !loadBusy.value,
  () => save(),
  { lifecycle: "mount" },
);

watch(
  () => open.value,
  (isOpen) => {
    if (isOpen) void loadConfig();
    else resetState();
  },
);

watch(
  () => props.userId,
  () => {
    if (open.value) void loadConfig();
  },
);
</script>

<template>
  <UiDialog
    :open="open"
    title-id="user-policy-modal-title"
    @close="close"
  >
    <template #header>
      <div class="console-modal__head-text">
        <h2
          id="user-policy-modal-title"
          class="console-modal__title"
        >
          {{ defaultBanned ? "添加用户封禁" : "编辑用户颗粒配置" }}
        </h2>
        <p class="console-modal__subtitle">
          <span
            v-if="userCfg"
            class="console-modal__subtitle-strong"
          >QQ {{ userCfg.user_id }}</span>
          <span
            v-else-if="userId"
            class="console-modal__subtitle-strong"
          >QQ {{ userId }}</span>
          <span
            v-if="subtitleUserNickname"
            class="muted"
          > · {{ subtitleUserNickname }}</span>
        </p>
      </div>
      <button
        type="button"
        class="console-modal__close"
        aria-label="关闭"
        @click="close"
      >
        ×
      </button>
    </template>
          <p
            v-if="loadBusy"
            class="muted"
            style="margin: 0"
          >
            加载中…
          </p>
          <p
            v-else-if="loadErr"
            class="alert alert--err"
          >
            {{ loadErr }}
          </p>
          <div
            v-else-if="userCfg && userDraft"
            class="bot-config-edit bot-config-edit--modal"
          >
            <p
              v-if="saveErr"
              class="alert alert--err"
              style="margin-bottom: 12px"
            >
              {{ saveErr }}
            </p>
            <FormBoolSwitchField
              label="封禁"
              label-style="yesno"
              :model-value="userDraft.banned"
              @update:model-value="userDraft.banned = $event"
            />
            <div class="row-actions">
              <button
                type="button"
                class="btn btn--primary"
                :disabled="saveBusy"
                @click="save"
              >
                {{ saveBusy ? "保存中…" : "保存" }}
              </button>
              <button
                type="button"
                class="btn"
                :disabled="saveBusy"
                @click="close"
              >
                取消
              </button>
            </div>
          </div>
  </UiDialog>
</template>
