// src/components/ui/UiBadge.vue
<script setup lang="ts">
export type UiBadgeVariant = "default" | "secondary" | "outline" | "ok" | "warn" | "muted" | "destructive";

withDefaults(
  defineProps<{
    variant?: UiBadgeVariant;
  }>(),
  {
    variant: "secondary",
  },
);
</script>

<template>
  <span
    class="ui-badge"
    :class="`ui-badge--${variant}`"
  >
    <slot />
  </span>
</template>

// react/src/components/ui/UiBadge.tsx
import type { HTMLAttributes, ReactNode } from "react";
import { cn } from "@/lib/utils";

export type UiBadgeVariant =
  | "default"
  | "secondary"
  | "outline"
  | "ok"
  | "warn"
  | "muted"
  | "destructive";

type Props = HTMLAttributes<HTMLSpanElement> & {
  variant?: UiBadgeVariant;
  children: ReactNode;
};

export default function UiBadge({ variant = "secondary", className, children, ...rest }: Props) {
  return (
    <span {...rest} className={cn("ui-badge", `ui-badge--${variant}`, className)}>
      {children}
    </span>
  );
}
