// react/src/pages/ChartsPage.tsx
import { useEffect, useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import {
  fetchConsoleDailyStats,
  fetchInstances,
  fetchPluginRunStats,
} from "@/api/fullConsole";
import type { BotConfigPublic, ConsoleDailyStatRow } from "@pallas-vue/api/pallasTypes";
import ChartsDailyBarChart from "@/components/ChartsDailyBarChart";
import ChartsMonthlyCommandChart from "@/components/ChartsMonthlyCommandChart";
import HomePluginRunCharts from "@/components/HomePluginRunCharts";
import IngressDispatchPanel from "@/components/IngressDispatchPanel";
import PageHeader from "@/components/PageHeader";
import Panel from "@/components/Panel";
import RefreshIconButton from "@/components/RefreshIconButton";
import StatTrendCard from "@/components/StatTrendCard";
import UiInput from "@/components/ui/UiInput";
import UiSelect from "@/components/ui/UiSelect";
import { useAccountPluginCharts } from "@/hooks/useAccountPluginCharts";
import {
  currentMonthIso,
  fillDailyRows,
  monthBounds,
  readSavedHomeAccount,
  todayIso,
  writeSavedHomeAccount,
} from "@/utils/chartsPageHelpers";

export default function ChartsPage() {
  const [rangeStart, setRangeStart] = useState(() => monthBounds(currentMonthIso()).start);
  const [rangeEnd, setRangeEnd] = useState(todayIso);
  const [selectedAccount, setSelectedAccount] = useState<number | null>(() => readSavedHomeAccount());

  const instQ = useQuery({ queryKey: ["instances"], queryFn: () => fetchInstances() });
  const pluginRunGlobalQ = useQuery({ queryKey: ["plugin-run-stats-global"], queryFn: () => fetchPluginRunStats() });

  const queryRange = useMemo(() => {
    const bounds = monthBounds(currentMonthIso());
    const start = rangeStart || bounds.start;
    const end = rangeEnd || todayIso();
    return start <= end ? { start, end } : { start: end, end: start };
  }, [rangeEnd, rangeStart]);

  const dailyRangeQ = useQuery({
    queryKey: ["console-daily-stats-range", queryRange.start, queryRange.end, selectedAccount],
    queryFn: () =>
      fetchConsoleDailyStats({
        start: queryRange.start,
        end: queryRange.end,
        ...(selectedAccount != null ? { selfId: selectedAccount } : {}),
      }),
    enabled: selectedAccount != null,
  });

  const {
    pluginsList,
    chartsBusy,
    pluginRunTimeSamples,
    scopedPluginPlugins,
    scopedApiCallsByApi,
    scopedMatcherRunsByPlugin,
    scopedMatcherErrorsByPlugin,
    scopedMatcherAvgDurationByPlugin,
    scopedMatcherDurationMsByPlugin,
    scopedMatcherDurationLog,
    scopedMatcherErrorLog,
    scopedPluginRunRow,
    scopedBotStatsRow,
    pluginRunStatsScoped,
    consoleDailyStats,
    accountMessageStats,
    refreshChartStats,
    ensurePluginsList,
  } = useAccountPluginCharts(selectedAccount);

  useEffect(() => {
    void ensurePluginsList();
  }, [ensurePluginsList]);

  useEffect(() => {
    void instQ.refetch();
    void pluginRunGlobalQ.refetch();
    void refreshChartStats();
  }, [refreshChartStats]);

  const sortedBots = useMemo(() => {
    const rows = [...((instQ.data?.db_bot_configs || []) as BotConfigPublic[])];
    const nick = (account: number) =>
      instQ.data?.bot_profiles?.[String(account)]?.nickname?.trim() || "";
    rows.sort((a, b) => {
      const cmp = nick(a.account).localeCompare(nick(b.account), "zh-CN");
      return cmp !== 0 ? cmp : a.account - b.account;
    });
    return rows;
  }, [instQ.data]);

  useEffect(() => {
    if (!sortedBots.length) {
      setSelectedAccount(null);
      return;
    }
    if (selectedAccount != null && sortedBots.some((r) => r.account === selectedAccount)) return;
    setSelectedAccount(sortedBots[0]!.account);
  }, [sortedBots, selectedAccount]);

  useEffect(() => {
    writeSavedHomeAccount(selectedAccount);
  }, [selectedAccount]);

  const dailyRowsScoped = useMemo((): ConsoleDailyStatRow[] => {
    const src = dailyRangeQ.data?.rows ?? consoleDailyStats?.rows ?? [];
    return [...src].sort((a, b) => a.date.localeCompare(b.date));
  }, [consoleDailyStats?.rows, dailyRangeQ.data?.rows]);

  const monthlyDailyRows = useMemo(() => {
    if (selectedAccount == null) return [] as ConsoleDailyStatRow[];
    return fillDailyRows(dailyRowsScoped, queryRange.start, queryRange.end, String(selectedAccount));
  }, [dailyRowsScoped, queryRange.end, queryRange.start, selectedAccount]);

  const rangeCommandPoints = useMemo(
    () => dailyRowsScoped.map((r) => ({ date: r.date, value: r.matcher_runs })),
    [dailyRowsScoped],
  );
  const rangeApiPoints = useMemo(
    () => dailyRowsScoped.map((r) => ({ date: r.date, value: r.api_calls ?? 0 })),
    [dailyRowsScoped],
  );

  const pluginRunMain = pluginRunStatsScoped ?? pluginRunGlobalQ.data;

  const accountTodayMsg = scopedBotStatsRow
    ? `${scopedBotStatsRow.today_received ?? "—"} / ${scopedBotStatsRow.today_sent ?? "—"}`
    : "—";
  const accountTodayApi = (() => {
    const n = scopedBotStatsRow?.today_api_calls;
    if (n == null || !Number.isFinite(Number(n))) return "—";
    return String(Math.floor(Number(n)));
  })();
  const accountMatcherRuns = (() => {
    const n = scopedPluginRunRow?.runs_today;
    if (n == null || !Number.isFinite(Number(n))) return "—";
    return String(Math.floor(Number(n)));
  })();
  const accountMatcherErrors = (() => {
    const n = scopedPluginRunRow?.errors_today;
    if (n == null || !Number.isFinite(Number(n))) return "—";
    return String(Math.floor(Number(n)));
  })();

  const msgSparkValues = useMemo((): number[] => {
    const intraday =
      scopedBotStatsRow?.message_traffic_history?.map((p) => p.received + p.sent) ?? [];
    if (intraday.length >= 2) return intraday;
    const rows = [...(consoleDailyStats?.rows ?? [])]
      .sort((a, b) => a.date.localeCompare(b.date))
      .slice(-14);
    return rows.map((r) => r.received + r.sent);
  }, [consoleDailyStats?.rows, scopedBotStatsRow]);

  const apiSparkValues = useMemo((): number[] => {
    const api = scopedBotStatsRow?.api_calls_history?.map((p) => p.total) ?? [];
    return api.length >= 2 ? api : [];
  }, [scopedBotStatsRow]);

  const matcherSparkValues = useMemo((): number[] => {
    const series = scopedMatcherRunsByPlugin;
    if (!series.length) return [];
    const maxLen = Math.max(...series.map((s) => s.points.length));
    if (maxLen < 2) return [];
    const out = new Array<number>(maxLen).fill(0);
    for (const s of series) {
      for (let i = 0; i < s.points.length; i++) {
        out[i] += Number(s.points[i]?.total) || 0;
      }
    }
    return out;
  }, [scopedMatcherRunsByPlugin]);

  const rangeBusy = dailyRangeQ.isFetching;
  const refreshing = instQ.isFetching || pluginRunGlobalQ.isFetching || chartsBusy || rangeBusy;
  const commandTotal = rangeCommandPoints.reduce((s, p) => s + p.value, 0);
  const dashboardReady = !chartsBusy;

  async function refreshAll() {
    await Promise.all([
      instQ.refetch(),
      pluginRunGlobalQ.refetch(),
      dailyRangeQ.refetch(),
      refreshChartStats(),
    ]);
  }

  return (
    <div className="console-hub-page charts-page charts-page--dashboard">
      <PageHeader
        title="数据看板"
        description="流量编排、月度命令、API、LLM 与详细图表；悬停各图可查看明细。"
        className="charts-page__masthead"
        actions={
          <div className="charts-page__masthead-tools">
            {sortedBots.length > 1 ? (
              <label className="charts-page__account-label charts-page__account-label--masthead">
                <span className="charts-page__account-label-text">账号</span>
                <UiSelect
                  className="charts-page__account-sel"
                  aria-label="选择 Bot 账号"
                  value={selectedAccount != null ? String(selectedAccount) : ""}
                  onValueChange={(v) => setSelectedAccount(Number(v) || null)}
                >
                  {sortedBots.map((b) => {
                    const nick = instQ.data?.bot_profiles?.[String(b.account)]?.nickname?.trim() || "BOT";
                    return (
                      <option key={b.account} value={b.account}>
                        {nick} · {b.account}
                      </option>
                    );
                  })}
                </UiSelect>
              </label>
            ) : null}
            <RefreshIconButton
              embedded
              busy={refreshing}
              label="刷新"
              showLabel
              onClick={() => void refreshAll()}
            />
          </div>
        }
      />

      <div className="charts-page__ingress">
        <IngressDispatchPanel />
      </div>

      {sortedBots.length ? (
        <div className="charts-page__filter-toolbar">
          <div className="charts-page__filter-group">
            <label className="charts-page__date-label">
              <span className="charts-page__date-label-text">起始</span>
              <UiInput
                className="charts-page__date-inp"
                type="date"
                aria-label="起始日期"
                value={rangeStart}
                onValueChange={setRangeStart}
              />
            </label>
            <label className="charts-page__date-label">
              <span className="charts-page__date-label-text">结束</span>
              <UiInput
                className="charts-page__date-inp"
                type="date"
                aria-label="结束日期"
                value={rangeEnd}
                onValueChange={setRangeEnd}
              />
            </label>
          </div>
        </div>
      ) : (
        <p className="muted charts-page__empty">数据库中暂无 Bot 配置。请先在「数据库实例」创建账号。</p>
      )}

      {selectedAccount != null ? (
        <div className="charts-page__layout">
          <div className="charts-page__main" aria-busy={refreshing || undefined}>
            <section id="charts-monthly" className="charts-page__section">
              <Panel className="charts-page__panel" title="月度命令统计">
                <p className="muted charts-page__section-lead">
                  按自然日汇总（磁盘持久化）；左轴为发送/接收消息，右轴为 Matcher 与协议 API。鼠标悬停查看每日明细。
                </p>
                <ChartsMonthlyCommandChart
                  rows={monthlyDailyRows}
                  busy={rangeBusy || chartsBusy}
                  emptyText="所选区间暂无持久化数据，请保持 Bot 运行并跨日写入。"
                />
              </Panel>
            </section>

            <section id="charts-commands" className="charts-page__section">
              <Panel className="charts-page__panel" title="命令使用量">
                <ChartsDailyBarChart points={rangeCommandPoints} title="Matcher" unit="次" accent="#d946ef" />
                {rangeCommandPoints.length ? (
                  <dl className="home-dl charts-page__summary-dl">
                    <dt>区间合计</dt>
                    <dd>{commandTotal.toLocaleString()} 次</dd>
                    <dt>日均</dt>
                    <dd>
                      {Math.round(commandTotal / Math.max(1, rangeCommandPoints.length)).toLocaleString()} 次
                    </dd>
                  </dl>
                ) : null}
              </Panel>
            </section>

            <section id="charts-api" className="charts-page__section">
              <Panel className="charts-page__panel" title="API 使用量">
                <ChartsDailyBarChart
                  points={rangeApiPoints}
                  title="协议 API 调用"
                  unit="次"
                  accent="#38bdf8"
                  emptyText="所选区间暂无 API 按日落盘数据；新版起随 console_daily_stats 一并持久化。"
                />
                <p className="muted charts-page__section-note">
                  今日实时曲线见下方「详细图表」中的协议 API 桶图；此处为按自然日汇总。
                </p>
              </Panel>
            </section>

            <section id="charts-detail" className="charts-page__section charts-page__section--detail">
              <section className="charts-page__kpi">
                <StatTrendCard
                  dense
                  label="今日消息"
                  value={accountTodayMsg}
                  hint="收 / 发 · 当前账号"
                  sparkValues={msgSparkValues}
                  chartVariant="msg"
                />
                <StatTrendCard
                  dense
                  label="协议 API"
                  value={accountTodayApi}
                  hint="今日成功调用 · 当前账号"
                  sparkValues={apiSparkValues}
                  chartVariant="api"
                />
                <StatTrendCard
                  dense
                  label="Matcher"
                  value={accountMatcherRuns}
                  hint={`今日执行 · 异常 ${accountMatcherErrors}`}
                  sparkValues={matcherSparkValues}
                  chartVariant="matcher"
                />
              </section>

              <div className="charts-page__board">
                <HomePluginRunCharts
                  layoutMode="dashboard"
                  plugins={scopedPluginPlugins}
                  pluginsMeta={pluginsList}
                  series={pluginRunTimeSamples}
                  busy={chartsBusy}
                  apiHistoryByApi={scopedApiCallsByApi}
                  apiHistoryBucketSec={accountMessageStats?.api_calls_history_bucket_sec}
                  matcherRunsByPlugin={scopedMatcherRunsByPlugin}
                  matcherErrorsByPlugin={scopedMatcherErrorsByPlugin}
                  matcherAvgDurationMsByPlugin={scopedMatcherAvgDurationByPlugin}
                  matcherDurationMsByPlugin={scopedMatcherDurationMsByPlugin}
                  matcherDurationLog={scopedMatcherDurationLog}
                  matcherDurationLogCap={scopedPluginRunRow?.matcher_duration_log_cap ?? 150}
                  matcherDurationLogPerPluginCap={scopedPluginRunRow?.matcher_duration_log_per_plugin_cap ?? 30}
                  matcherHistoryBucketSec={pluginRunMain?.matcher_calls_history_bucket_sec}
                  matcherErrorsToday={scopedPluginRunRow?.errors_today ?? 0}
                  matcherErrorLog={scopedMatcherErrorLog}
                  dailyStatRows={consoleDailyStats?.rows ?? []}
                />
                {dashboardReady && !msgSparkValues.length && !apiSparkValues.length ? (
                  <p className="muted charts-page__board-note">
                    部分曲线需进程运行一段时间后才有时间桶数据；按日汇总图依赖历史落盘。
                  </p>
                ) : null}
              </div>
            </section>
          </div>
        </div>
      ) : null}
    </div>
  );
}

// src/pages/ChartsPage.vue
<script setup lang="ts">
import ConsoleNavIcon from "@/components/ConsoleNavIcon.vue";
import { computed, defineAsyncComponent, onActivated, onMounted, ref, watch } from "vue";
import {
  fetchConsoleDailyStats,
  fetchInstances,
  fetchPluginRunStats,
  peekInstancesCache,
} from "@/api/consoleApi";
import type {
  BotConfigPublic,
  ConsoleDailyStatRow,
  ConsoleDailyStatsData,
  InstancesData,
} from "@/api/pallasTypes";
import ChartsDailyBarChart from "@/components/ChartsDailyBarChart.vue";
import ChartsMonthlyCommandChart from "@/components/ChartsMonthlyCommandChart.vue";
import ConsolePageSkeleton from "@/components/ConsolePageSkeleton.vue";
import PageChrome from "@/components/PageChrome.vue";
import RefreshIconButton from "@/components/RefreshIconButton.vue";
import StatTrendCard from "@/components/StatTrendCard.vue";
import UiCard from "@/components/ui/UiCard.vue";
import UiInput from "@/components/ui/UiInput.vue";

const IngressDispatchPanel = defineAsyncComponent(() => import("@/components/IngressDispatchPanel.vue"));
const HomePluginRunCharts = defineAsyncComponent(() => import("@/components/HomePluginRunCharts.vue"));
import {
  readSavedHomeAccount,
  useAccountPluginCharts,
  writeSavedHomeAccount,
} from "@/composables/useAccountPluginCharts";
import { usePanelNavIcon } from "@/composables/usePanelNavIcon";

const panelNavIcon = usePanelNavIcon();
const warmInstances = peekInstancesCache();
const pageReady = ref(Boolean(warmInstances));
const err = ref("");
const instances = ref<InstancesData | null>(warmInstances);
const dailyStatsRange = ref<ConsoleDailyStatsData | null>(null);
const rangeBusy = ref(false);

const selectedAccount = ref<number | null>(readSavedHomeAccount());
const pluginRunGlobal = ref<Awaited<ReturnType<typeof fetchPluginRunStats>> | null>(null);

function todayIso(): string {
  const d = new Date();
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

function currentMonthIso(): string {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
}

const rangeStart = ref("");
const rangeEnd = ref(todayIso());

const {
  pluginsList,
  chartsBusy,
  pluginRunTimeSamples,
  scopedPluginPlugins,
  scopedApiCallsByApi,
  scopedMatcherRunsByPlugin,
  scopedMatcherErrorsByPlugin,
  scopedMatcherAvgDurationByPlugin,
  scopedMatcherDurationMsByPlugin,
  scopedMatcherDurationLog,
  scopedMatcherErrorLog,
  scopedPluginRunRow,
  scopedBotStatsRow,
  pluginRunStatsScoped,
  consoleDailyStats,
  accountMessageStats,
  refreshChartStats,
  ensurePluginsList,
} = useAccountPluginCharts(selectedAccount);

function dbNick(account: number): string {
  return instances.value?.bot_profiles?.[String(account)]?.nickname?.trim() || "";
}

const sortedBots = computed(() => {
  const rows = [...(instances.value?.db_bot_configs ?? [])];
  rows.sort((a, b) => {
    const na = dbNick(a.account).toLowerCase();
    const nb = dbNick(b.account).toLowerCase();
    const cmp = na.localeCompare(nb, "zh-CN");
    if (cmp !== 0) return cmp;
    return a.account - b.account;
  });
  return rows;
});

function botLabel(row: BotConfigPublic): string {
  return dbNick(row.account) || "BOT";
}

function ensureSelectedBot() {
  const rows = sortedBots.value;
  if (!rows.length) {
    selectedAccount.value = null;
    return;
  }
  const cur = selectedAccount.value;
  if (cur != null && rows.some((r) => r.account === cur)) return;
  selectedAccount.value = rows[0]?.account ?? null;
}

watch(selectedAccount, (acc) => {
  writeSavedHomeAccount(acc);
});

function monthBounds(month: string): { start: string; end: string } {
  const [y, m] = month.split("-").map((x) => Number(x));
  if (!y || !m) {
    const t = todayIso();
    return { start: t, end: t };
  }
  const last = new Date(y, m, 0).getDate();
  const mm = String(m).padStart(2, "0");
  return {
    start: `${y}-${mm}-01`,
    end: `${y}-${mm}-${String(last).padStart(2, "0")}`,
  };
}

function daysInRange(start: string, end: string): string[] {
  const out: string[] = [];
  const cur = new Date(`${start}T00:00:00`);
  const endD = new Date(`${end}T00:00:00`);
  if (Number.isNaN(cur.getTime()) || Number.isNaN(endD.getTime())) return out;
  while (cur <= endD) {
    const y = cur.getFullYear();
    const m = String(cur.getMonth() + 1).padStart(2, "0");
    const d = String(cur.getDate()).padStart(2, "0");
    out.push(`${y}-${m}-${d}`);
    cur.setDate(cur.getDate() + 1);
  }
  return out;
}

const queryRange = computed((): { start: string; end: string } => {
  const bounds = monthBounds(currentMonthIso());
  const start = rangeStart.value || bounds.start;
  const end = rangeEnd.value || todayIso();
  return start <= end ? { start, end } : { start: end, end: start };
});

const dailyRowsScoped = computed((): ConsoleDailyStatRow[] => {
  const src = dailyStatsRange.value?.rows ?? consoleDailyStats.value?.rows ?? [];
  return [...src].sort((a, b) => a.date.localeCompare(b.date));
});

const dailyByDate = computed(() => {
  const map = new Map<string, ConsoleDailyStatRow>();
  for (const row of dailyRowsScoped.value) {
    map.set(row.date, row);
  }
  return map;
});

const monthlyDailyRows = computed((): ConsoleDailyStatRow[] => {
  const { start, end } = queryRange.value;
  const days = daysInRange(start, end);
  const selfId = selectedAccount.value != null ? String(selectedAccount.value) : "";
  return days.map((date) => {
    const row = dailyByDate.value.get(date);
    if (row) return row;
    return {
      date,
      self_id: selfId,
      received: 0,
      sent: 0,
      matcher_runs: 0,
      api_calls: 0,
    };
  });
});

const rangeCommandPoints = computed(() =>
  dailyRowsScoped.value.map((r) => ({
    date: r.date,
    value: r.matcher_runs,
  })),
);

const rangeApiPoints = computed(() =>
  dailyRowsScoped.value.map((r) => ({
    date: r.date,
    value: r.api_calls ?? 0,
  })),
);

const pluginRunMain = computed(() => pluginRunStatsScoped.value ?? pluginRunGlobal.value);

const accountTodayMsg = computed(() => {
  const b = scopedBotStatsRow.value;
  if (!b) return "—";
  return `${b.today_received ?? "—"} / ${b.today_sent ?? "—"}`;
});

const accountTodayApi = computed(() => {
  const n = scopedBotStatsRow.value?.today_api_calls;
  if (n == null || !Number.isFinite(Number(n))) return "—";
  return String(Math.floor(Number(n)));
});

const accountMatcherRuns = computed(() => {
  const n = scopedPluginRunRow.value?.runs_today;
  if (n == null || !Number.isFinite(Number(n))) return "—";
  return String(Math.floor(Number(n)));
});

const accountMatcherErrors = computed(() => {
  const n = scopedPluginRunRow.value?.errors_today;
  if (n == null || !Number.isFinite(Number(n))) return "—";
  return String(Math.floor(Number(n)));
});

const msgSparkValues = computed((): number[] => {
  const intraday =
    scopedBotStatsRow.value?.message_traffic_history?.map((p) => p.received + p.sent) ?? [];
  if (intraday.length >= 2) return intraday;
  const rows = [...(consoleDailyStats.value?.rows ?? [])]
    .sort((a, b) => a.date.localeCompare(b.date))
    .slice(-14);
  return rows.map((r) => r.received + r.sent);
});

const apiSparkValues = computed((): number[] => {
  const api = scopedBotStatsRow.value?.api_calls_history?.map((p) => p.total) ?? [];
  return api.length >= 2 ? api : [];
});

const matcherSparkValues = computed((): number[] => {
  const series = scopedMatcherRunsByPlugin.value;
  if (!series.length) return [];
  const maxLen = Math.max(...series.map((s) => s.points.length));
  if (maxLen < 2) return [];
  const out = new Array<number>(maxLen).fill(0);
  for (const s of series) {
    for (let i = 0; i < s.points.length; i++) {
      out[i] += Number(s.points[i]?.total) || 0;
    }
  }
  return out;
});

const dashboardReady = computed(() => pageReady.value && !chartsBusy.value);

async function loadDailyRange() {
  const acc = selectedAccount.value;
  if (acc == null) {
    dailyStatsRange.value = null;
    return;
  }
  const { start, end } = queryRange.value;
  rangeBusy.value = true;
  try {
    dailyStatsRange.value = await fetchConsoleDailyStats({ selfId: acc, start, end });
  } catch {
    dailyStatsRange.value = null;
  } finally {
    rangeBusy.value = false;
  }
}

async function loadRangeData() {
  await loadDailyRange();
}

async function load(opts?: { bypassCache?: boolean }) {
  err.value = "";
  const bypassCache = opts?.bypassCache === true;
  try {
    await Promise.all([
      fetchInstances(bypassCache ? { bypassCache: true } : undefined).then((d) => {
        instances.value = d;
      }),
      ensurePluginsList(),
      fetchPluginRunStats(undefined, undefined, bypassCache ? { bypassCache: true } : undefined)
        .then((d) => {
          pluginRunGlobal.value = d;
        })
        .catch(() => {
          pluginRunGlobal.value = null;
        }),
      refreshChartStats(),
    ]);
    ensureSelectedBot();
    pageReady.value = true;
    void loadRangeData();
  } catch (e) {
    err.value = e instanceof Error ? e.message : String(e);
    pageReady.value = true;
  }
}

async function refreshAll() {
  await Promise.all([
    load({ bypassCache: true }),
    loadRangeData(),
  ]);
}

watch([selectedAccount, rangeStart, rangeEnd], () => {
  if (!pageReady.value) return;
  void loadRangeData();
});

onMounted(() => {
  const bounds = monthBounds(currentMonthIso());
  rangeStart.value = bounds.start;
  rangeEnd.value = bounds.end;
  if (warmInstances) ensureSelectedBot();
  void load();
});

onActivated(() => {
  const warm = peekInstancesCache();
  if (warm) instances.value = warm;
  if (!pageReady.value) return;
  void load();
});
</script>

<template>
  <div class="console-hub-page charts-page charts-page--dashboard">
    <div
      v-if="err"
      class="alert alert--err"
    >
      {{ err }}
    </div>

    <ConsolePageSkeleton
      v-if="!pageReady"
      :panels="3"
    />

    <template v-else>
      <PageChrome
        :icon="panelNavIcon"
        chrome-class="charts-page__masthead"
        title="数据看板"
        lead="流量编排、月度命令、API、LLM 与详细图表；悬停各图可查看明细。"
      >
        <template #actions>
          <div class="charts-page__masthead-tools">
            <label
              v-if="sortedBots.length > 1"
              class="charts-page__account-label charts-page__account-label--masthead"
            >
              <span class="charts-page__account-label-text">账号</span>
              <select
                v-model.number="selectedAccount"
                class="sel charts-page__account-sel"
                aria-label="选择 Bot 账号"
              >
                <option
                  v-for="b in sortedBots"
                  :key="b.account"
                  :value="b.account"
                >
                  {{ botLabel(b) }} · {{ b.account }}
                </option>
              </select>
            </label>
            <RefreshIconButton
              embedded
              :busy="chartsBusy || rangeBusy"
              label="刷新"
              @click="refreshAll"
            />
          </div>
        </template>
      </PageChrome>

      <IngressDispatchPanel class="charts-page__ingress" />

      <div
        v-if="sortedBots.length"
        class="charts-page__filter-toolbar"
      >
        <div class="charts-page__filter-group">
          <label class="charts-page__date-label">
            <span class="charts-page__date-label-text">起始</span>
            <UiInput
              v-model="rangeStart"
              class="charts-page__date-inp"
              type="date"
              aria-label="起始日期"
            />
          </label>
          <label class="charts-page__date-label">
            <span class="charts-page__date-label-text">结束</span>
            <UiInput
              v-model="rangeEnd"
              class="charts-page__date-inp"
              type="date"
              aria-label="结束日期"
            />
          </label>
        </div>
      </div>

      <p
        v-if="!sortedBots.length"
        class="muted charts-page__empty"
      >
        数据库中暂无 Bot 配置。请先在「数据库实例」创建账号。
      </p>

      <div
        v-else-if="selectedAccount != null"
        class="charts-page__layout"
      >
        <div
          class="charts-page__main"
          :aria-busy="rangeBusy || chartsBusy || undefined"
        >
          <section
            id="charts-monthly"
            class="charts-page__section"
          >
            <UiCard
              tag="div"
              glass
              class="charts-page__panel"
            >
              <div class="panel__hd">
                <h2 class="panel__title">
                  <ConsoleNavIcon
                    class="panel__title-ico"
                    name="charts"
                  />月度命令统计
                </h2>
              </div>
              <div class="panel__bd">
                <p class="muted charts-page__section-lead">
                  按自然日汇总（磁盘持久化）；左轴为发送/接收消息，右轴为 Matcher 与协议 API。鼠标悬停查看每日明细。
                </p>
                <ChartsMonthlyCommandChart
                  :rows="monthlyDailyRows"
                  :busy="rangeBusy || chartsBusy"
                  empty-text="所选区间暂无持久化数据，请保持 Bot 运行并跨日写入。"
                />
              </div>
            </UiCard>
          </section>

          <section
            id="charts-commands"
            class="charts-page__section"
          >
            <UiCard
              tag="div"
              glass
              class="charts-page__panel"
            >
              <div class="panel__hd">
                <h2 class="panel__title">
                  <ConsoleNavIcon
                    class="panel__title-ico"
                    name="terminal"
                  />命令使用量
                </h2>
              </div>
              <div class="panel__bd">
                <ChartsDailyBarChart
                  :points="rangeCommandPoints"
                  title="Matcher"
                  unit="次"
                  accent="#d946ef"
                />
                <dl
                  v-if="rangeCommandPoints.length"
                  class="home-dl charts-page__summary-dl"
                >
                  <dt>区间合计</dt>
                  <dd>{{ rangeCommandPoints.reduce((s, p) => s + p.value, 0).toLocaleString() }} 次</dd>
                  <dt>日均</dt>
                  <dd>{{
                    Math.round(
                      rangeCommandPoints.reduce((s, p) => s + p.value, 0) / Math.max(1, rangeCommandPoints.length),
                    ).toLocaleString()
                  }} 次</dd>
                </dl>
              </div>
            </UiCard>
          </section>

          <section
            id="charts-api"
            class="charts-page__section"
          >
            <UiCard
              tag="div"
              glass
              class="charts-page__panel"
            >
              <div class="panel__hd">
                <h2 class="panel__title">
                  <ConsoleNavIcon
                    class="panel__title-ico"
                    name="swap"
                  />API 使用量
                </h2>
              </div>
              <div class="panel__bd">
                <ChartsDailyBarChart
                  :points="rangeApiPoints"
                  title="协议 API 调用"
                  unit="次"
                  accent="#38bdf8"
                  empty-text="所选区间暂无 API 按日落盘数据；新版起随 console_daily_stats 一并持久化。"
                />
                <p class="muted charts-page__section-note">
                  今日实时曲线见下方「详细图表」中的协议 API 桶图；此处为按自然日汇总。
                </p>
              </div>
            </UiCard>
          </section>

          <section
            id="charts-detail"
            class="charts-page__section charts-page__section--detail"
          >
            <section class="charts-page__kpi">
              <StatTrendCard
                dense
                label="今日消息"
                :value="accountTodayMsg"
                hint="收 / 发 · 当前账号"
                :spark-values="msgSparkValues"
                chart-variant="msg"
              />
              <StatTrendCard
                dense
                label="协议 API"
                :value="accountTodayApi"
                hint="今日成功调用 · 当前账号"
                :spark-values="apiSparkValues"
                chart-variant="api"
              />
              <StatTrendCard
                dense
                label="Matcher"
                :value="accountMatcherRuns"
                :hint="`今日执行 · 异常 ${accountMatcherErrors}`"
                :spark-values="matcherSparkValues"
                chart-variant="matcher"
              />
            </section>
            <div class="charts-page__board">
              <HomePluginRunCharts
                layout-mode="dashboard"
                :plugins="scopedPluginPlugins"
                :plugins-meta="pluginsList"
                :series="pluginRunTimeSamples"
                :busy="chartsBusy"
                :api-history-by-api="scopedApiCallsByApi"
                :api-history-bucket-sec="accountMessageStats?.api_calls_history_bucket_sec"
                :matcher-runs-by-plugin="scopedMatcherRunsByPlugin"
                :matcher-errors-by-plugin="scopedMatcherErrorsByPlugin"
                :matcher-avg-duration-ms-by-plugin="scopedMatcherAvgDurationByPlugin"
                :matcher-duration-ms-by-plugin="scopedMatcherDurationMsByPlugin"
                :matcher-duration-log="scopedMatcherDurationLog"
                :matcher-duration-log-cap="scopedPluginRunRow?.matcher_duration_log_cap ?? 150"
                :matcher-duration-log-per-plugin-cap="scopedPluginRunRow?.matcher_duration_log_per_plugin_cap ?? 30"
                :matcher-history-bucket-sec="pluginRunMain?.matcher_calls_history_bucket_sec"
                :matcher-errors-today="scopedPluginRunRow?.errors_today ?? 0"
                :matcher-error-log="scopedMatcherErrorLog"
                :daily-stat-rows="consoleDailyStats?.rows ?? []"
              />
              <p
                v-if="dashboardReady && !msgSparkValues.length && !apiSparkValues.length"
                class="muted charts-page__board-note"
              >
                部分曲线需进程运行一段时间后才有时间桶数据；按日汇总图依赖历史落盘。
              </p>
            </div>
          </section>
        </div>
      </div>
    </template>
  </div>
</template>
