// src/pages/ChartsPage.vue
<script setup lang="ts">
import ConsoleNavIcon from "@/components/ConsoleNavIcon.vue";
import { computed, defineAsyncComponent, onActivated, onMounted, ref, watch } from "vue";
import {
  fetchConsoleDailyStats,
  fetchInstances,
  fetchPluginRunStats,
  peekInstancesCache,
} from "@/api/consoleApi";
import type {
  BotConfigPublic,
  ConsoleDailyStatRow,
  ConsoleDailyStatsData,
  InstancesData,
} from "@/api/pallasTypes";
import ChartsDailyBarChart from "@/components/ChartsDailyBarChart.vue";
import ChartsMonthlyCommandChart from "@/components/ChartsMonthlyCommandChart.vue";
import ConsolePageSkeleton from "@/components/ConsolePageSkeleton.vue";
import PageChrome from "@/components/PageChrome.vue";
import RefreshIconButton from "@/components/RefreshIconButton.vue";
import StatTrendCard from "@/components/StatTrendCard.vue";
import UiCard from "@/components/ui/UiCard.vue";
import UiInput from "@/components/ui/UiInput.vue";

const IngressDispatchPanel = defineAsyncComponent(() => import("@/components/IngressDispatchPanel.vue"));
const HomePluginRunCharts = defineAsyncComponent(() => import("@/components/HomePluginRunCharts.vue"));
import {
  readSavedHomeAccount,
  useAccountPluginCharts,
  writeSavedHomeAccount,
} from "@/composables/useAccountPluginCharts";
import { usePanelNavIcon } from "@/composables/usePanelNavIcon";

const panelNavIcon = usePanelNavIcon();
const warmInstances = peekInstancesCache();
const pageReady = ref(Boolean(warmInstances));
const err = ref("");
const instances = ref<InstancesData | null>(warmInstances);
const dailyStatsRange = ref<ConsoleDailyStatsData | null>(null);
const rangeBusy = ref(false);

const selectedAccount = ref<number | null>(readSavedHomeAccount());
const pluginRunGlobal = ref<Awaited<ReturnType<typeof fetchPluginRunStats>> | null>(null);

function todayIso(): string {
  const d = new Date();
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

function currentMonthIso(): string {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
}

const rangeStart = ref("");
const rangeEnd = ref(todayIso());

const {
  pluginsList,
  chartsBusy,
  pluginRunTimeSamples,
  scopedPluginPlugins,
  scopedApiCallsByApi,
  scopedMatcherRunsByPlugin,
  scopedMatcherErrorsByPlugin,
  scopedMatcherAvgDurationByPlugin,
  scopedMatcherDurationMsByPlugin,
  scopedMatcherDurationLog,
  scopedMatcherErrorLog,
  scopedPluginRunRow,
  scopedBotStatsRow,
  pluginRunStatsScoped,
  consoleDailyStats,
  accountMessageStats,
  refreshChartStats,
  ensurePluginsList,
} = useAccountPluginCharts(selectedAccount);

function dbNick(account: number): string {
  return instances.value?.bot_profiles?.[String(account)]?.nickname?.trim() || "";
}

const sortedBots = computed(() => {
  const rows = [...(instances.value?.db_bot_configs ?? [])];
  rows.sort((a, b) => {
    const na = dbNick(a.account).toLowerCase();
    const nb = dbNick(b.account).toLowerCase();
    const cmp = na.localeCompare(nb, "zh-CN");
    if (cmp !== 0) return cmp;
    return a.account - b.account;
  });
  return rows;
});

function botLabel(row: BotConfigPublic): string {
  return dbNick(row.account) || "BOT";
}

function ensureSelectedBot() {
  const rows = sortedBots.value;
  if (!rows.length) {
    selectedAccount.value = null;
    return;
  }
  const cur = selectedAccount.value;
  if (cur != null && rows.some((r) => r.account === cur)) return;
  selectedAccount.value = rows[0]?.account ?? null;
}

watch(selectedAccount, (acc) => {
  writeSavedHomeAccount(acc);
});

function monthBounds(month: string): { start: string; end: string } {
  const [y, m] = month.split("-").map((x) => Number(x));
  if (!y || !m) {
    const t = todayIso();
    return { start: t, end: t };
  }
  const last = new Date(y, m, 0).getDate();
  const mm = String(m).padStart(2, "0");
  return {
    start: `${y}-${mm}-01`,
    end: `${y}-${mm}-${String(last).padStart(2, "0")}`,
  };
}

function daysInRange(start: string, end: string): string[] {
  const out: string[] = [];
  const cur = new Date(`${start}T00:00:00`);
  const endD = new Date(`${end}T00:00:00`);
  if (Number.isNaN(cur.getTime()) || Number.isNaN(endD.getTime())) return out;
  while (cur <= endD) {
    const y = cur.getFullYear();
    const m = String(cur.getMonth() + 1).padStart(2, "0");
    const d = String(cur.getDate()).padStart(2, "0");
    out.push(`${y}-${m}-${d}`);
    cur.setDate(cur.getDate() + 1);
  }
  return out;
}

const queryRange = computed((): { start: string; end: string } => {
  const bounds = monthBounds(currentMonthIso());
  const start = rangeStart.value || bounds.start;
  const end = rangeEnd.value || todayIso();
  return start <= end ? { start, end } : { start: end, end: start };
});

const dailyRowsScoped = computed((): ConsoleDailyStatRow[] => {
  const src = dailyStatsRange.value?.rows ?? consoleDailyStats.value?.rows ?? [];
  return [...src].sort((a, b) => a.date.localeCompare(b.date));
});

const dailyByDate = computed(() => {
  const map = new Map<string, ConsoleDailyStatRow>();
  for (const row of dailyRowsScoped.value) {
    map.set(row.date, row);
  }
  return map;
});

const monthlyDailyRows = computed((): ConsoleDailyStatRow[] => {
  const { start, end } = queryRange.value;
  const days = daysInRange(start, end);
  const selfId = selectedAccount.value != null ? String(selectedAccount.value) : "";
  return days.map((date) => {
    const row = dailyByDate.value.get(date);
    if (row) return row;
    return {
      date,
      self_id: selfId,
      received: 0,
      sent: 0,
      matcher_runs: 0,
      api_calls: 0,
    };
  });
});

const rangeCommandPoints = computed(() =>
  dailyRowsScoped.value.map((r) => ({
    date: r.date,
    value: r.matcher_runs,
  })),
);

const rangeApiPoints = computed(() =>
  dailyRowsScoped.value.map((r) => ({
    date: r.date,
    value: r.api_calls ?? 0,
  })),
);

const pluginRunMain = computed(() => pluginRunStatsScoped.value ?? pluginRunGlobal.value);

const accountTodayMsg = computed(() => {
  const b = scopedBotStatsRow.value;
  if (!b) return "—";
  return `${b.today_received ?? "—"} / ${b.today_sent ?? "—"}`;
});

const accountTodayApi = computed(() => {
  const n = scopedBotStatsRow.value?.today_api_calls;
  if (n == null || !Number.isFinite(Number(n))) return "—";
  return String(Math.floor(Number(n)));
});

const accountMatcherRuns = computed(() => {
  const n = scopedPluginRunRow.value?.runs_today;
  if (n == null || !Number.isFinite(Number(n))) return "—";
  return String(Math.floor(Number(n)));
});

const accountMatcherErrors = computed(() => {
  const n = scopedPluginRunRow.value?.errors_today;
  if (n == null || !Number.isFinite(Number(n))) return "—";
  return String(Math.floor(Number(n)));
});

const msgSparkValues = computed((): number[] => {
  const intraday =
    scopedBotStatsRow.value?.message_traffic_history?.map((p) => p.received + p.sent) ?? [];
  if (intraday.length >= 2) return intraday;
  const rows = [...(consoleDailyStats.value?.rows ?? [])]
    .sort((a, b) => a.date.localeCompare(b.date))
    .slice(-14);
  return rows.map((r) => r.received + r.sent);
});

const apiSparkValues = computed((): number[] => {
  const api = scopedBotStatsRow.value?.api_calls_history?.map((p) => p.total) ?? [];
  return api.length >= 2 ? api : [];
});

const matcherSparkValues = computed((): number[] => {
  const series = scopedMatcherRunsByPlugin.value;
  if (!series.length) return [];
  const maxLen = Math.max(...series.map((s) => s.points.length));
  if (maxLen < 2) return [];
  const out = new Array<number>(maxLen).fill(0);
  for (const s of series) {
    for (let i = 0; i < s.points.length; i++) {
      out[i] += Number(s.points[i]?.total) || 0;
    }
  }
  return out;
});

const dashboardReady = computed(() => pageReady.value && !chartsBusy.value);

async function loadDailyRange() {
  const acc = selectedAccount.value;
  if (acc == null) {
    dailyStatsRange.value = null;
    return;
  }
  const { start, end } = queryRange.value;
  rangeBusy.value = true;
  try {
    dailyStatsRange.value = await fetchConsoleDailyStats({ selfId: acc, start, end });
  } catch {
    dailyStatsRange.value = null;
  } finally {
    rangeBusy.value = false;
  }
}

async function loadRangeData() {
  await loadDailyRange();
}

async function load(opts?: { bypassCache?: boolean }) {
  err.value = "";
  const bypassCache = opts?.bypassCache === true;
  try {
    await Promise.all([
      fetchInstances(bypassCache ? { bypassCache: true } : undefined).then((d) => {
        instances.value = d;
      }),
      ensurePluginsList(),
      fetchPluginRunStats(undefined, undefined, bypassCache ? { bypassCache: true } : undefined)
        .then((d) => {
          pluginRunGlobal.value = d;
        })
        .catch(() => {
          pluginRunGlobal.value = null;
        }),
      refreshChartStats(),
    ]);
    ensureSelectedBot();
    pageReady.value = true;
    void loadRangeData();
  } catch (e) {
    err.value = e instanceof Error ? e.message : String(e);
    pageReady.value = true;
  }
}

async function refreshAll() {
  await Promise.all([
    load({ bypassCache: true }),
    loadRangeData(),
  ]);
}

watch([selectedAccount, rangeStart, rangeEnd], () => {
  if (!pageReady.value) return;
  void loadRangeData();
});

onMounted(() => {
  const bounds = monthBounds(currentMonthIso());
  rangeStart.value = bounds.start;
  rangeEnd.value = bounds.end;
  if (warmInstances) ensureSelectedBot();
  void load();
});

onActivated(() => {
  const warm = peekInstancesCache();
  if (warm) instances.value = warm;
  if (!pageReady.value) return;
  void load();
});
</script>

<template>
  <div class="console-hub-page charts-page charts-page--dashboard">
    <div
      v-if="err"
      class="alert alert--err"
    >
      {{ err }}
    </div>

    <ConsolePageSkeleton
      v-if="!pageReady"
      :panels="3"
    />

    <template v-else>
      <PageChrome
        :icon="panelNavIcon"
        chrome-class="charts-page__masthead"
        title="数据看板"
        lead="流量编排、月度命令、API、LLM 与详细图表；悬停各图可查看明细。"
      >
        <template #actions>
          <div class="charts-page__masthead-tools">
            <label
              v-if="sortedBots.length > 1"
              class="charts-page__account-label charts-page__account-label--masthead"
            >
              <span class="charts-page__account-label-text">账号</span>
              <select
                v-model.number="selectedAccount"
                class="sel charts-page__account-sel"
                aria-label="选择 Bot 账号"
              >
                <option
                  v-for="b in sortedBots"
                  :key="b.account"
                  :value="b.account"
                >
                  {{ botLabel(b) }} · {{ b.account }}
                </option>
              </select>
            </label>
            <RefreshIconButton
              embedded
              :busy="chartsBusy || rangeBusy"
              label="刷新"
              @click="refreshAll"
            />
          </div>
        </template>
      </PageChrome>

      <IngressDispatchPanel class="charts-page__ingress" />

      <div
        v-if="sortedBots.length"
        class="charts-page__filter-toolbar"
      >
        <div class="charts-page__filter-group">
          <label class="charts-page__date-label">
            <span class="charts-page__date-label-text">起始</span>
            <UiInput
              v-model="rangeStart"
              class="charts-page__date-inp"
              type="date"
              aria-label="起始日期"
            />
          </label>
          <label class="charts-page__date-label">
            <span class="charts-page__date-label-text">结束</span>
            <UiInput
              v-model="rangeEnd"
              class="charts-page__date-inp"
              type="date"
              aria-label="结束日期"
            />
          </label>
        </div>
      </div>

      <p
        v-if="!sortedBots.length"
        class="muted charts-page__empty"
      >
        数据库中暂无 Bot 配置。请先在「数据库实例」创建账号。
      </p>

      <div
        v-else-if="selectedAccount != null"
        class="charts-page__layout"
      >
        <div
          class="charts-page__main"
          :aria-busy="rangeBusy || chartsBusy || undefined"
        >
          <section
            id="charts-monthly"
            class="charts-page__section"
          >
            <UiCard
              tag="div"
              glass
              class="charts-page__panel"
            >
              <div class="panel__hd">
                <h2 class="panel__title">
                  <ConsoleNavIcon
                    class="panel__title-ico"
                    name="charts"
                  />月度命令统计
                </h2>
              </div>
              <div class="panel__bd">
                <p class="muted charts-page__section-lead">
                  按自然日汇总（磁盘持久化）；左轴为发送/接收消息，右轴为 Matcher 与协议 API。鼠标悬停查看每日明细。
                </p>
                <ChartsMonthlyCommandChart
                  :rows="monthlyDailyRows"
                  :busy="rangeBusy || chartsBusy"
                  empty-text="所选区间暂无持久化数据，请保持 Bot 运行并跨日写入。"
                />
              </div>
            </UiCard>
          </section>

          <section
            id="charts-commands"
            class="charts-page__section"
          >
            <UiCard
              tag="div"
              glass
              class="charts-page__panel"
            >
              <div class="panel__hd">
                <h2 class="panel__title">
                  <ConsoleNavIcon
                    class="panel__title-ico"
                    name="terminal"
                  />命令使用量
                </h2>
              </div>
              <div class="panel__bd">
                <ChartsDailyBarChart
                  :points="rangeCommandPoints"
                  title="Matcher"
                  unit="次"
                  accent="#d946ef"
                />
                <dl
                  v-if="rangeCommandPoints.length"
                  class="home-dl charts-page__summary-dl"
                >
                  <dt>区间合计</dt>
                  <dd>{{ rangeCommandPoints.reduce((s, p) => s + p.value, 0).toLocaleString() }} 次</dd>
                  <dt>日均</dt>
                  <dd>{{
                    Math.round(
                      rangeCommandPoints.reduce((s, p) => s + p.value, 0) / Math.max(1, rangeCommandPoints.length),
                    ).toLocaleString()
                  }} 次</dd>
                </dl>
              </div>
            </UiCard>
          </section>

          <section
            id="charts-api"
            class="charts-page__section"
          >
            <UiCard
              tag="div"
              glass
              class="charts-page__panel"
            >
              <div class="panel__hd">
                <h2 class="panel__title">
                  <ConsoleNavIcon
                    class="panel__title-ico"
                    name="swap"
                  />API 使用量
                </h2>
              </div>
              <div class="panel__bd">
                <ChartsDailyBarChart
                  :points="rangeApiPoints"
                  title="协议 API 调用"
                  unit="次"
                  accent="#38bdf8"
                  empty-text="所选区间暂无 API 按日落盘数据；新版起随 console_daily_stats 一并持久化。"
                />
                <p class="muted charts-page__section-note">
                  今日实时曲线见下方「详细图表」中的协议 API 桶图；此处为按自然日汇总。
                </p>
              </div>
            </UiCard>
          </section>

          <section
            id="charts-detail"
            class="charts-page__section charts-page__section--detail"
          >
            <section class="charts-page__kpi">
              <StatTrendCard
                dense
                label="今日消息"
                :value="accountTodayMsg"
                hint="收 / 发 · 当前账号"
                :spark-values="msgSparkValues"
                chart-variant="msg"
              />
              <StatTrendCard
                dense
                label="协议 API"
                :value="accountTodayApi"
                hint="今日成功调用 · 当前账号"
                :spark-values="apiSparkValues"
                chart-variant="api"
              />
              <StatTrendCard
                dense
                label="Matcher"
                :value="accountMatcherRuns"
                :hint="`今日执行 · 异常 ${accountMatcherErrors}`"
                :spark-values="matcherSparkValues"
                chart-variant="matcher"
              />
            </section>
            <div class="charts-page__board">
              <HomePluginRunCharts
                layout-mode="dashboard"
                :plugins="scopedPluginPlugins"
                :plugins-meta="pluginsList"
                :series="pluginRunTimeSamples"
                :busy="chartsBusy"
                :api-history-by-api="scopedApiCallsByApi"
                :api-history-bucket-sec="accountMessageStats?.api_calls_history_bucket_sec"
                :matcher-runs-by-plugin="scopedMatcherRunsByPlugin"
                :matcher-errors-by-plugin="scopedMatcherErrorsByPlugin"
                :matcher-avg-duration-ms-by-plugin="scopedMatcherAvgDurationByPlugin"
                :matcher-duration-ms-by-plugin="scopedMatcherDurationMsByPlugin"
                :matcher-duration-log="scopedMatcherDurationLog"
                :matcher-duration-log-cap="scopedPluginRunRow?.matcher_duration_log_cap ?? 150"
                :matcher-duration-log-per-plugin-cap="scopedPluginRunRow?.matcher_duration_log_per_plugin_cap ?? 30"
                :matcher-history-bucket-sec="pluginRunMain?.matcher_calls_history_bucket_sec"
                :matcher-errors-today="scopedPluginRunRow?.errors_today ?? 0"
                :matcher-error-log="scopedMatcherErrorLog"
                :daily-stat-rows="consoleDailyStats?.rows ?? []"
              />
              <p
                v-if="dashboardReady && !msgSparkValues.length && !apiSparkValues.length"
                class="muted charts-page__board-note"
              >
                部分曲线需进程运行一段时间后才有时间桶数据；按日汇总图依赖历史落盘。
              </p>
            </div>
          </section>
        </div>
      </div>
    </template>
  </div>
</template>

// src/pages/ChartsPage.tsx
import { useEffect, useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useSearchParams } from "react-router-dom";
import { Activity, BarChart3, Bot, LineChart, UsersRound } from "lucide-react";
import PanelTitleIcon from "@/components/PanelTitleIcon";
import {
  fetchConsoleDailyStats,
  fetchInstances,
  fetchPluginRunStats,
} from "@/api/fullConsole";
import type { BotConfigPublic, ConsoleDailyStatRow } from "@/api/pallasTypes";
import ChartsHorizontalRankBars from "@/components/ChartsHorizontalRankBars";
import ChartsMonthlyCommandChart from "@/components/ChartsMonthlyCommandChart";
import ChartsNamedSeriesTrend from "@/components/ChartsNamedSeriesTrend";
import ChartsPluginFilter from "@/components/ChartsPluginFilter";
import ChromeField from "@/components/ChromeField";
import ChromeTools, { CHROME_TOOLS_TRAILING } from "@/components/ChromeTools";
import ConsolePageSkeleton from "@/components/ConsolePageSkeleton";
import DateModeFilter, { type DateMode } from "@/components/DateModeFilter";
import PageMasthead from "@/components/PageMasthead";
import RefreshIconButton from "@/components/RefreshIconButton";
import BotSelectLabel from "@/components/BotSelectLabel";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useAccountPluginCharts } from "@/hooks/useAccountPluginCharts";
import { useBotFavorites } from "@/hooks/useBotFavorites";
import { cn } from "@/lib/utils";
import { botAccountFavoriteRank, botSelectDropdownLabel } from "@/utils/botDisplay";
import {
  currentMonthIso,
  fillDailyRows,
  monthBounds,
  parseBotAccountId,
  readSavedHomeAccount,
  todayIso,
  writeSavedHomeAccount,
} from "@/utils/chartsPageHelpers";
import {
  readChartsPluginFilter,
  resolveDisplayedPlugins,
  writeChartsPluginFilter,
  type ChartsPluginFilterScope,
  type ChartsPluginFilterState,
} from "@/utils/chartsPluginFilter";
import { matcherPluginDisplayName } from "@/utils/pluginDisplayLabel";
import type { NamedSeriesInput } from "@/utils/namedSeriesTrend";

const CHART_PANEL = "charts-page__panel flex flex-col overflow-hidden shadow-none";
const CHART_PANEL_HD =
  "panel__hd panel__hd--split home-page__panel-hd-nowrap flex-row items-center justify-between space-y-0 border-b px-4 py-3";
const CHART_PANEL_BD = "panel__bd space-y-3 px-4 pb-4 pt-3";
const ACCOUNT_SEL =
  "bot-acct-sel charts-page__account-sel h-8 w-[9rem] min-w-[7.5rem] max-w-[9rem] shrink-0 overflow-hidden";
/** 与区间趋势 Matcher 序列同色，柱图不跟主题走 */
const PLUGIN_TODAY_BAR_ACCENT = "#7c3aed";

function MetricTile({
  label,
  value,
  hint,
}: {
  label: string;
  value: string;
  hint?: string;
}) {
  return (
    <div className="metric-tile">
      <div className="metric-tile__head">
        <span className="metric-tile__label">{label}</span>
      </div>
      <div className="metric-tile__value-slot">
        <span className="metric-tile__value metric-tile__value--inline">{value}</span>
        {hint ? <span className="metric-tile__hint muted">{hint}</span> : null}
      </div>
    </div>
  );
}

export default function ChartsPage() {
  const [searchParams, setSearchParams] = useSearchParams();
  const accountFromQuery = parseBotAccountId(searchParams.get("self_id"));
  const [rangeStart, setRangeStart] = useState(() => monthBounds(currentMonthIso()).start);
  const [rangeEnd, setRangeEnd] = useState(todayIso);
  const [dateMode, setDateMode] = useState<DateMode>("range");
  const [selectedAccount, setSelectedAccount] = useState<number | null>(
    () => accountFromQuery ?? readSavedHomeAccount(),
  );
  const [rankFilterOpen, setRankFilterOpen] = useState(false);
  const [matcherFilterOpen, setMatcherFilterOpen] = useState(false);
  const [rankFilter, setRankFilter] = useState<ChartsPluginFilterState>(() =>
    readChartsPluginFilter(accountFromQuery ?? readSavedHomeAccount(), "rank"),
  );
  const [matcherFilter, setMatcherFilter] = useState<ChartsPluginFilterState>(() =>
    readChartsPluginFilter(accountFromQuery ?? readSavedHomeAccount(), "matcher"),
  );

  function selectAccount(next: number | null) {
    setSelectedAccount(next);
    if (searchParams.has("self_id")) {
      const nextParams = new URLSearchParams(searchParams);
      nextParams.delete("self_id");
      setSearchParams(nextParams, { replace: true });
    }
  }

  const { favorites } = useBotFavorites();
  const instQ = useQuery({ queryKey: ["instances"], queryFn: () => fetchInstances() });
  const pluginRunGlobalQ = useQuery({ queryKey: ["plugin-run-stats-global"], queryFn: () => fetchPluginRunStats() });

  const queryRange = useMemo(() => {
    const bounds = monthBounds(currentMonthIso());
    const start = rangeStart || bounds.start;
    const end = rangeEnd || todayIso();
    return start <= end ? { start, end } : { start: end, end: start };
  }, [rangeEnd, rangeStart]);

  const dailyRangeQ = useQuery({
    queryKey: ["console-daily-stats-range", queryRange.start, queryRange.end, selectedAccount],
    queryFn: () =>
      fetchConsoleDailyStats({
        start: queryRange.start,
        end: queryRange.end,
        ...(selectedAccount != null ? { selfId: selectedAccount } : {}),
      }),
    enabled: selectedAccount != null,
  });

  const {
    pluginsList,
    chartsBusy,
    scopedPluginPlugins,
    scopedMatcherRunsByPlugin,
    scopedPluginRunRow,
    scopedBotStatsRow,
    consoleDailyStats,
    refreshChartStats,
    ensurePluginsList,
  } = useAccountPluginCharts(selectedAccount);

  useEffect(() => {
    void ensurePluginsList();
  }, [ensurePluginsList]);

  const sortedBots = useMemo(() => {
    const rows = [...((instQ.data?.db_bot_configs || []) as BotConfigPublic[])];
    const nick = (account: number) =>
      instQ.data?.bot_profiles?.[String(account)]?.nickname?.trim() || "";
    rows.sort((a, b) => {
      const fa = botAccountFavoriteRank(favorites, a.account);
      const fb = botAccountFavoriteRank(favorites, b.account);
      if (fa !== fb) return fb - fa;
      const cmp = nick(a.account).localeCompare(nick(b.account), "zh-CN");
      return cmp !== 0 ? cmp : a.account - b.account;
    });
    return rows;
  }, [favorites, instQ.data]);

  const instancesPending = instQ.isPending && !instQ.data;
  const botsResolved = instQ.isFetched;

  useEffect(() => {
    // 实例列表未返回前不要当成「无 Bot」，否则会闪「未配置」并打断已选账号的图表请求
    if (!botsResolved) return;
    if (!sortedBots.length) {
      setSelectedAccount(null);
      return;
    }
    const inList = (acc: number | null) =>
      acc != null && sortedBots.some((r) => r.account === acc);
    // 优先 URL（仪表盘跳转）→ 当前选择 → 与仪表盘共用的本地记忆 → 列表第一项
    if (inList(accountFromQuery)) {
      if (selectedAccount !== accountFromQuery) setSelectedAccount(accountFromQuery);
      return;
    }
    if (inList(selectedAccount)) return;
    const saved = readSavedHomeAccount();
    if (inList(saved)) {
      setSelectedAccount(saved);
      return;
    }
    setSelectedAccount(sortedBots[0]!.account);
  }, [accountFromQuery, botsResolved, sortedBots, selectedAccount]);

  useEffect(() => {
    // 列表未就绪时不要把仪表盘已选账号写成 null
    if (selectedAccount != null) writeSavedHomeAccount(selectedAccount);
    else if (botsResolved && !sortedBots.length) writeSavedHomeAccount(null);
    setRankFilter(readChartsPluginFilter(selectedAccount, "rank"));
    setMatcherFilter(readChartsPluginFilter(selectedAccount, "matcher"));
  }, [botsResolved, selectedAccount, sortedBots.length]);

  const dailyRowsScoped = useMemo((): ConsoleDailyStatRow[] => {
    const src = dailyRangeQ.data?.rows ?? consoleDailyStats?.rows ?? [];
    return [...src].sort((a, b) => a.date.localeCompare(b.date));
  }, [consoleDailyStats?.rows, dailyRangeQ.data?.rows]);

  const monthlyDailyRows = useMemo(() => {
    if (selectedAccount == null) return [] as ConsoleDailyStatRow[];
    return fillDailyRows(dailyRowsScoped, queryRange.start, queryRange.end, String(selectedAccount));
  }, [dailyRowsScoped, queryRange.end, queryRange.start, selectedAccount]);

  const rangeCommandTotal = useMemo(
    () => dailyRowsScoped.reduce((s, r) => s + (r.matcher_runs || 0), 0),
    [dailyRowsScoped],
  );
  const rangeApiTotal = useMemo(
    () => dailyRowsScoped.reduce((s, r) => s + (r.api_calls ?? 0), 0),
    [dailyRowsScoped],
  );
  const rangeDayCount = Math.max(1, dailyRowsScoped.length);

  const pluginCandidates = useMemo(() => {
    const byId = new Map<string, { id: string; label: string; runsToday: number }>();
    for (const p of scopedPluginPlugins) {
      const id = String(p.name || "").trim();
      if (!id) continue;
      const runs = Number(p.runs_today) || 0;
      if (runs <= 0) continue;
      byId.set(id, {
        id,
        label: matcherPluginDisplayName(id, pluginsList),
        runsToday: runs,
      });
    }
    for (const row of scopedMatcherRunsByPlugin) {
      const id = String(row.plugin || "").trim();
      if (!id || !(row.points?.length ?? 0)) continue;
      if (!byId.has(id)) {
        byId.set(id, {
          id,
          label: matcherPluginDisplayName(id, pluginsList),
          runsToday: 0,
        });
      }
    }
    return [...byId.values()].sort(
      (a, b) => b.runsToday - a.runsToday || a.label.localeCompare(b.label),
    );
  }, [pluginsList, scopedMatcherRunsByPlugin, scopedPluginPlugins]);

  const rankPluginIds = useMemo(
    () =>
      resolveDisplayedPlugins(
        pluginCandidates.map((p) => p.id),
        rankFilter,
        12,
      ),
    [pluginCandidates, rankFilter],
  );

  const matcherPluginIds = useMemo(
    () =>
      resolveDisplayedPlugins(
        pluginCandidates.map((p) => p.id),
        matcherFilter,
        12,
      ),
    [matcherFilter, pluginCandidates],
  );

  const rankIdSet = useMemo(() => new Set(rankPluginIds), [rankPluginIds]);

  const topPluginBars = useMemo(() => {
    return pluginCandidates
      .filter((p) => rankIdSet.has(p.id))
      .slice(0, 12)
      .map((p) => ({
        label: p.label,
        fullLabel: p.label,
        value: p.runsToday,
      }));
  }, [pluginCandidates, rankIdSet]);

  const groupMetrics = dailyRangeQ.data?.group_metrics;
  const dagValue =
    groupMetrics && Number.isFinite(groupMetrics.dag) ? String(groupMetrics.dag) : "—";
  const magValue =
    groupMetrics && Number.isFinite(groupMetrics.mag) ? String(groupMetrics.mag) : "—";
  const dagMagRatio =
    groupMetrics?.dag_mag_ratio != null && Number.isFinite(groupMetrics.dag_mag_ratio)
      ? groupMetrics.dag_mag_ratio.toFixed(2)
      : "—";

  const dagTrendSeries = useMemo((): NamedSeriesInput[] => {
    const byDate = new Map<string, number>();
    for (const row of dailyRowsScoped) {
      const date = String(row.date || "").slice(0, 10);
      if (!date) continue;
      byDate.set(date, (byDate.get(date) || 0) + (Number(row.active_groups) || 0));
    }
    const points = [...byDate.entries()]
      .sort((a, b) => a[0].localeCompare(b[0]))
      .map(([date, total]) => ({
        at: Math.floor(new Date(`${date}T12:00:00`).getTime() / 1000),
        total,
      }));
    return [{ id: "dag", label: "DAG", points }];
  }, [dailyRowsScoped]);

  const matcherTrendSeries = useMemo(() => {
    return matcherPluginIds
      .filter((plugin) => {
        const row = scopedMatcherRunsByPlugin.find((r) => r.plugin === plugin);
        return (row?.points?.length ?? 0) > 0;
      })
      .slice(0, 12)
      .map((plugin) => {
        const row = scopedMatcherRunsByPlugin.find((r) => r.plugin === plugin)!;
        return {
          id: plugin,
          label: matcherPluginDisplayName(plugin, pluginsList),
          points: row.points ?? [],
        };
      });
  }, [matcherPluginIds, pluginsList, scopedMatcherRunsByPlugin]);

  function persistFilter(scope: ChartsPluginFilterScope, next: ChartsPluginFilterState) {
    if (scope === "rank") setRankFilter(next);
    else setMatcherFilter(next);
    writeChartsPluginFilter(selectedAccount, scope, next);
  }

  function onTogglePlugin(scope: ChartsPluginFilterScope, id: string, checked: boolean) {
    const filter = scope === "rank" ? rankFilter : matcherFilter;
    const displayed = scope === "rank" ? rankPluginIds : matcherPluginIds;
    const base =
      filter.mode === "custom" && filter.selected.length ? [...filter.selected] : displayed;
    const set = new Set(base);
    if (checked) set.add(id);
    else set.delete(id);
    persistFilter(scope, { mode: "custom", selected: [...set] });
  }

  function onSelectTop(scope: ChartsPluginFilterScope, n: number) {
    persistFilter(scope, {
      mode: "custom",
      selected: pluginCandidates.slice(0, n).map((p) => p.id),
    });
  }

  function onResetAuto(scope: ChartsPluginFilterScope) {
    persistFilter(scope, { mode: "auto", selected: [] });
  }

  const rankSelectedSet = useMemo(() => {
    if (rankFilter.mode === "custom" && rankFilter.selected.length) {
      return new Set(rankFilter.selected);
    }
    return new Set(rankPluginIds);
  }, [rankFilter, rankPluginIds]);

  const matcherSelectedSet = useMemo(() => {
    if (matcherFilter.mode === "custom" && matcherFilter.selected.length) {
      return new Set(matcherFilter.selected);
    }
    return new Set(matcherPluginIds);
  }, [matcherFilter, matcherPluginIds]);

  const accountTodayMsg = scopedBotStatsRow
    ? `${scopedBotStatsRow.today_received ?? "—"} / ${scopedBotStatsRow.today_sent ?? "—"}`
    : "—";
  const accountTodayApi = (() => {
    const n = scopedBotStatsRow?.today_api_calls;
    if (n == null || !Number.isFinite(Number(n))) return "—";
    return String(Math.floor(Number(n)));
  })();
  const accountMatcherRuns = (() => {
    const n = scopedPluginRunRow?.runs_today;
    if (n == null || !Number.isFinite(Number(n))) return "—";
    return String(Math.floor(Number(n)));
  })();
  const accountMatcherErrors = (() => {
    const n = scopedPluginRunRow?.errors_today;
    if (n == null || !Number.isFinite(Number(n))) return "—";
    return String(Math.floor(Number(n)));
  })();

  const rangeBusy = dailyRangeQ.isFetching;
  const refreshing = instQ.isFetching || pluginRunGlobalQ.isFetching || chartsBusy || rangeBusy;

  async function refreshAll() {
    await Promise.all([
      instQ.refetch(),
      pluginRunGlobalQ.refetch(),
      dailyRangeQ.refetch(),
      refreshChartStats(),
    ]);
  }

  function botNick(account: number): string {
    return instQ.data?.bot_profiles?.[String(account)]?.nickname?.trim() || "";
  }

  function botTitle(account: number): string {
    return botSelectDropdownLabel(botNick(account) || "BOT", account);
  }

  return (
    <div className="charts-page charts-page--dashboard">
      <PageMasthead
        className="charts-page__masthead"
        title="数据看板"
        description="流量、命令与群活跃概览；趋势与排行同屏。"
      />

      {sortedBots.length || (selectedAccount != null && instancesPending) ? (
        <ChromeTools>
          {sortedBots.length > 1 ? (
            <ChromeField label="账号" icon={Bot} className="shrink-0">
              <Select
                value={selectedAccount != null ? String(selectedAccount) : undefined}
                onValueChange={(v) => selectAccount(Number(v) || null)}
              >
                <SelectTrigger
                  className={ACCOUNT_SEL}
                  aria-label="选择 Bot 账号"
                  title={selectedAccount != null ? botTitle(selectedAccount) : undefined}
                >
                  <SelectValue placeholder="选择账号" />
                </SelectTrigger>
                <SelectContent align="start" className="min-w-[var(--radix-select-trigger-width)]">
                  {sortedBots.map((b) => (
                    <SelectItem key={b.account} value={String(b.account)}>
                      <BotSelectLabel nickname={botNick(b.account) || "BOT"} account={b.account} />
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </ChromeField>
          ) : null}
          <DateModeFilter
            size="toolbar"
            mode={dateMode}
            onModeChange={setDateMode}
            start={rangeStart}
            end={rangeEnd}
            onStartChange={setRangeStart}
            onEndChange={setRangeEnd}
          />
          <div className={CHROME_TOOLS_TRAILING}>
            <RefreshIconButton
              busy={refreshing}
              label="刷新"
              showLabel
              onClick={() => void refreshAll()}
            />
          </div>
        </ChromeTools>
      ) : null}

      {instancesPending && selectedAccount == null ? <ConsolePageSkeleton panels={3} /> : null}

      {botsResolved && !sortedBots.length ? (
        <p className="muted charts-page__empty">数据库中暂无 Bot 配置。请先在「数据库实例」创建账号。</p>
      ) : null}

      {selectedAccount != null ? (
        <div className="charts-page__layout" aria-busy={refreshing || undefined}>
          <section className="charts-page__kpi home-kpi-bar" aria-label="今日与区间摘要">
            <MetricTile label="今日消息" value={accountTodayMsg} hint="收 / 发" />
            <MetricTile label="今日 API" value={accountTodayApi} hint="协议调用" />
            <MetricTile
              label="今日 Matcher"
              value={accountMatcherRuns}
              hint={`异常 ${accountMatcherErrors}`}
            />
            <MetricTile label="DAG" value={dagValue} hint="今日活跃群" />
            <MetricTile
              label="MAG"
              value={magValue}
              hint={`近 ${groupMetrics?.mag_days ?? 30} 日`}
            />
            <MetricTile label="DAG/MAG" value={dagMagRatio} hint="日活 / 月活" />
            <MetricTile
              label="区间 Matcher"
              value={rangeCommandTotal.toLocaleString()}
              hint={`日均 ${Math.round(rangeCommandTotal / rangeDayCount).toLocaleString()}`}
            />
            <MetricTile
              label="区间 API"
              value={rangeApiTotal.toLocaleString()}
              hint={`日均 ${Math.round(rangeApiTotal / rangeDayCount).toLocaleString()}`}
            />
          </section>

          <section id="charts-trend" className="charts-page__section charts-page__section--hero">
            <div className="charts-page__board charts-page__board--cards">
              <Card className={cn(CHART_PANEL, "charts-page__panel--hero")}>
                <CardHeader className={CHART_PANEL_HD}>
                  <CardTitle className="panel__title flex items-center gap-1.5">
                    <PanelTitleIcon icon={LineChart} />
                    区间趋势
                  </CardTitle>
                </CardHeader>
                <CardContent className={CHART_PANEL_BD}>
                  <p className="muted charts-page__section-lead">消息 · Matcher · API（按日）</p>
                  <ChartsMonthlyCommandChart
                    rows={monthlyDailyRows}
                    busy={rangeBusy || chartsBusy}
                    emptyText="所选区间暂无数据"
                  />
                </CardContent>
              </Card>
              <Card className={cn(CHART_PANEL, "charts-page__panel--hero")}>
                <CardHeader className={CHART_PANEL_HD}>
                  <CardTitle className="panel__title flex items-center gap-1.5">
                    <PanelTitleIcon icon={UsersRound} />
                    活跃群趋势
                  </CardTitle>
                </CardHeader>
                <CardContent className={CHART_PANEL_BD}>
                  <p className="muted charts-page__section-lead">区间内每日 DAG</p>
                  <ChartsNamedSeriesTrend
                    series={dagTrendSeries}
                    busy={rangeBusy}
                    showSummary={false}
                    axisUnit=""
                    emptyText="暂无活跃群数据"
                    compact
                  />
                </CardContent>
              </Card>
            </div>
          </section>

          <section id="charts-detail" className="charts-page__section charts-page__section--secondary">
            <div className="charts-page__board flex flex-col gap-[var(--console-panel-gap,18px)]">
              <Card className={cn(CHART_PANEL, "charts-page__panel--secondary")}>
                <CardHeader className={CHART_PANEL_HD}>
                  <CardTitle className="panel__title flex items-center gap-1.5">
                    <PanelTitleIcon icon={Activity} />
                    Matcher 实时
                  </CardTitle>
                </CardHeader>
                <CardContent className={CHART_PANEL_BD}>
                  <p className="muted charts-page__section-lead mb-0">时间桶趋势</p>
                  <ChartsNamedSeriesTrend
                    series={matcherTrendSeries}
                    busy={chartsBusy}
                    chartUid="charts-matcher-bucket"
                    maxSeries={12}
                    emptyText="暂无 Matcher 时序"
                  />
                  <ChartsPluginFilter
                    embedded
                    open={matcherFilterOpen}
                    onOpenChange={setMatcherFilterOpen}
                    options={pluginCandidates.slice(0, 20)}
                    selected={matcherSelectedSet}
                    mode={matcherFilter.mode}
                    onToggle={(id, checked) => onTogglePlugin("matcher", id, checked)}
                    onSelectTop={(n) => onSelectTop("matcher", n)}
                    onResetAuto={() => onResetAuto("matcher")}
                  />
                </CardContent>
              </Card>

              <Card className={cn(CHART_PANEL, "charts-page__panel--secondary")}>
                <CardHeader className={CHART_PANEL_HD}>
                  <CardTitle className="panel__title flex items-center gap-1.5">
                    <PanelTitleIcon icon={BarChart3} />
                    插件排行
                  </CardTitle>
                </CardHeader>
                <CardContent className={CHART_PANEL_BD}>
                  <p className="muted charts-page__section-lead mb-0">今日 Matcher 次数</p>
                  <ChartsHorizontalRankBars
                    points={topPluginBars}
                    unit="次"
                    accent={PLUGIN_TODAY_BAR_ACCENT}
                    softScale
                    emptyText={chartsBusy ? "加载中…" : "暂无今日数据"}
                  />
                  <ChartsPluginFilter
                    embedded
                    open={rankFilterOpen}
                    onOpenChange={setRankFilterOpen}
                    options={pluginCandidates.slice(0, 20)}
                    selected={rankSelectedSet}
                    mode={rankFilter.mode}
                    onToggle={(id, checked) => onTogglePlugin("rank", id, checked)}
                    onSelectTop={(n) => onSelectTop("rank", n)}
                    onResetAuto={() => onResetAuto("rank")}
                  />
                </CardContent>
              </Card>
            </div>
            {!chartsBusy && !scopedPluginPlugins.length ? (
              <p className="muted charts-page__board-note">
                排行与实时桶需 Bot 运行一段时间；区间趋势依赖按日落盘。
              </p>
            ) : null}
          </section>
        </div>
      ) : null}
    </div>
  );
}
