// src/components/ConsoleHubSearch.tsx
import { Search } from "lucide-react";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";

/** 全站 hub 搜索：图标在输入框外（避免叠字），描边跟 control 面。 */
export default function ConsoleHubSearch({
  value,
  onValueChange,
  placeholder = "搜索…",
  ariaLabel,
  className,
  disabled,
}: {
  value: string;
  onValueChange: (value: string) => void;
  placeholder?: string;
  ariaLabel?: string;
  className?: string;
  disabled?: boolean;
}) {
  return (
    <div className={cn("console-hub-page__search-wrap", className)}>
      <label className="console-hub-page__search">
        <span className="console-hub-page__search-ico" aria-hidden="true">
          <Search className="console-hub-page__search-svg text-[var(--text-muted)]" strokeWidth={1.75} />
        </span>
        <Input
          className="console-hub-page__search-input h-8 min-h-8 focus-visible:ring-0 focus-visible:ring-offset-0"
          type="search"
          placeholder={placeholder}
          aria-label={ariaLabel || placeholder}
          autoComplete="off"
          disabled={disabled}
          value={value}
          onChange={(e) => onValueChange(e.target.value)}
        />
      </label>
    </div>
  );
}

// src/components/ConsoleHubSearch.vue
<script setup lang="ts">
import UiInput from "@/components/ui/UiInput.vue";

const model = defineModel<string>({ default: "" });

withDefaults(
  defineProps<{
    placeholder?: string;
    ariaLabel?: string;
  }>(),
  {
    placeholder: "搜索…",
  },
);
</script>

<template>
  <div class="console-hub-page__search-wrap">
    <label class="console-hub-page__search">
      <span
        class="console-hub-page__search-ico"
        aria-hidden="true"
      >
        <svg
          class="console-hub-page__search-svg"
          width="16"
          height="16"
          viewBox="0 0 16 16"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <circle
            cx="7"
            cy="7"
            r="4.25"
            stroke="currentColor"
            stroke-width="1.5"
          />
          <path
            d="M10.25 10.25L13.5 13.5"
            stroke="currentColor"
            stroke-width="1.5"
            stroke-linecap="round"
          />
        </svg>
      </span>
      <UiInput
        v-model="model"
        class="console-hub-page__search-input"
        type="search"
        :placeholder="placeholder"
        :aria-label="ariaLabel || placeholder"
        autocomplete="off"
      />
    </label>
  </div>
</template>
