// src/components/ConsoleDeleteConfirmModal.vue
<script setup lang="ts">
import { computed } from "vue";
import UiButton from "@/components/ui/UiButton.vue";
import UiDialog from "@/components/ui/UiDialog.vue";

export type ConsoleDeleteListItem = {
  key: string;
  label: string;
};

const props = defineProps<{
  open: boolean;
  title: string;
  subtitle: string;
  items: ConsoleDeleteListItem[];
  busy?: boolean;
  error?: string;
  warnings?: string[];
  confirmLabel?: string;
  titleId?: string;
}>();

const emit = defineEmits<{
  close: [];
  confirm: [];
}>();

const headingId = computed(() => props.titleId || "console-delete-modal-title");
</script>

<template>
  <UiDialog
    :open="open"
    :title-id="headingId"
    :title="title"
    :subtitle="subtitle"
    :busy="busy"
    :show-close="true"
    @close="emit('close')"
  >
    <p
      v-if="error"
      class="alert alert--err"
      style="margin: 0 0 12px"
    >
      {{ error }}
    </p>
    <p
      v-for="(w, wi) in warnings ?? []"
      :key="`warn-${wi}`"
      class="alert alert--err"
      style="margin: 0 0 12px"
    >
      {{ w }}
    </p>
    <p
      class="muted"
      style="margin: 0 0 8px; font-size: 13px"
    >
      账号列表
    </p>
    <ul class="inst-delete-account-list muted">
      <li
        v-for="item in items"
        :key="item.key"
      >
        {{ item.label }}
      </li>
    </ul>
    <div
      class="row-actions"
      style="margin-top: 18px; flex-wrap: wrap; gap: 8px"
    >
      <UiButton
        variant="destructive"
        :disabled="busy"
        @click="emit('confirm')"
      >
        {{ busy ? "删除中…" : (confirmLabel || "确认删除") }}
      </UiButton>
      <UiButton
        :disabled="busy"
        @click="emit('close')"
      >
        取消
      </UiButton>
    </div>
  </UiDialog>
</template>

<style>
.inst-delete-account-list {
  margin: 0;
  padding-left: 1.2em;
  line-height: 1.55;
  font-size: 13px;
  max-height: 200px;
  overflow: auto;
}
</style>

// src/components/ConsoleDeleteConfirmModal.tsx
import { Button } from "@/components/ui/button";
import {
  AlertDialog,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";

export type ConsoleDeleteListItem = {
  key: string;
  label: string;
};

type Props = {
  open: boolean;
  title: string;
  subtitle: string;
  items: ConsoleDeleteListItem[];
  busy?: boolean;
  error?: string;
  warnings?: string[];
  confirmLabel?: string;
  busyLabel?: string;
  listLabel?: string;
  /** 默认 destructive（删除）；重启/停止等用 default */
  confirmVariant?: "destructive" | "default";
  titleId?: string;
  onClose: () => void;
  onConfirm: () => void;
};

/** 批量操作二级确认：shadcn AlertDialog（展示账号列表与可选警告）。 */
export default function ConsoleDeleteConfirmModal({
  open,
  title,
  subtitle,
  items,
  busy = false,
  error,
  warnings,
  confirmLabel,
  busyLabel,
  listLabel = "账号列表",
  confirmVariant = "destructive",
  titleId,
  onClose,
  onConfirm,
}: Props) {
  const headingId = titleId || "console-delete-modal-title";
  const confirmText = busy
    ? busyLabel || (confirmVariant === "destructive" ? "删除中…" : "处理中…")
    : confirmLabel || (confirmVariant === "destructive" ? "确认删除" : "确认");

  return (
    <AlertDialog
      open={open}
      onOpenChange={(next) => {
        if (!next && !busy) onClose();
      }}
    >
      <AlertDialogContent className="bg-card sm:max-w-md">
        <AlertDialogHeader>
          <AlertDialogTitle id={headingId}>{title}</AlertDialogTitle>
          <AlertDialogDescription>{subtitle}</AlertDialogDescription>
        </AlertDialogHeader>

        {error ? <p className="alert alert--err m-0">{error}</p> : null}
        {(warnings ?? []).map((w, wi) => (
          <p key={`warn-${wi}`} className="alert alert--err m-0">
            {w}
          </p>
        ))}

        <div className="space-y-2">
          <p className="m-0 text-[13px] text-muted-foreground">{listLabel}</p>
          <ul className="inst-delete-account-list muted m-0">
            {items.map((item) => (
              <li key={item.key}>{item.label}</li>
            ))}
          </ul>
        </div>

        <AlertDialogFooter>
          <AlertDialogCancel disabled={busy}>取消</AlertDialogCancel>
          <Button type="button" variant={confirmVariant} disabled={busy} onClick={onConfirm}>
            {confirmText}
          </Button>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
}
