// src/components/ConsoleSwitch.vue
<script setup lang="ts">
withDefaults(
  defineProps<{
    modelValue: boolean;
    disabled?: boolean;
    label?: string;
    showLabel?: boolean;
    /** 开发模式等场景保留琥珀色轨道 */
    tone?: "default" | "amber";
    ariaLabel?: string;
  }>(),
  {
    disabled: false,
    showLabel: true,
    tone: "default",
  },
);

const emit = defineEmits<{
  "update:modelValue": [value: boolean];
}>();

function onChange(ev: Event) {
  emit("update:modelValue", (ev.target as HTMLInputElement).checked);
}
</script>

<template>
  <label
    class="console-bool-switch"
    :class="{
      'console-bool-switch--on': modelValue,
      'console-bool-switch--amber': tone === 'amber',
    }"
  >
    <input
      type="checkbox"
      class="console-bool-switch__input"
      :checked="modelValue"
      :disabled="disabled"
      :aria-label="ariaLabel || label"
      @change="onChange"
    >
    <span
      class="console-bool-switch__track"
      aria-hidden="true"
    >
      <span class="console-bool-switch__thumb" />
    </span>
    <span
      v-if="showLabel && label"
      class="console-bool-switch__label"
    >{{ label }}</span>
  </label>
</template>

// src/components/ConsoleSwitch.tsx
import { cn } from "@/lib/utils";

export default function ConsoleSwitch({
  checked,
  disabled = false,
  label,
  showLabel = true,
  tone = "default",
  ariaLabel,
  onCheckedChange,
}: {
  checked: boolean;
  disabled?: boolean;
  label?: string;
  showLabel?: boolean;
  tone?: "default" | "amber";
  ariaLabel?: string;
  onCheckedChange: (next: boolean) => void;
}) {
  return (
    <label
      className={cn(
        "console-bool-switch",
        checked && "console-bool-switch--on",
        tone === "amber" && "console-bool-switch--amber",
      )}
    >
      <input
        type="checkbox"
        className="console-bool-switch__input"
        checked={checked}
        disabled={disabled}
        aria-label={ariaLabel || label}
        onChange={(e) => onCheckedChange(e.target.checked)}
      />
      <span className="console-bool-switch__track" aria-hidden="true">
        <span className="console-bool-switch__thumb" />
      </span>
      {showLabel && label ? <span className="console-bool-switch__label">{label}</span> : null}
    </label>
  );
}
