// src/components/ConsoleToastHost.tsx
import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import {
  dismissConsoleToast,
  getConsoleToastItems,
  subscribeConsoleToast,
  type ConsoleToastItem,
} from "@/utils/consoleToast";

export default function ConsoleToastHost() {
  const [items, setItems] = useState<readonly ConsoleToastItem[]>(() => getConsoleToastItems());

  useEffect(() => subscribeConsoleToast(() => setItems(getConsoleToastItems())), []);

  if (!items.length || typeof document === "undefined") return null;

  return createPortal(
    <div className="console-toast-host" role="status" aria-live="polite" aria-atomic="false">
      {items.map((item) => (
        <div key={item.id} className={`console-toast console-toast--${item.level}`}>
          <span className="console-toast__msg">{item.message}</span>
          <button
            type="button"
            className="console-toast__close"
            aria-label="关闭"
            onClick={() => dismissConsoleToast(item.id)}
          >
            ×
          </button>
        </div>
      ))}
    </div>,
    document.body,
  );
}

// src/components/ConsoleToastHost.vue
<script setup lang="ts">
import { dismissConsoleToast, useConsoleToastState } from "@/utils/consoleToast";

const { items } = useConsoleToastState();
</script>

<template>
  <Teleport to="body">
    <div
      v-if="items.length"
      class="console-toast-host"
      role="status"
      aria-live="polite"
      aria-atomic="false"
    >
      <div
        v-for="item in items"
        :key="item.id"
        class="console-toast"
        :class="`console-toast--${item.level}`"
      >
        <span class="console-toast__msg">{{ item.message }}</span>
        <button
          type="button"
          class="console-toast__close"
          aria-label="关闭"
          @click="dismissConsoleToast(item.id)"
        >
          ×
        </button>
      </div>
    </div>
  </Teleport>
</template>
