// src/components/ConsoleHubToolbarStrip.vue
<script setup lang="ts">
withDefaults(
  defineProps<{
    /** 无搜索框、仅操作区（如统计与语料页刷新） */
    actionsOnly?: boolean;
  }>(),
  {
    actionsOnly: false,
  },
);
</script>

<template>
  <div
    class="console-hub-toolbar-strip"
    :class="{ 'console-hub-toolbar-strip--actions-only': actionsOnly }"
  >
    <div class="console-hub-toolbar-strip__main">
      <div
        v-if="$slots.search"
        class="console-hub-toolbar-strip__search"
      >
        <slot name="search" />
      </div>
      <div
        v-if="$slots.middle"
        class="console-hub-toolbar-strip__middle"
      >
        <slot name="middle" />
      </div>
      <div
        v-if="$slots.actions"
        class="console-hub-toolbar-strip__actions"
      >
        <slot name="actions" />
      </div>
    </div>
  </div>
</template>

// src/components/ConsoleHubToolbarStrip.tsx
import type { ReactNode } from "react";
import { cn } from "@/lib/utils";

export default function ConsoleHubToolbarStrip({
  search,
  middle,
  actions,
  actionsOnly = false,
  className,
}: {
  search?: ReactNode;
  middle?: ReactNode;
  actions?: ReactNode;
  actionsOnly?: boolean;
  className?: string;
}) {
  return (
    <div
      className={cn(
        "console-hub-toolbar-strip",
        actionsOnly && "console-hub-toolbar-strip--actions-only",
        className,
      )}
    >
      <div className="console-hub-toolbar-strip__main">
        {search ? <div className="console-hub-toolbar-strip__search">{search}</div> : null}
        {middle ? <div className="console-hub-toolbar-strip__middle">{middle}</div> : null}
        {actions ? <div className="console-hub-toolbar-strip__actions">{actions}</div> : null}
      </div>
    </div>
  );
}
