// src/components/ConsoleTableEdit.vue
<script setup lang="ts">
withDefaults(
  defineProps<{
    disabled?: boolean;
    label?: string;
  }>(),
  { disabled: false, label: "编辑" },
);

const emit = defineEmits<{
  click: [];
}>();
</script>

<template>
  <button
    type="button"
    class="console-table-edit"
    :disabled="disabled"
    @click="emit('click')"
  >
    {{ label }}
  </button>
</template>

// src/components/ConsoleTableEdit.tsx
import { cn } from "@/lib/utils";

export default function ConsoleTableEdit({
  disabled,
  label = "配置",
  variant = "default",
  onClick,
}: {
  disabled?: boolean;
  label?: string;
  variant?: "default" | "danger";
  onClick?: () => void;
}) {
  return (
    <button
      type="button"
      className={cn("console-table-edit", variant === "danger" && "console-table-edit--danger")}
      disabled={disabled}
      onClick={onClick}
    >
      {label}
    </button>
  );
}
