// react/src/components/CorpusWordCloud.tsx
import { useCallback, useEffect, useMemo, useRef, useState, type CSSProperties } from "react";
import { axiosErrorDetail } from "@/api/http";
import { fetchCommunityCorpusHot, fetchLocalCorpusHot } from "@/api/fullConsole";
import type { CommunityCorpusHotData, CommunityHotTab } from "@/api/pallasTypes";
import { rankHotItems, type HotTagNode } from "@/utils/hotBubbleLayout";
import { cn } from "@/lib/utils";

const communityTabs: Array<{ key: CommunityHotTab; label: string }> = [
  { key: "fleet", label: "机群" },
  { key: "pool", label: "高频池" },
  { key: "month", label: "本月" },
];

function pillClasses(node: HotTagNode, selected: string | null): string {
  const classes = ["corpus-hot__pill", `corpus-hot__pill--${node.sizeClass}`];
  if (node.rank <= 3) classes.push(`corpus-hot__pill--top${node.rank}`);
  if (node.item.keywords === selected) classes.push("corpus-hot__pill--active");
  return classes.join(" ");
}

export default function CorpusWordCloud({
  source = "community",
  reloadToken = 0,
}: {
  source?: "community" | "local";
  reloadToken?: number;
}) {
  const [tab, setTab] = useState<CommunityHotTab>("fleet");
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState("");
  const [data, setData] = useState<CommunityCorpusHotData | null>(null);
  const [selectedKeywords, setSelectedKeywords] = useState<string | null>(null);
  const [cloudLoading, setCloudLoading] = useState(false);
  const [cloudEntering, setCloudEntering] = useState(false);
  const enterTimerRef = useRef<number | null>(null);

  const tabLabel = communityTabs.find((row) => row.key === tab)?.label || "机群";

  const scopeLabel =
    source === "local"
      ? "本机累计"
      : tab === "fleet"
        ? "近24h机群叠加"
        : tab === "pool"
          ? "社区高频池"
          : `${tabLabel}近期活跃`;

  const statusHint =
    source === "local" || tab === "fleet"
      ? "标签越大越热 · 点击查看热度"
      : "标签越大越热 · 点击查看代表回复";

  const items = data?.items || [];
  const rankedNodes = useMemo(() => rankHotItems(items), [items]);
  const selectedItem = items.find((item) => item.keywords === selectedKeywords) || null;
  const selectedRank =
    selectedKeywords != null
      ? rankedNodes.find((node) => node.item.keywords === selectedKeywords)?.rank ?? null
      : null;

  const triggerCloudEnter = useCallback(() => {
    setCloudEntering(true);
    if (enterTimerRef.current != null) window.clearTimeout(enterTimerRef.current);
    enterTimerRef.current = window.setTimeout(() => {
      setCloudEntering(false);
      enterTimerRef.current = null;
    }, 640);
  }, []);

  const loadHot = useCallback(
    async (bypassCache = false) => {
      const tabSwitch = cloudLoading;
      setBusy(true);
      setErr("");
      try {
        const next =
          source === "local"
            ? await fetchLocalCorpusHot({ bypassCache })
            : await fetchCommunityCorpusHot(tab, { bypassCache });
        setData(next);
        if (selectedKeywords && !next.items.some((item) => item.keywords === selectedKeywords)) {
          setSelectedKeywords(null);
        }
        if (tabSwitch && rankHotItems(next.items).length) {
          triggerCloudEnter();
        }
      } catch (e) {
        setData(null);
        setSelectedKeywords(null);
        setErr(axiosErrorDetail(e));
      } finally {
        setBusy(false);
        setCloudLoading(false);
      }
    },
    [cloudLoading, selectedKeywords, source, tab, triggerCloudEnter],
  );

  useEffect(() => {
    void loadHot();
  }, [source, tab]);

  useEffect(() => {
    if (reloadToken > 0) void loadHot(true);
  }, [reloadToken]);

  useEffect(
    () => () => {
      if (enterTimerRef.current != null) window.clearTimeout(enterTimerRef.current);
    },
    [],
  );

  function selectTab(next: CommunityHotTab) {
    if (next === tab || busy) return;
    if (items.length) setCloudLoading(true);
    setTab(next);
    setSelectedKeywords(null);
  }

  function toggleKeyword(keywords: string) {
    setSelectedKeywords((cur) => (cur === keywords ? null : keywords));
  }

  return (
    <div className="corpus-hot">
      {source === "community" ? (
        <div className="corpus-hot__tabs" role="tablist" aria-label="热词统计范围">
          {communityTabs.map((row) => (
            <button
              key={row.key}
              type="button"
              className={cn("corpus-hot__tab", tab === row.key && "corpus-hot__tab--active")}
              role="tab"
              aria-selected={tab === row.key}
              disabled={busy}
              onClick={() => selectTab(row.key)}
            >
              {row.label}
            </button>
          ))}
        </div>
      ) : null}

      {busy && !items.length ? (
        <p className="muted corpus-hot__status">加载{scopeLabel}热词…</p>
      ) : err ? (
        <p className="alert alert--warn corpus-hot__status">热词加载失败：{err}</p>
      ) : !items.length ? (
        <p className="muted corpus-hot__status">
          {source === "local"
            ? "暂无本机语料热词。日常接话学习后，这里会展示本部署累计最热触发词。"
            : tab === "fleet"
              ? "暂无机群热词。各部署开启语料贡献并上报心跳后，这里会展示近24h热词叠加榜。"
              : tab === "pool"
                ? "暂无共享语料高频词。接入并贡献语料后，这里会展示社区累计最热触发词。"
                : "该时段暂无近期活跃热词。可切换到「机群」或「高频池」查看。"}
        </p>
      ) : (
        <p className="muted corpus-hot__status">
          {scopeLabel} · {statusHint}
        </p>
      )}

      {items.length ? (
        <div
          className={cn("corpus-hot__canvas", cloudLoading && "corpus-hot__canvas--loading")}
          aria-label="共享语料热词云"
        >
          <div
            className={cn(
              "corpus-hot__cloud",
              selectedKeywords && "corpus-hot__cloud--selected",
              cloudEntering && "corpus-hot__cloud--tab-enter",
            )}
            role="list"
          >
            {rankedNodes.map((node, index) => (
              <button
                key={node.item.keywords}
                type="button"
                className={pillClasses(node, selectedKeywords)}
                style={
                  {
                    "--heat": node.scoreRatio.toFixed(3),
                    "--pill-i": String(index),
                  } as CSSProperties
                }
                role="listitem"
                aria-pressed={node.item.keywords === selectedKeywords}
                title={`${node.item.keywords} · 热度 ${node.item.score}`}
                onClick={() => toggleKeyword(node.item.keywords)}
              >
                {node.rank <= 3 ? (
                  <span className="corpus-hot__pill-rank" aria-hidden="true">
                    {node.rank}
                  </span>
                ) : null}
                <span className="corpus-hot__pill-word">{node.item.keywords}</span>
                <span className="corpus-hot__pill-score">{node.item.score}</span>
              </button>
            ))}
          </div>
        </div>
      ) : null}

      {selectedItem ? (
        <div className="corpus-hot__detail" aria-live="polite">
          <div className="corpus-hot__detail-panel">
            <div className="corpus-hot__detail-hd">
              <div className="corpus-hot__detail-heading">
                {selectedRank != null && selectedRank <= 3 ? (
                  <span className="corpus-hot__detail-rank">#{selectedRank}</span>
                ) : null}
                <h3 className="corpus-hot__detail-title">{selectedItem.keywords}</h3>
                <p className="corpus-hot__detail-meta muted">
                  {source === "local" || tab === "pool"
                    ? `累计热度 ${selectedItem.score}`
                    : tab === "fleet"
                      ? `机群叠加热度 ${selectedItem.score}`
                      : `${tabLabel}热度 ${selectedItem.score}`}
                </p>
              </div>
              <button type="button" className="corpus-hot__detail-close" aria-label="收起详情" onClick={() => setSelectedKeywords(null)}>
                收起
              </button>
            </div>
            <ul className="corpus-hot__reply-list">
              {!selectedItem.answers.length ? (
                <li className="corpus-hot__reply corpus-hot__reply--empty muted">
                  {tab === "fleet" ? "机群榜不含代表回复" : "暂无代表回复"}
                </li>
              ) : (
                selectedItem.answers.map((answer, idx) => (
                  <li key={`${selectedItem.keywords}-${idx}`} className="corpus-hot__reply">
                    <p className="corpus-hot__reply-text">{answer.message || answer.answer_keywords || "（无文案）"}</p>
                    <p className="corpus-hot__reply-hint muted">引用 {answer.count} 次</p>
                  </li>
                ))
              )}
            </ul>
          </div>
        </div>
      ) : null}
    </div>
  );
}

// src/components/CorpusWordCloud.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from "vue";
import { fetchCommunityCorpusHot, fetchLocalCorpusHot } from "@/api/consoleApi";
import type { CommunityCorpusHotData, CommunityHotTab, HotCorpusItem } from "@/api/pallasTypes";
import { rankHotItems, type HotTagNode } from "@/utils/hotBubbleLayout";

const props = withDefaults(
  defineProps<{
    reloadToken?: number;
    source?: "community" | "local";
  }>(),
  {
    source: "community",
  },
);

const communityTabs: Array<{ key: CommunityHotTab; label: string }> = [
  { key: "fleet", label: "机群" },
  { key: "pool", label: "高频池" },
  { key: "month", label: "本月" },
];

const tab = ref<CommunityHotTab>("fleet");
const busy = ref(false);
const err = ref("");
const data = ref<CommunityCorpusHotData | null>(null);
const selectedKeywords = ref<string | null>(null);
const cloudLoading = ref(false);
const cloudEntering = ref(false);
let enterTimer: number | null = null;

const tabLabel = computed(() => communityTabs.find((row) => row.key === tab.value)?.label || "机群");

const scopeLabel = computed(() => {
  if (props.source === "local") return "本机累计";
  if (tab.value === "fleet") return "近24h机群叠加";
  return tab.value === "pool" ? "社区高频池" : `${tabLabel.value}近期活跃`;
});

const statusHint = computed(() =>
  props.source === "local" || tab.value === "fleet"
    ? "标签越大越热 · 点击查看热度"
    : "标签越大越热 · 点击查看代表回复",
);

const items = computed((): HotCorpusItem[] => data.value?.items || []);
const rankedNodes = computed(() => rankHotItems(items.value));

const selectedItem = computed(() =>
  items.value.find((item) => item.keywords === selectedKeywords.value) || null,
);

const selectedRank = computed(() => {
  if (!selectedKeywords.value) return null;
  return rankedNodes.value.find((node) => node.item.keywords === selectedKeywords.value)?.rank ?? null;
});

function pillClasses(node: HotTagNode): string[] {
  const classes = ["corpus-hot__pill", `corpus-hot__pill--${node.sizeClass}`];
  if (node.rank <= 3) classes.push(`corpus-hot__pill--top${node.rank}`);
  if (node.item.keywords === selectedKeywords.value) classes.push("corpus-hot__pill--active");
  return classes;
}

function toggleKeyword(keywords: string) {
  selectedKeywords.value = selectedKeywords.value === keywords ? null : keywords;
}

function clearSelection() {
  selectedKeywords.value = null;
}

function triggerCloudEnter() {
  cloudEntering.value = true;
  if (enterTimer != null) window.clearTimeout(enterTimer);
  enterTimer = window.setTimeout(() => {
    cloudEntering.value = false;
    enterTimer = null;
  }, 640);
}

async function loadHot(bypassCache = false) {
  const tabSwitch = cloudLoading.value;
  busy.value = true;
  err.value = "";
  try {
    data.value =
      props.source === "local"
        ? await fetchLocalCorpusHot({ bypassCache })
        : await fetchCommunityCorpusHot(tab.value, { bypassCache });
    if (selectedKeywords.value && !data.value.items.some((item) => item.keywords === selectedKeywords.value)) {
      selectedKeywords.value = null;
    }
    if (tabSwitch && rankedNodes.value.length) {
      triggerCloudEnter();
    }
  } catch (e) {
    data.value = null;
    selectedKeywords.value = null;
    err.value = e instanceof Error ? e.message : String(e);
  } finally {
    busy.value = false;
    cloudLoading.value = false;
  }
}

function selectTab(next: CommunityHotTab) {
  if (next === tab.value || busy.value) return;
  if (items.value.length) {
    cloudLoading.value = true;
  }
  tab.value = next;
  selectedKeywords.value = null;
  void loadHot();
}

void loadHot();

onBeforeUnmount(() => {
  if (enterTimer != null) window.clearTimeout(enterTimer);
  enterTimer = null;
});

watch(
  () => props.reloadToken,
  () => {
    void loadHot(true);
  },
);
</script>

<template>
  <div class="corpus-hot">
    <div
      v-if="source === 'community'"
      class="corpus-hot__tabs"
      role="tablist"
      aria-label="热词统计范围"
    >
      <button
        v-for="row in communityTabs"
        :key="row.key"
        type="button"
        class="corpus-hot__tab"
        :class="{ 'corpus-hot__tab--active': tab === row.key }"
        role="tab"
        :aria-selected="tab === row.key ? 'true' : 'false'"
        :disabled="busy"
        @click="selectTab(row.key)"
      >
        {{ row.label }}
      </button>
    </div>

    <p
      v-if="busy && !items.length"
      class="muted corpus-hot__status"
    >
      加载{{ scopeLabel }}热词…
    </p>
    <p
      v-else-if="err"
      class="alert alert--warn corpus-hot__status"
    >
      热词加载失败：{{ err }}
    </p>
    <p
      v-else-if="!items.length"
      class="muted corpus-hot__status"
    >
      <template v-if="source === 'local'">
        暂无本机语料热词。日常接话学习后，这里会展示本部署累计最热触发词。
      </template>
      <template v-else-if="tab === 'fleet'">
        暂无机群热词。各部署开启语料贡献并上报心跳后，这里会展示近24h热词叠加榜。
      </template>
      <template v-else-if="tab === 'pool'">
        暂无共享语料高频词。接入并贡献语料后，这里会展示社区累计最热触发词。
      </template>
      <template v-else>
        该时段暂无近期活跃热词。可切换到「机群」或「高频池」查看。
      </template>
    </p>
    <p
      v-else
      class="muted corpus-hot__status"
    >
      {{ scopeLabel }} · {{ statusHint }}
    </p>

    <div
      v-show="items.length"
      class="corpus-hot__canvas"
      :class="{ 'corpus-hot__canvas--loading': cloudLoading }"
      aria-label="共享语料热词云"
    >
      <div
        class="corpus-hot__cloud"
        :class="{
          'corpus-hot__cloud--selected': selectedKeywords,
          'corpus-hot__cloud--tab-enter': cloudEntering,
        }"
        role="list"
      >
        <button
          v-for="(node, index) in rankedNodes"
          :key="node.item.keywords"
          type="button"
          :class="pillClasses(node)"
          :style="{
            '--heat': node.scoreRatio.toFixed(3),
            '--pill-i': String(index),
          }"
          role="listitem"
          :aria-pressed="node.item.keywords === selectedKeywords ? 'true' : 'false'"
          :title="`${node.item.keywords} · 热度 ${node.item.score}`"
          @click="toggleKeyword(node.item.keywords)"
        >
          <span
            v-if="node.rank <= 3"
            class="corpus-hot__pill-rank"
            aria-hidden="true"
          >{{ node.rank }}</span>
          <span class="corpus-hot__pill-word">{{ node.item.keywords }}</span>
          <span class="corpus-hot__pill-score">{{ node.item.score }}</span>
        </button>
      </div>
    </div>

    <div
      v-if="selectedItem"
      class="corpus-hot__detail"
      aria-live="polite"
    >
      <div class="corpus-hot__detail-panel">
        <div class="corpus-hot__detail-hd">
          <div class="corpus-hot__detail-heading">
            <span
              v-if="selectedRank !== null && selectedRank <= 3"
              class="corpus-hot__detail-rank"
            >#{{ selectedRank }}</span>
            <h3 class="corpus-hot__detail-title">
              {{ selectedItem.keywords }}
            </h3>
            <p class="corpus-hot__detail-meta muted">
              <template v-if="source === 'local' || tab === 'pool'">
                累计热度 {{ selectedItem.score }}
              </template>
              <template v-else-if="tab === 'fleet'">
                机群叠加热度 {{ selectedItem.score }}
              </template>
              <template v-else>
                {{ tabLabel }}热度 {{ selectedItem.score }}
              </template>
            </p>
          </div>
          <button
            type="button"
            class="corpus-hot__detail-close"
            aria-label="收起详情"
            @click="clearSelection"
          >
            收起
          </button>
        </div>
        <ul class="corpus-hot__reply-list">
          <li
            v-if="!selectedItem.answers.length"
            class="corpus-hot__reply corpus-hot__reply--empty muted"
          >
            {{ tab === 'fleet' ? '机群榜不含代表回复' : '暂无代表回复' }}
          </li>
          <li
            v-for="(answer, idx) in selectedItem.answers"
            v-else
            :key="`${selectedItem.keywords}-${idx}`"
            class="corpus-hot__reply"
          >
            <p class="corpus-hot__reply-text">
              {{ answer.message || answer.answer_keywords || "（无文案）" }}
            </p>
            <p class="corpus-hot__reply-hint muted">
              引用 {{ answer.count }} 次
            </p>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>
