// src/components/LogVirtualFeed.tsx
import {
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
} from "react";
import type { LogEntry } from "@/api/pallasTypes";
import { formatLogDisplayTime } from "@/utils/logDisplay";
import { cn } from "@/lib/utils";
import "@/styles/log-virtual-feed.css";

export type LogVirtualFeedHandle = {
  scrollToBottom: (force?: boolean) => Promise<void>;
};

type Props = {
  rows: LogEntry[];
  followTail?: boolean;
  rowHeight?: number;
  overscan?: number;
  onScrollState?: (nearBottom: boolean) => void;
};

function stableRowKey(row: LogEntry): string {
  const id = row.id;
  if (typeof id === "number" && Number.isFinite(id) && id > 0) return `id:${id}`;
  const msg = String(row.message ?? "");
  return `c:${row.time}|${row.scope}|${row.level}|${msg.length}:${msg.slice(0, 64)}:${msg.slice(-32)}`;
}

function previewMessage(message: string): string {
  return message.replace(/\s+/g, " ").trim();
}

const LogVirtualFeed = forwardRef<LogVirtualFeedHandle, Props>(function LogVirtualFeed(
  { rows, followTail = true, rowHeight = 34, overscan = 10, onScrollState },
  ref,
) {
  const scrollElRef = useRef<HTMLDivElement | null>(null);
  const [scrollTop, setScrollTop] = useState(0);
  const [viewportHeight, setViewportHeight] = useState(480);
  const [expandedKey, setExpandedKey] = useState<string | null>(null);
  const [expandedSnapshot, setExpandedSnapshot] = useState<LogEntry | null>(null);
  const suppressScrollStateRef = useRef(0);
  const scrollBottomTokenRef = useRef(0);
  const roRef = useRef<ResizeObserver | null>(null);

  const totalHeight = Math.max(0, rows.length * rowHeight);
  const startIndex = Math.max(0, Math.floor(scrollTop / rowHeight) - overscan);
  const endIndex = Math.min(
    rows.length,
    Math.ceil((scrollTop + viewportHeight) / rowHeight) + overscan,
  );
  const visibleRows = useMemo(
    () =>
      rows.slice(startIndex, endIndex).map((row, i) => {
        const index = startIndex + i;
        const stableKey = stableRowKey(row);
        return { row, index, stableKey, domKey: `${stableKey}#${index}` };
      }),
    [rows, startIndex, endIndex],
  );
  const offsetY = startIndex * rowHeight;

  const expandedRow = useMemo(() => {
    if (!expandedKey) return null;
    const live = rows.find((row) => stableRowKey(row) === expandedKey);
    return live ?? expandedSnapshot;
  }, [rows, expandedKey, expandedSnapshot]);

  const scrollThreshold = useCallback((el: HTMLElement) => {
    const h = el.clientHeight;
    return Math.min(80, Math.max(24, Math.floor(h * 0.08)));
  }, []);

  const isNearBottom = useCallback(
    (el: HTMLElement) => {
      if (el.clientHeight < 8) return false;
      const gap = el.scrollHeight - el.scrollTop - el.clientHeight;
      const slack = Math.max(scrollThreshold(el), rowHeight * 3);
      return gap <= slack;
    },
    [rowHeight, scrollThreshold],
  );

  const scrollToBottom = useCallback(
    async (force = false) => {
      if (!force && !followTail) return;
      await Promise.resolve();
      const el = scrollElRef.current;
      if (!el) return;
      const token = ++scrollBottomTokenRef.current;
      suppressScrollStateRef.current += 1;
      const apply = () => {
        if (token !== scrollBottomTokenRef.current) return;
        const estimated = Math.max(el.scrollHeight, rows.length * rowHeight);
        el.scrollTop = Math.max(0, estimated - el.clientHeight);
        setScrollTop(el.scrollTop);
      };
      apply();
      let frames = 0;
      const tick = () => {
        if (token !== scrollBottomTokenRef.current) {
          suppressScrollStateRef.current = Math.max(0, suppressScrollStateRef.current - 1);
          return;
        }
        apply();
        frames += 1;
        const laidOut = el.clientHeight >= 8;
        const needRetry = !laidOut || !isNearBottom(el);
        if (frames < (laidOut ? 8 : 16) && needRetry) {
          window.requestAnimationFrame(tick);
          return;
        }
        suppressScrollStateRef.current = Math.max(0, suppressScrollStateRef.current - 1);
        if (laidOut) onScrollState?.(true);
      };
      window.requestAnimationFrame(tick);
    },
    [followTail, isNearBottom, onScrollState, rowHeight, rows.length],
  );

  useImperativeHandle(ref, () => ({ scrollToBottom }), [scrollToBottom]);

  // 挂载时强制贴底一次（；后续跟尾由 followTail 相关 effect 负责
  useEffect(() => {
    void scrollToBottom(true);
    // eslint-disable-next-line react-hooks/exhaustive-deps -- enter once
  }, []);

  useEffect(() => {
    const el = scrollElRef.current;
    if (!el || typeof ResizeObserver === "undefined") return;
    roRef.current?.disconnect();
    roRef.current = new ResizeObserver(() => {
      setViewportHeight(el.clientHeight || 480);
      if (followTail) void scrollToBottom(true);
    });
    roRef.current.observe(el);
    setViewportHeight(el.clientHeight || 480);
    return () => roRef.current?.disconnect();
  }, [followTail, scrollToBottom]);

  useEffect(() => {
    if (followTail) void scrollToBottom(true);
  }, [rows.length, followTail, scrollToBottom]);

  useEffect(() => {
    const last = rows[rows.length - 1];
    const token = last ? `${stableRowKey(last)}|${last.message.length}` : "";
    void token;
    if (followTail) void scrollToBottom(true);
  }, [rows, followTail, scrollToBottom]);

  useEffect(() => {
    if (followTail) void scrollToBottom(true);
  }, [followTail, scrollToBottom]);

  function onScroll() {
    const el = scrollElRef.current;
    if (!el) return;
    setScrollTop(el.scrollTop);
    if (suppressScrollStateRef.current > 0) return;
    onScrollState?.(isNearBottom(el));
  }

  function toggleRow(key: string, row: LogEntry) {
    if (expandedKey === key) {
      setExpandedKey(null);
      setExpandedSnapshot(null);
      return;
    }
    setExpandedKey(key);
    setExpandedSnapshot({ ...row });
  }

  return (
    <div className="log-virtual-feed-wrap">
      <div ref={scrollElRef} className="log-feed log-virtual-feed" onScroll={onScroll}>
        <div className="log-virtual-feed__spacer" style={{ height: `${totalHeight}px` }}>
          <div className="log-virtual-feed__window" style={{ transform: `translateY(${offsetY}px)` }}>
            {visibleRows.map(({ row, stableKey, domKey }) => (
              <button
                key={domKey}
                type="button"
                className={cn(
                  "log-line log-line--virtual",
                  expandedKey === stableKey && "log-line--virtual-active",
                )}
                style={{ minHeight: `${rowHeight}px`, height: `${rowHeight}px` }}
                title={previewMessage(row.message)}
                onClick={() => toggleRow(stableKey, row)}
              >
                <span className="log-line__time">{formatLogDisplayTime(row.time)}</span>
                <span className={cn("log-line__lv-tag", `log-line__lv-tag--${row.level}`)}>{row.level}</span>
                {row.scope ? <span className="log-line__scope">[{row.scope}]</span> : null}
                <span className="log-line__msg log-line__msg--clip">{previewMessage(row.message)}</span>
              </button>
            ))}
          </div>
        </div>
      </div>
      {expandedRow ? (
        <div className="log-virtual-feed__detail">
          <div className="log-virtual-feed__detail-meta">
            <span className="log-line__time">{formatLogDisplayTime(expandedRow.time)}</span>
            <span className={cn("log-line__lv-tag", `log-line__lv-tag--${expandedRow.level}`)}>
              {expandedRow.level}
            </span>
            {expandedRow.scope ? <span className="log-line__scope">[{expandedRow.scope}]</span> : null}
            <button
              type="button"
              className="ui-btn ui-btn--ghost ui-btn--sm log-virtual-feed__detail-close"
              onClick={() => {
                setExpandedKey(null);
                setExpandedSnapshot(null);
              }}
            >
              收起
            </button>
          </div>
          <pre className="log-virtual-feed__detail-body">{expandedRow.message}</pre>
        </div>
      ) : null}
    </div>
  );
});

export default LogVirtualFeed;

// src/components/LogVirtualFeed.vue
<script setup lang="ts">
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from "vue";
import type { LogEntry } from "@/api/pallasTypes";
import { formatLogDisplayTime } from "@/utils/logDisplay";

const props = withDefaults(
  defineProps<{
    rows: LogEntry[];
    followTail?: boolean;
    rowHeight?: number;
    overscan?: number;
  }>(),
  {
    followTail: true,
    rowHeight: 34,
    overscan: 10,
  },
);

const emit = defineEmits<{
  scrollState: [nearBottom: boolean];
}>();

const scrollEl = ref<HTMLElement | null>(null);
const scrollTop = ref(0);
const viewportHeight = ref(480);
/** 展开详情按稳定 key 绑定；快照避免列表滚动/追加后内容漂移 */
const expandedKey = ref<string | null>(null);
const expandedSnapshot = ref<LogEntry | null>(null);
let ro: ResizeObserver | null = null;
let suppressScrollState = 0;
let scrollBottomToken = 0;

const totalHeight = computed(() => Math.max(0, props.rows.length * props.rowHeight));

const startIndex = computed(() => {
  const raw = Math.floor(scrollTop.value / props.rowHeight) - props.overscan;
  return Math.max(0, raw);
});

const endIndex = computed(() => {
  const raw = Math.ceil((scrollTop.value + viewportHeight.value) / props.rowHeight) + props.overscan;
  return Math.min(props.rows.length, raw);
});

const visibleRows = computed(() =>
  props.rows.slice(startIndex.value, endIndex.value).map((row, i) => {
    const index = startIndex.value + i;
    const stableKey = stableRowKey(row);
    return {
      row,
      index,
      stableKey,
      /** DOM key 含下标保证唯一；展开态只用 stableKey */
      domKey: `${stableKey}#${index}`,
    };
  }),
);

const offsetY = computed(() => startIndex.value * props.rowHeight);

const expandedRow = computed(() => {
  if (!expandedKey.value) return null;
  const live = props.rows.find((row) => stableRowKey(row) === expandedKey.value);
  return live ?? expandedSnapshot.value;
});

/** 正数 stream id 优先；否则用内容指纹（不含列表下标，避免 stick-to-bottom 时漂移） */
function stableRowKey(row: LogEntry): string {
  const id = row.id;
  if (typeof id === "number" && Number.isFinite(id) && id > 0) return `id:${id}`;
  const msg = String(row.message ?? "");
  return `c:${row.time}|${row.scope}|${row.level}|${msg.length}:${msg.slice(0, 64)}:${msg.slice(-32)}`;
}

function previewMessage(message: string): string {
  return message.replace(/\s+/g, " ").trim();
}

function scrollThreshold(el: HTMLElement): number {
  const h = el.clientHeight;
  return Math.min(80, Math.max(24, Math.floor(h * 0.08)));
}

function isNearBottom(el: HTMLElement): boolean {
  // 尚未量到高度时不要当成「已在底部」，否则多帧重试会提前结束
  if (el.clientHeight < 8) return false;
  const gap = el.scrollHeight - el.scrollTop - el.clientHeight;
  const slack = Math.max(scrollThreshold(el), props.rowHeight * 3);
  return gap <= slack;
}

function onScroll() {
  const el = scrollEl.value;
  if (!el) return;
  scrollTop.value = el.scrollTop;
  if (suppressScrollState > 0) return;
  emit("scrollState", isNearBottom(el));
}

function toggleRow(key: string, row: LogEntry) {
  if (expandedKey.value === key) {
    expandedKey.value = null;
    expandedSnapshot.value = null;
    return;
  }
  expandedKey.value = key;
  expandedSnapshot.value = { ...row };
}

async function scrollToBottom(force = false) {
  if (!force && !props.followTail) return;
  await nextTick();
  const el = scrollEl.value;
  if (!el) return;
  const token = ++scrollBottomToken;
  suppressScrollState += 1;
  const apply = () => {
    if (token !== scrollBottomToken) return;
    // 优先用虚拟列表估算高度，避免 spacer 未提交前 scrollHeight 偏小
    const estimated = Math.max(el.scrollHeight, props.rows.length * props.rowHeight);
    el.scrollTop = Math.max(0, estimated - el.clientHeight);
    scrollTop.value = el.scrollTop;
  };
  apply();
  if (typeof window === "undefined") {
    suppressScrollState = Math.max(0, suppressScrollState - 1);
    emit("scrollState", true);
    return;
  }
  let frames = 0;
  const tick = () => {
    if (token !== scrollBottomToken) {
      suppressScrollState = Math.max(0, suppressScrollState - 1);
      return;
    }
    apply();
    frames += 1;
    const laidOut = el.clientHeight >= 8;
    const needRetry = !laidOut || !isNearBottom(el);
    // 布局未完成时多等几帧；已布局仍未贴底也再试
    if (frames < (laidOut ? 8 : 16) && needRetry) {
      window.requestAnimationFrame(tick);
      return;
    }
    suppressScrollState = Math.max(0, suppressScrollState - 1);
    // 程序化滚底后锁定跟随，避免布局未完成时误判「已离开底部」
    if (laidOut) emit("scrollState", true);
  };
  window.requestAnimationFrame(tick);
}

function bindViewport() {
  const el = scrollEl.value;
  if (!el || typeof ResizeObserver === "undefined") return;
  ro?.disconnect();
  ro = new ResizeObserver(() => {
    viewportHeight.value = el.clientHeight || 480;
    if (props.followTail) void scrollToBottom(true);
  });
  ro.observe(el);
  viewportHeight.value = el.clientHeight || 480;
}

watch(
  () => props.rows.length,
  () => {
    if (props.followTail) void scrollToBottom(true);
  },
  { flush: "post" },
);

watch(
  () => {
    const last = props.rows[props.rows.length - 1];
    return last ? `${stableRowKey(last)}|${last.message.length}` : "";
  },
  () => {
    if (props.followTail) void scrollToBottom(true);
  },
  { flush: "post" },
);

watch(
  () => props.followTail,
  (on) => {
    if (on) void scrollToBottom(true);
  },
);

onMounted(() => {
  bindViewport();
  void scrollToBottom(true);
});

onUnmounted(() => {
  ro?.disconnect();
  ro = null;
  scrollBottomToken += 1;
});

defineExpose({ scrollToBottom });
</script>

<template>
  <div class="log-virtual-feed-wrap">
    <div
      ref="scrollEl"
      class="log-feed log-virtual-feed"
      @scroll.passive="onScroll"
    >
      <div
        class="log-virtual-feed__spacer"
        :style="{ height: `${totalHeight}px` }"
      >
        <div
          class="log-virtual-feed__window"
          :style="{ transform: `translateY(${offsetY}px)` }"
        >
          <button
            v-for="{ row, stableKey, domKey } in visibleRows"
            :key="domKey"
            type="button"
            class="log-line log-line--virtual"
            :class="{ 'log-line--virtual-active': expandedKey === stableKey }"
            :style="{ minHeight: `${rowHeight}px`, height: `${rowHeight}px` }"
            :title="previewMessage(row.message)"
            @click="toggleRow(stableKey, row)"
          >
            <span class="log-line__time">{{ formatLogDisplayTime(row.time) }}</span>
            <span :class="['log-line__lv-tag', `log-line__lv-tag--${row.level}`]">{{ row.level }}</span>
            <span
              v-if="row.scope"
              class="log-line__scope"
            >[{{ row.scope }}]</span>
            <span class="log-line__msg log-line__msg--clip">{{ previewMessage(row.message) }}</span>
          </button>
        </div>
      </div>
    </div>
    <div
      v-if="expandedRow"
      class="log-virtual-feed__detail"
    >
      <div class="log-virtual-feed__detail-meta">
        <span class="log-line__time">{{ formatLogDisplayTime(expandedRow.time) }}</span>
        <span :class="['log-line__lv-tag', `log-line__lv-tag--${expandedRow.level}`]">{{ expandedRow.level }}</span>
        <span
          v-if="expandedRow.scope"
          class="log-line__scope"
        >[{{ expandedRow.scope }}]</span>
        <button
          type="button"
          class="ui-btn ui-btn--ghost ui-btn--sm log-virtual-feed__detail-close"
          @click="expandedKey = null; expandedSnapshot = null"
        >
          收起
        </button>
      </div>
      <pre class="log-virtual-feed__detail-body">{{ expandedRow.message }}</pre>
    </div>
  </div>
</template>

<style scoped>
.log-virtual-feed-wrap {
  display: flex;
  flex-direction: column;
  gap: 8px;
  min-height: 0;
  flex: 1;
}
.log-virtual-feed {
  position: relative;
  overflow-y: auto;
  flex: 1;
  min-height: 0;
  max-height: none;
  /* 覆盖全局 .log-feed 的 padding，避免估高贴底后视觉上仍「差一截」 */
  padding: 0;
}
.log-virtual-feed__spacer {
  position: relative;
  width: 100%;
}
.log-virtual-feed__window {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
}
.log-line--virtual {
  display: flex;
  align-items: center;
  gap: 8px;
  width: 100%;
  box-sizing: border-box;
  padding: 0 10px;
  margin: 0;
  border: none;
  background: transparent;
  color: inherit;
  font: inherit;
  text-align: left;
  cursor: pointer;
}
.log-line--virtual:hover,
.log-line--virtual-active {
  background: color-mix(in srgb, var(--accent) 8%, transparent);
}
.log-line--virtual .log-line__lv-tag {
  flex-shrink: 0;
}
.log-line--virtual .log-line__scope {
  flex: 0 1 7rem;
  max-width: 7rem;
}
.log-line--virtual .log-line__msg--clip {
  flex: 1 1 auto;
  min-width: 0;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.log-virtual-feed__detail {
  flex-shrink: 0;
  padding: 10px 12px;
  border-radius: var(--radius-md);
  border: 1px solid color-mix(in srgb, var(--accent) 28%, var(--border));
  background: color-mix(in srgb, var(--bg-elev) 92%, transparent);
}
.log-virtual-feed__detail-meta {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 8px;
  margin-bottom: 8px;
}
.log-virtual-feed__detail-close {
  margin-left: auto;
  padding: 4px 10px;
  min-height: 0;
  font-size: 12px;
}
.log-virtual-feed__detail-body {
  margin: 0;
  max-height: min(220px, 28vh);
  overflow: auto;
  white-space: pre-wrap;
  word-break: break-word;
  font-family: var(--font-mono);
  font-size: 11px;
  line-height: 1.45;
  color: var(--text);
}
</style>
