// react/src/components/PluginConfigDialog.tsx
import { useMemo, useRef, useState } from "react";
import { Link } from "react-router-dom";
import ConsoleModal from "@/components/ConsoleModal";
import PluginConfigWorkspace, {
  type PluginConfigWorkspaceHandle,
} from "@/components/PluginConfigWorkspace";
import type {
  CommunityPluginRow,
  OfficialExtensionRow,
  PluginRow,
} from "@/api/pallasTypes";
import { AI_ENTRY_PLUGIN_CONFIG_CHECK } from "@/config/aiEntrySemantics";
import { aiConfigSectionPath } from "@/config/aiConfigSections";
import { resolvePluginReadmeTarget } from "@/utils/pluginReadmeTarget";

type Props = {
  open: boolean;
  pluginName: string;
  pluginRow: PluginRow | null;
  officialExtensions: OfficialExtensionRow[];
  communityPlugins: CommunityPluginRow[];
  onClose: () => void;
};

export default function PluginConfigDialog({
  open,
  pluginName,
  pluginRow,
  officialExtensions,
  communityPlugins,
  onClose,
}: Props) {
  const workspaceRef = useRef<PluginConfigWorkspaceHandle>(null);
  const [status, setStatus] = useState<Omit<PluginConfigWorkspaceHandle, "save" | "runConfigCheck">>({
    saving: false,
    checking: false,
    loading: true,
    hasData: false,
    supportsConfigCheck: false,
  });

  const displayTitle = pluginRow?.metadata?.name || pluginName;
  const pluginResolvedId = (pluginRow?.resolved_plugin_id || pluginName).trim();
  const showDrawAiConfigHint = pluginResolvedId === "draw";

  const readmeTarget = useMemo(() => {
    if (!pluginRow) return null;
    return resolvePluginReadmeTarget(
      pluginRow as Parameters<typeof resolvePluginReadmeTarget>[0],
      officialExtensions as Parameters<typeof resolvePluginReadmeTarget>[1],
      communityPlugins as Parameters<typeof resolvePluginReadmeTarget>[2],
    );
  }, [pluginRow, officialExtensions, communityPlugins]);

  const canSave =
    status.hasData && !status.loading && !status.saving && !status.checking;

  return (
    <ConsoleModal
      open={open && Boolean(pluginName)}
      titleId="plugin-config-dialog-title"
      panelClass="plugin-config-dialog"
      bodyClass="plugin-config-dialog__bd"
      busy={status.saving}
      onClose={onClose}
      header={
        <>
          <div className="console-modal__head-text plugin-config-dialog__head">
            <div className="plugin-config-dialog__head-text">
              <h2 id="plugin-config-dialog-title" className="console-modal__title">
                {displayTitle}
              </h2>
              <p className="console-modal__subtitle">
                <code>{pluginResolvedId}</code>
              </p>
            </div>
          </div>
          <button type="button" className="console-modal__close" aria-label="关闭" onClick={onClose}>
            ×
          </button>
        </>
      }
      footer={
        <div className="plugin-config-dialog__foot row-actions">
          {status.supportsConfigCheck ? (
            <button
              type="button"
              className="btn btn--outline"
              disabled={!canSave}
              onClick={() => void workspaceRef.current?.runConfigCheck()}
            >
              {status.checking ? "检测中…" : AI_ENTRY_PLUGIN_CONFIG_CHECK.label}
            </button>
          ) : null}
          <button
            type="button"
            className="btn btn--primary"
            disabled={!canSave}
            title="Ctrl+S"
            onClick={() => void workspaceRef.current?.save()}
          >
            {status.saving ? "保存中…" : "保存"}
          </button>
        </div>
      }
    >
      {showDrawAiConfigHint ? (
        <p className="muted plugin-config-dialog__ai-hint">
          推荐在 <Link to={aiConfigSectionPath("draw")}>AI 配置 · 画画</Link>
          管理网关；本页为兼容入口，配置键相同。
        </p>
      ) : null}
      {pluginName ? (
        <PluginConfigWorkspace
          key={pluginName}
          ref={workspaceRef}
          presentation="dialog"
          pluginName={pluginName}
          initialPluginRow={pluginRow}
          readmeTarget={readmeTarget}
          onStatusChange={setStatus}
        />
      ) : null}
    </ConsoleModal>
  );
}

// src/components/PluginConfigDialog.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import type { CommunityPluginRow, OfficialExtensionRow, PluginRow } from "@/api/pallasTypes";
import PluginConfigWorkspace from "@/components/PluginConfigWorkspace.vue";
import PluginIcon from "@/components/PluginIcon.vue";
import UiButton from "@/components/ui/UiButton.vue";
import UiDialog from "@/components/ui/UiDialog.vue";
import { AI_ENTRY_PLUGIN_CONFIG_CHECK } from "@/config/aiEntrySemantics";
import { aiConfigSectionPath } from "@/config/aiConfigSections";
import { resolvePluginReadmeTarget } from "@/utils/pluginReadmeTarget";
import { RouterLink } from "vue-router";

const props = defineProps<{
  open: boolean;
  pluginName: string;
  pluginRow: PluginRow | null;
  iconUrl?: string | null;
  officialExtensions: OfficialExtensionRow[];
  communityPlugins: CommunityPluginRow[];
}>();

const emit = defineEmits<{ close: [] }>();

const workspaceRef = ref<InstanceType<typeof PluginConfigWorkspace> | null>(null);

const displayTitle = computed(
  () => props.pluginRow?.metadata?.name || props.pluginName,
);

const pluginResolvedId = computed(
  () => (props.pluginRow?.resolved_plugin_id || props.pluginName).trim(),
);

const readmeTarget = computed(() => {
  if (!props.pluginRow) return null;
  return resolvePluginReadmeTarget(
    props.pluginRow,
    props.officialExtensions,
    props.communityPlugins,
  );
});

const canSave = computed(
  () =>
    Boolean(workspaceRef.value?.data) &&
    !workspaceRef.value?.loading &&
    !workspaceRef.value?.saving &&
    !workspaceRef.value?.checking,
);

const showDrawAiConfigHint = computed(() => pluginResolvedId.value === "draw");

function requestClose() {
  emit("close");
}
</script>

<template>
  <UiDialog
    :open="open && Boolean(pluginName)"
    title-id="plugin-config-dialog-title"
    panel-class="plugin-config-dialog"
    body-class="plugin-config-dialog__bd"
    @close="requestClose"
  >
    <template #header>
      <div class="console-modal__head-text plugin-config-dialog__head">
        <PluginIcon
          class="plugin-config-dialog__icon"
          :plugin-id="pluginResolvedId"
          :label="displayTitle"
          :icon-url="iconUrl"
          size="md"
        />
        <div class="plugin-config-dialog__head-text">
          <h2
            id="plugin-config-dialog-title"
            class="console-modal__title"
          >
            {{ displayTitle }}
          </h2>
          <p class="console-modal__subtitle">
            <code>{{ pluginResolvedId }}</code>
          </p>
        </div>
      </div>
      <button
        type="button"
        class="console-modal__close"
        aria-label="关闭"
        @click="requestClose"
      >
        ×
      </button>
    </template>

    <p
      v-if="showDrawAiConfigHint"
      class="muted plugin-config-dialog__ai-hint"
    >
      推荐在
      <RouterLink :to="aiConfigSectionPath('draw')">AI 配置 · 画画</RouterLink>
      管理网关；本页为兼容入口，配置键相同。
    </p>

    <PluginConfigWorkspace
      v-if="pluginName"
      :key="pluginName"
      ref="workspaceRef"
      presentation="dialog"
      :plugin-name="pluginName"
      :icon-url="iconUrl"
      :initial-plugin-row="pluginRow"
      :readme-target="readmeTarget"
    />

    <template #footer>
      <div class="plugin-config-dialog__foot row-actions">
        <UiButton
          v-if="workspaceRef?.supportsConfigCheck"
          variant="outline"
          :disabled="!canSave"
          :busy="workspaceRef?.checking"
          @click="workspaceRef?.runConfigCheck()"
        >
          {{ workspaceRef?.checking ? "检测中…" : AI_ENTRY_PLUGIN_CONFIG_CHECK.label }}
        </UiButton>
        <UiButton
          variant="primary"
          :disabled="!canSave"
          :busy="workspaceRef?.saving"
          title="Ctrl+S"
          @click="workspaceRef?.save()"
        >
          {{ workspaceRef?.saving ? "保存中…" : "保存" }}
        </UiButton>
      </div>
    </template>
  </UiDialog>
</template>

<style scoped>
.plugin-config-dialog__ai-hint {
  margin: 0 16px 12px;
  font-size: 0.8125rem;
}
</style>
