// src/components/PluginConfigDialog.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import type { CommunityPluginRow, OfficialExtensionRow, PluginRow } from "@/api/pallasTypes";
import PluginConfigWorkspace from "@/components/PluginConfigWorkspace.vue";
import PluginIcon from "@/components/PluginIcon.vue";
import UiButton from "@/components/ui/UiButton.vue";
import UiDialog from "@/components/ui/UiDialog.vue";
import { AI_ENTRY_PLUGIN_CONFIG_CHECK } from "@/config/aiEntrySemantics";
import { aiConfigSectionPath } from "@/config/aiConfigSections";
import { resolvePluginReadmeTarget } from "@/utils/pluginReadmeTarget";
import { RouterLink } from "vue-router";

const props = defineProps<{
  open: boolean;
  pluginName: string;
  pluginRow: PluginRow | null;
  iconUrl?: string | null;
  officialExtensions: OfficialExtensionRow[];
  communityPlugins: CommunityPluginRow[];
}>();

const emit = defineEmits<{ close: [] }>();

const workspaceRef = ref<InstanceType<typeof PluginConfigWorkspace> | null>(null);

const displayTitle = computed(
  () => props.pluginRow?.metadata?.name || props.pluginName,
);

const pluginResolvedId = computed(
  () => (props.pluginRow?.resolved_plugin_id || props.pluginName).trim(),
);

const readmeTarget = computed(() => {
  if (!props.pluginRow) return null;
  return resolvePluginReadmeTarget(
    props.pluginRow,
    props.officialExtensions,
    props.communityPlugins,
  );
});

const canSave = computed(
  () =>
    Boolean(workspaceRef.value?.data) &&
    !workspaceRef.value?.loading &&
    !workspaceRef.value?.saving &&
    !workspaceRef.value?.checking,
);

const showDrawAiConfigHint = computed(() => pluginResolvedId.value === "draw");

function requestClose() {
  emit("close");
}
</script>

<template>
  <UiDialog
    :open="open && Boolean(pluginName)"
    title-id="plugin-config-dialog-title"
    panel-class="plugin-config-dialog"
    body-class="plugin-config-dialog__bd"
    @close="requestClose"
  >
    <template #header>
      <div class="console-modal__head-text plugin-config-dialog__head">
        <PluginIcon
          class="plugin-config-dialog__icon"
          :plugin-id="pluginResolvedId"
          :label="displayTitle"
          :icon-url="iconUrl"
          size="md"
        />
        <div class="plugin-config-dialog__head-text">
          <h2
            id="plugin-config-dialog-title"
            class="console-modal__title"
          >
            {{ displayTitle }}
          </h2>
          <p class="console-modal__subtitle">
            <code>{{ pluginResolvedId }}</code>
          </p>
        </div>
      </div>
      <button
        type="button"
        class="console-modal__close"
        aria-label="关闭"
        @click="requestClose"
      >
        ×
      </button>
    </template>

    <p
      v-if="showDrawAiConfigHint"
      class="muted plugin-config-dialog__ai-hint"
    >
      推荐在
      <RouterLink :to="aiConfigSectionPath('draw')">AI 配置 · 画画</RouterLink>
      管理网关；本页为兼容入口，配置键相同。
    </p>

    <PluginConfigWorkspace
      v-if="pluginName"
      :key="pluginName"
      ref="workspaceRef"
      presentation="dialog"
      :plugin-name="pluginName"
      :icon-url="iconUrl"
      :initial-plugin-row="pluginRow"
      :readme-target="readmeTarget"
    />

    <template #footer>
      <div class="plugin-config-dialog__foot row-actions">
        <UiButton
          v-if="workspaceRef?.supportsConfigCheck"
          variant="outline"
          :disabled="!canSave"
          :busy="workspaceRef?.checking"
          @click="workspaceRef?.runConfigCheck()"
        >
          {{ workspaceRef?.checking ? "检测中…" : AI_ENTRY_PLUGIN_CONFIG_CHECK.label }}
        </UiButton>
        <UiButton
          variant="primary"
          :disabled="!canSave"
          :busy="workspaceRef?.saving"
          title="Ctrl+S"
          @click="workspaceRef?.save()"
        >
          {{ workspaceRef?.saving ? "保存中…" : "保存" }}
        </UiButton>
      </div>
    </template>
  </UiDialog>
</template>

<style scoped>
.plugin-config-dialog__ai-hint {
  margin: 0 16px 12px;
  font-size: 0.8125rem;
}
</style>

// src/components/PluginConfigDialog.tsx
import { useMemo, useRef, useState } from "react";
import { Link } from "react-router-dom";
import PluginConfigWorkspace, {
  type PluginConfigWorkspaceHandle,
} from "@/components/PluginConfigWorkspace";
import type {
  CommunityPluginRow,
  OfficialExtensionRow,
  PluginRow,
} from "@/api/pallasTypes";
import { AI_ENTRY_PLUGIN_CONFIG_CHECK } from "@/config/aiEntrySemantics";
import { aiConfigSectionPath } from "@/config/aiConfigSections";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { resolvePluginReadmeTarget } from "@/utils/pluginReadmeTarget";

type Props = {
  open: boolean;
  pluginName: string;
  pluginRow: PluginRow | null;
  officialExtensions: OfficialExtensionRow[];
  communityPlugins: CommunityPluginRow[];
  onClose: () => void;
};

/** 插件配置弹窗：shadcn Dialog（居中实心底）。 */
export default function PluginConfigDialog({
  open,
  pluginName,
  pluginRow,
  officialExtensions,
  communityPlugins,
  onClose,
}: Props) {
  const workspaceRef = useRef<PluginConfigWorkspaceHandle>(null);
  const [status, setStatus] = useState<Omit<PluginConfigWorkspaceHandle, "save" | "runConfigCheck">>({
    saving: false,
    checking: false,
    loading: true,
    hasData: false,
    supportsConfigCheck: false,
  });

  const onStatusChange = (next: Omit<PluginConfigWorkspaceHandle, "save" | "runConfigCheck">) => {
    setStatus((prev) => {
      if (
        prev.saving === next.saving &&
        prev.checking === next.checking &&
        prev.loading === next.loading &&
        prev.hasData === next.hasData &&
        prev.supportsConfigCheck === next.supportsConfigCheck
      ) {
        return prev;
      }
      return next;
    });
  };

  const displayTitle = pluginRow?.metadata?.name || pluginName;
  const pluginResolvedId = (pluginRow?.resolved_plugin_id || pluginName).trim();
  const showDrawAiConfigHint = pluginResolvedId === "draw";

  const readmeTarget = useMemo(() => {
    if (!pluginRow) return null;
    return resolvePluginReadmeTarget(
      pluginRow as Parameters<typeof resolvePluginReadmeTarget>[0],
      officialExtensions as Parameters<typeof resolvePluginReadmeTarget>[1],
      communityPlugins as Parameters<typeof resolvePluginReadmeTarget>[2],
    );
  }, [pluginRow, officialExtensions, communityPlugins]);

  const canSave = status.hasData && !status.loading && !status.saving && !status.checking;
  const busy = status.saving;

  function requestClose() {
    if (busy) return;
    onClose();
  }

  return (
    <Dialog
      open={open && Boolean(pluginName)}
      onOpenChange={(next) => {
        if (!next) requestClose();
      }}
    >
      <DialogContent
        className="plugin-config-dialog flex max-h-[min(960px,calc(100dvh-32px))] w-[min(960px,calc(100vw-32px))] max-w-[min(960px,calc(100vw-32px))] gap-0 overflow-hidden bg-card p-0"
        onEscapeKeyDown={(e) => {
          if (busy) e.preventDefault();
        }}
        onPointerDownOutside={(e) => {
          if (busy) e.preventDefault();
        }}
      >
        <DialogHeader className="plugin-config-dialog__head border-b border-[color-mix(in_srgb,var(--border)_70%,transparent)] px-4 py-3 text-left sm:text-left">
          <div className="plugin-config-dialog__head-text w-full space-y-1 pr-6 text-left">
            <DialogTitle id="plugin-config-dialog-title" className="text-left">{displayTitle}</DialogTitle>
            <DialogDescription asChild>
              <p className="font-mono text-xs text-muted-foreground">
                <code>{pluginResolvedId}</code>
              </p>
            </DialogDescription>
          </div>
        </DialogHeader>

        <div className="plugin-config-dialog__bd min-h-0 flex-1 overflow-auto">
          {showDrawAiConfigHint ? (
            <p className="px-4 pt-3 text-sm text-muted-foreground">
              推荐在 <Link to={aiConfigSectionPath("media", "draw")} className="text-primary underline-offset-2 hover:underline">AI 配置 · 画画</Link>
              管理网关；本页为兼容入口，配置键相同。
            </p>
          ) : null}
          {pluginName ? (
            <PluginConfigWorkspace
              key={pluginName}
              ref={workspaceRef}
              presentation="dialog"
              pluginName={pluginName}
              initialPluginRow={pluginRow}
              readmeTarget={readmeTarget}
              onStatusChange={onStatusChange}
            />
          ) : null}
        </div>

        <DialogFooter className="plugin-config-dialog__foot border-t border-[color-mix(in_srgb,var(--border)_70%,transparent)] px-4 py-3 sm:justify-end">
          {status.supportsConfigCheck ? (
            <Button
              type="button"
              variant="outline"
              size="sm"
              disabled={!canSave}
              onClick={() => void workspaceRef.current?.runConfigCheck()}
            >
              {status.checking ? "检测中…" : AI_ENTRY_PLUGIN_CONFIG_CHECK.label}
            </Button>
          ) : null}
          <Button
            type="button"
            size="sm"
            disabled={!canSave}
            title="Ctrl+S"
            onClick={() => void workspaceRef.current?.save()}
          >
            {status.saving ? "保存中…" : "保存"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
