// src/components/PrefsSettingCard.tsx
import type { ReactNode } from "react";

export default function PrefsSettingCard({
  title,
  lead,
  wide,
  cardId,
  children,
}: {
  title: ReactNode;
  lead?: string;
  wide?: boolean;
  cardId?: string;
  children: ReactNode;
}) {
  return (
    <section
      id={cardId || undefined}
      className={`prefs-setting-card panel${wide ? " prefs-setting-card--wide" : ""}`}
    >
      <header className="prefs-setting-card__hd">
        <div className="prefs-setting-card__head-text">
          <h3 className="panel__title prefs-setting-card__title">{title}</h3>
          {lead ? <p className="prefs-setting-card__lead muted">{lead}</p> : null}
        </div>
      </header>
      <div className="prefs-setting-card__bd">{children}</div>
    </section>
  );
}

// src/components/PrefsSettingCard.vue
<script setup lang="ts">
import ConsoleNavIcon from "@/components/ConsoleNavIcon.vue";
import type { ConsoleNavIconId } from "@/config/consoleNavIcons";

withDefaults(
  defineProps<{
    icon?: ConsoleNavIconId | string;
    title: string;
    lead?: string;
    wide?: boolean;
    cardId?: string;
  }>(),
  {
    icon: "dashboard",
    lead: "",
    wide: false,
    cardId: "",
  },
);
</script>

<template>
  <section
    :id="cardId || undefined"
    class="prefs-setting-card panel"
    :class="{ 'prefs-setting-card--wide': wide }"
  >
    <header class="prefs-setting-card__hd">
      <div class="prefs-setting-card__head-text">
        <h3 class="panel__title prefs-setting-card__title">
          <ConsoleNavIcon
            class="panel__title-ico"
            :name="icon"
          />{{ title }}
        </h3>
        <p
          v-if="lead"
          class="prefs-setting-card__lead muted"
        >
          {{ lead }}
        </p>
      </div>
    </header>
    <div class="prefs-setting-card__bd">
      <slot />
    </div>
  </section>
</template>
