// src/components/ReadmeMarkdown.tsx
import { useEffect, useRef } from "react";
import { setupReadmeCodeCopyButtons } from "@/utils/readmeCodeCopy";

type Props = {
  html: string;
  /** 默认含 readme-markdown；更新页等自带排版时可整段覆盖。 */
  className?: string;
};

/** Markdown HTML 容器：挂载后为代码块补幽灵 Copy。 */
export default function ReadmeMarkdown({
  html,
  className = "readme-markdown markdown-body",
}: Props) {
  const rootRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const el = rootRef.current;
    if (!el) return;
    const next = html.trim() ? html : "";
    el.innerHTML = next;
    if (!next) return;
    return setupReadmeCodeCopyButtons(el);
  }, [html]);

  return <div ref={rootRef} className={className} />;
}

// src/components/ReadmeMarkdown.vue
<script setup lang="ts">
import { nextTick, onBeforeUnmount, ref, watch } from "vue";
import { setupReadmeCodeCopyButtons } from "@/utils/readmeCodeCopy";

const props = withDefaults(
  defineProps<{
    html: string;
    extraClass?: string;
  }>(),
  {
    extraClass: "",
  },
);

const root = ref<HTMLElement | null>(null);
let teardown: (() => void) | null = null;

async function refreshCopyButtons() {
  teardown?.();
  teardown = null;
  if (!props.html.trim()) return;
  await nextTick();
  if (!root.value) return;
  teardown = setupReadmeCodeCopyButtons(root.value);
}

watch(
  () => props.html,
  () => {
    void refreshCopyButtons();
  },
  { immediate: true },
);

onBeforeUnmount(() => {
  teardown?.();
});
</script>

<template>
  <div
    ref="root"
    class="readme-markdown markdown-body"
    :class="extraClass"
    v-html="html"
  />
</template>
