// src/components/PluginStoreCardSkeleton.vue
<template>
  <div
    class="plugin-store-card plugin-store-card--skeleton"
    aria-hidden="true"
  >
    <div class="plugin-store-card__layout">
      <div class="plugin-store-card__media">
        <div class="plugin-store-card__cover plugin-store-card__skel plugin-store-card__skel--round" />
      </div>
      <div class="plugin-store-card__info">
        <div class="plugin-store-card__skel plugin-store-card__skel--title" />
        <div class="plugin-store-card__skel plugin-store-card__skel--line plugin-store-card__skel--short" />
      </div>
      <div class="plugin-store-card__summary">
        <div class="plugin-store-card__skel plugin-store-card__skel--line" />
        <div class="plugin-store-card__skel plugin-store-card__skel--line plugin-store-card__skel--short" />
      </div>
    </div>
    <footer class="plugin-store-card__foot">
      <div class="plugin-store-card__skel plugin-store-card__skel--btn" />
    </footer>
  </div>
</template>

// react/src/components/PluginStoreCardSkeleton.tsx
export default function PluginStoreCardSkeleton() {
  return (
    <div className="plugin-store-card plugin-store-card--skeleton ui-card ui-card--glass" aria-hidden="true">
      <div className="ui-card__content">
        <div className="plugin-store-card__layout">
          <div className="plugin-store-card__media">
            <div className="plugin-store-card__cover plugin-store-card__skel plugin-store-card__skel--round" />
          </div>
          <div className="plugin-store-card__info">
            <div className="plugin-store-card__skel plugin-store-card__skel--title" />
            <div className="plugin-store-card__skel plugin-store-card__skel--line plugin-store-card__skel--short" />
          </div>
          <div className="plugin-store-card__summary">
            <div className="plugin-store-card__skel plugin-store-card__skel--line" />
            <div className="plugin-store-card__skel plugin-store-card__skel--line plugin-store-card__skel--short" />
          </div>
        </div>
      </div>
      <div className="ui-card__footer">
        <footer className="plugin-store-card__foot">
          <div className="plugin-store-card__skel plugin-store-card__skel--btn" />
        </footer>
      </div>
    </div>
  );
}
