// src/components/StatCard.vue
<script setup lang="ts">
defineProps<{
  label: string;
  value: string | number;
  hint?: string;
  /** 更小的内边距与数值，用于仪表盘等密集布局 */
  dense?: boolean;
}>();
</script>

<template>
  <div
    class="card stat-card"
    :class="{ 'stat-card--dense': dense }"
  >
    <div class="card__body">
      <div class="stat-card__label">{{ label }}</div>
      <div class="stat-card__value">{{ value }}</div>
      <div
        v-if="hint"
        class="stat-card__hint"
      >
        {{ hint }}
      </div>
    </div>
  </div>
</template>

// react/src/components/StatCard.tsx
export default function StatCard({
  label,
  value,
  hint,
  dense = false,
}: {
  label: string;
  value: string | number;
  hint?: string;
  dense?: boolean;
}) {
  return (
    <div className={`ui-card ui-card--glass stat-card${dense ? " stat-card--dense" : ""}`}>
      <div className="ui-card__content">
        <div className="card__body">
          <div className="stat-card__label">{label}</div>
          <div className="stat-card__value">{value}</div>
          {hint ? <div className="stat-card__hint">{hint}</div> : null}
        </div>
      </div>
    </div>
  );
}
