// react/src/components/ui/UiField.tsx
/**
 * @deprecated 新代码可用 Label + 自建布局，或后续 Field 原语。
 * 本壳保留 Vue 期字段标签行结构。
 */
import type { ReactNode } from "react";
import { Label } from "@/components/ui/label";
import { cn } from "@/lib/utils";

export default function UiField({
  label,
  required = false,
  secret = false,
  hideLabel = false,
  className,
  labelEnd,
  meta,
  children,
}: {
  label?: string;
  required?: boolean;
  secret?: boolean;
  hideLabel?: boolean;
  className?: string;
  labelEnd?: ReactNode;
  meta?: ReactNode;
  children: ReactNode;
}) {
  const showLabelRow = !hideLabel && Boolean(label || labelEnd || meta);

  return (
    <div className={cn("ui-field space-y-1.5", className)}>
      {showLabelRow ? (
        <div className="ui-field__label-row flex items-start justify-between gap-2">
          <div className="ui-field__label flex min-w-0 items-center gap-1.5">
            <div className="ui-field__title flex min-w-0 items-center gap-1.5">
              {label ? (
                <Label className="ui-field__label-text truncate" title={label}>
                  {label}
                </Label>
              ) : null}
              {labelEnd}
            </div>
            {required ? (
              <span className="text-destructive" aria-hidden="true">
                *
              </span>
            ) : null}
            {secret ? (
              <span className="rounded-[var(--radius-control,6px)] bg-muted px-1.5 py-0.5 text-[10px] font-medium text-muted-foreground">
                密钥
              </span>
            ) : null}
          </div>
          {meta ? <div className="ui-field__meta shrink-0 text-xs text-muted-foreground">{meta}</div> : null}
        </div>
      ) : null}
      <div className="ui-field__control">{children}</div>
    </div>
  );
}

// src/components/ui/UiField.vue
<script setup lang="ts">
withDefaults(
  defineProps<{
    label?: string;
    required?: boolean;
    secret?: boolean;
    /** 无 label 时仍可渲染控件 */
    hideLabel?: boolean;
  }>(),
  {
    required: false,
    secret: false,
    hideLabel: false,
  },
);
</script>

<template>
  <div class="ui-field">
    <div
      v-if="!hideLabel && (label || $slots['label-end'] || $slots.meta)"
      class="ui-field__label-row"
    >
      <div class="ui-field__label">
        <div class="ui-field__title">
          <span
            v-if="label"
            class="ui-field__label-text"
            :title="label"
          >{{ label }}</span>
          <slot name="label-end" />
        </div>
        <span
          v-if="required"
          class="ui-field__required"
          aria-hidden="true"
        >*</span>
        <span
          v-if="secret"
          class="ui-field__secret"
        >密钥</span>
      </div>
      <div
        v-if="$slots.meta"
        class="ui-field__meta"
      >
        <slot name="meta" />
      </div>
    </div>
    <div class="ui-field__control">
      <slot />
    </div>
  </div>
</template>

<style scoped>
.ui-field {
  display: grid;
  gap: 8px;
  min-width: 0;
  max-width: 100%;
  align-content: start;
  overflow: hidden;
}

.ui-field__label-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
  min-width: 0;
  min-height: 20px;
  max-width: 100%;
  overflow: hidden;
}

.ui-field__label {
  display: flex;
  align-items: center;
  gap: 6px;
  min-width: 0;
  flex: 1 1 0;
  overflow: hidden;
  color: var(--text-muted);
  font-size: 13px;
  line-height: 1.35;
  font-weight: 500;
}

/* 标题 + ? 成组贴齐；勿让文字 flex 撑开把帮助钮推到行尾 */
.ui-field__title {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  min-width: 0;
  max-width: 100%;
  flex: 0 1 auto;
}

.ui-field__label-text {
  flex: 0 1 auto;
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.ui-field__required {
  color: color-mix(in srgb, var(--danger, #ef4444) 80%, var(--text) 10%);
  font-size: 12px;
  line-height: 1;
  flex-shrink: 0;
}

.ui-field__secret {
  display: inline-flex;
  align-items: center;
  min-height: 18px;
  padding: 0 6px;
  border-radius: 999px;
  border: 1px solid color-mix(in srgb, #f59e0b 42%, transparent);
  background: color-mix(in srgb, #f59e0b 8%, transparent);
  color: color-mix(in srgb, #f59e0b 84%, var(--text) 8%);
  font-size: 10px;
  font-weight: 600;
  line-height: 1;
  flex-shrink: 0;
}

.ui-field__meta {
  display: flex;
  align-items: center;
  gap: 6px;
  flex: 0 0 auto;
  max-width: 42%;
  min-width: 0;
  overflow: hidden;
  transition: opacity 0.15s ease;
}

.ui-field__control {
  min-width: 0;
  max-width: 100%;
}

@media (hover: hover) and (pointer: fine) {
  .ui-field__meta {
    opacity: 0;
  }

  .ui-field:hover .ui-field__meta,
  .ui-field:focus-within .ui-field__meta {
    opacity: 1;
  }
}

@media (max-width: 560px) {
  .ui-field__label-row {
    flex-wrap: wrap;
    row-gap: 4px;
  }

  .ui-field__label {
    flex: 1 1 auto;
    max-width: 100%;
  }

  .ui-field__meta {
    opacity: 1;
    max-width: 100%;
    flex: 1 1 auto;
  }
}
</style>
